### ISSUE TITLE
only one host thread launch CUDA kernel in 20.03

### ISSUE THREAD

**Issue by guoners** [triton-inference-server/server#1663]
Hi, I used trtis(19.11) and triton(20.03) to do some inferences with multi instances. 
However, when I profiled the sever process with Nsight System, I found that in 19.11, there are multi host pthreads that perform CUDA kernel launch (#pthread equal to #instance), and there is only one host pthread that launch CUDA kernel in 20.03. It seems to have a bad influence on the overall performance.
And I didn't find any cmdl options or model configures that control it. ( I checked triton doc and part of source code)
Did I miss anything?
And I wonder how to use multi host pthreads to perform kernel launch in 20.03.
Thanks a lot!

**Comment by GuanLuo** [comment]
The intuition is that using multiple threads to launch CUDA kernels will introduce CUDA contention, thus we changed it to let one thread to launch the CUDA works. Can you share your results regarding the bad influence?

**Comment by guoners** [comment]
We used qa_container built from Dockfile.QA, and used resnet50 as an example.
TensorRT generates serialized models.
The max batch size is set in {1,2,4,8,...,256}, and batch size is equal to MBS in each test.
And the #inst is set in {1,2,3,...,8,10,...,16}
In most situations, 20.03 outperforms 19.11.
But when MBS lower than 8, and #inst larger than 6 or 8, 19.11 has better performance.
Here is part of the results.
![res50-mbs4](https://user-images.githubusercontent.com/13401338/84845139-7e53a400-b07e-11ea-8301-ecb8dcd34159.png)
![res50-mbs32](https://user-images.githubusercontent.com/13401338/84845159-86abdf00-b07e-11ea-857b-8a107624ecb3.png)

**Comment by guoners** [comment]
> The intuition is that using multiple threads to launch CUDA kernels will introduce CUDA contention, thus we changed it to let one thread to launch the CUDA works. Can you share your results regarding the bad influence?

Thanks for replying, and we found there still are the same number of host threads as the number of instances in the server process. It seems these host threads only launch cudaEvenSynchronize and incur pthread_cond_wait, which brought overhead. Is this optimizable?

**Comment by GuanLuo** [comment]
The host threads that perform only `cudaEventSynchronize` is the completion thread, not the issuing thread. There is one completion thread for each instance as `cudaEventSynchronize` will block the host thread which is not desired for other approach of using one completion thread for all instances (need to spin-looping each instance's event state in that case).

Can you share the profiling result (i.e. nsys report) on the overhead you found? I don't think the completion threads will incur overhead as the workflow in completion threads is lightweight and `cudaEventSynchronize` is quite responsive to when the event is completed.

Also what is the procedure for you to generate the above diagrams? There are many components in between sending requests and receiving responses and I can't tell if the overhead is solely due to how CUDA kernels are being launched simply from the diagrams. It will also be helpful if you can run the two Triton versions with perf_client which will show the breakdowns of time spent in each phase of the pipeline.

**Comment by guoners** [comment]
> The 20.03 implementation should not require a large number of model instances to get the best performance. Usually just 1 or 2 instances will give the maximum throughput. Do you have cases where the maximum thoughput found with 19.11 is significantly greater than the maximum throughput of 20.03, using the best configuration for each?

No, 20.03 has better performance in most of my tests. In some cases, 19.11 has slight advantages.
However, in my nsight system profile results, I notice the interval between the launches of the batches is quite long (around 1.5ms). The separation of kernel launches seems to hurt performance, especially in small models. How can we reduce this space?
