### ISSUE TITLE
can we use inference server for the codes which doesnt have any model ?

### ISSUE THREAD

**Issue by DEEP2907** [triton-inference-server/server#1908]
Hi ,
I am trying to use inference server just for resolving concurrency issue of other server codes which doesnt have any model?

**Comment by deadeyegoodwin** [comment]
If you have some code that you want to run inside Triton as a "backend" so that you can send inference requests to it like you would any of the existing frameworks, then you want to implement your custom code in a backend. Triton is transitioning from an older backend API to a new one, so you should definitely work with the new one: https://github.com/NVIDIA/triton-inference-server/blob/master/docs/backend.rst
