### ISSUE TITLE
OOM error API

### ISSUE THREAD

**Issue by loveppdog** [triton-inference-server/server#1940]
I use triton server20.03 and  inference models include tf/pytorch/.....
And oom always happens when we inference.  Of course, I have tried to fix OOM with warm up and schedule process.
But not good.

Is there OOM/error API? 
I have checked trtserver --help and  can't find the suitable oom/error API.
I have used triton server context api to check serverstatus but not about oom error for a model. 
I want to monitor triton server  through API so that when oom/errors happen   and I can restart triton server.

And I find trition server log: some oom or  errors of logs are from tensorflow and I also hope to monitor these errors.

**Comment by deadeyegoodwin** [comment]
Do you mean that Triton crashes from an OOM? Or that an inference request fails because it runs out of memory?
There are health endpoints to check if triton is still running.
There are also status endpoints where you can check for a model how many times it has failed. These failures are not categorized by OOM but if you see failures you could use that as an indication to restart.

**Comment by loveppdog** [comment]
> here are also status endpoints where you can check for a model how many times it has failed. T

My case should be an inference request fails because it runs out of memory. 
So I should use status endpoints to check a model how many times it has failed.

Could you give me an example to use status endpoints? (I use triton 20.03. )

**Comment by CoderHam** [comment]
@loveppdog closing this ticket due to inactivity. Please reopen if required.
