### ISSUE TITLE
Missing models to run client examples

### ISSUE THREAD

**Issue by szaboak** [triton-inference-server/server#1960]
**Is your feature request related to a problem? Please describe.**
I'm trying to create some application with triton-inderence-server docker.
I followed to Quick start guide from https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/quickstart.html.

Downloaded the latest server and client sdk docker files:
nvcr.io/nvidia/tritonserver:20.08-py3
nvcr.io/nvidia/tritonserver:20.08-py3-clientsdk

Fetched models in the latest git branch:
git checkout r20.08
cd docs/examples
./fetch_models.sh

Some of the client examples work as expected, but many of them complain about missing models.
For example:

python /workspace/install/python/grpc_client.py:
	status = StatusCode.UNAVAILABLE
	details = "Request for unknown model: 'resnet_v1_50_graphdef' is not found"

python /workspace/install/python/simple_grpc_sequence_stream_infer_client.py:
Request for unknown model: 'simple_sequence' is not found

**Describe the solution you'd like**
All model files and repositories, that the examples need should be collected by the "fetch_models.sh" script.
This would help to use the examples as they are out of the box.

**Describe alternatives you've considered**

In the meantime could you please provide the missing models for me to try out the example. (Mainly the "simple_sequence is needed")

**Additional context**

**Comment by deadeyegoodwin** [comment]
There is actually no problem with the quickstart. The problem is that for the sequence examples you need the "simple_sequence" custom backend which needs to be built. https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/build.html#building-a-custom-backend

We are also in a transition from the old-style custom backends to the new triton backend API which confuses things some. But if you follow instructions in the link above you can build a libsequence.so and then use it with the model configuration in  qa/custom_models/custom_sequence_int32/config.pbtxt.

**Comment by szaboak** [comment]
Thanks, I found it in the meantime.
It works.
You can close this ticket.
