### ISSUE TITLE
GRPC python client get_model_config

### ISSUE THREAD

**Issue by YuanTingHsieh** [triton-inference-server/server#1971]
**Description**
Use tritongrpcclient to get_model_config with as_json flag turned on it will return a dict as expected.
But the dict has one key 'config' then all the things inside that dict.
Also, the dimension values in dim of input and output are specified in strings, but I expect it should be in numbers?

**Triton Information**
20.08 Triton container

**To Reproduce**
`
config = triton_client.get_model_config(model_name, model_version, as_json=True)
`
config will look like this:
{'config: {'name': 'segmentation_ct_spleen', 'platform': 'tensorflow_graphdef', 'version_policy': {'latest': {'num_versions': 1}}, 'max_batch_size': 1, 'input': [{'name': 'NV_MODEL_INPUT', 'data_type': 'TYPE_FP32', 'dims': ['1', '160', '160', '160']}], 'output': [{'name': 'NV_MODEL_OUTPUT', 'data_type': 'TYPE_FP32', 'dims': ['2', '160', '160', '160']}], 'instance_group': [{'name': 'segmentation_ct_spleen_0', 'count': 1, 'gpus': [0], 'kind': 'KIND_GPU'}], 'default_model_filename': 'model.graphdef', 'optimization': {'input_pinned_memory': {'enable': True}, 'output_pinned_memory': {'enable': True}}, 'backend': 'tensorflow'}}

**Expected behavior**
I guess we want the things inside dims to be numbers instead of strings?
Do we need the key 'config' if all things are inside this key?
It is fine to also stay like this but then this will be a little different vs HTTP client's get_model_config method

**Comment by deadeyegoodwin** [comment]
In my opinion protobuf is just broken around json generation in that they confuse the limitations of some languages/platforms to become the required limitations of all languages/platforms and don't provide an option to avoid those limitations. The common explanation given that json is specified as only supporting up to 56-bit integer is wrong but seems to be the standard response that closes all these kind of issues. For example, https://github.com/protocolbuffers/protobuf/issues/2954.

But since the GRPC client is explicitly using protobuf then we are going to just live with this brokenness. We will update the documentation to point out that the generated json will have int64 values represented as strings.
