### ISSUE TITLE
Datatype difference in model config and HTTP request body 

### ISSUE THREAD

**Issue by phuotran** [triton-inference-server/server#1996]
Hello,

I have a couple of questions concerning the datatype specified in the model configuration and the datatype specified in the HTTP request body when sending an inference request to the Triton HTTP endpoint.

1. It looks like the datatypes defined in the model configuration are the ones described in the [Triton doc](https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/model_configuration.html#datatypes), while the datatypes defined in the HTTP request body are the ones defined by [KFserving](https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md#tensor-data-types). Is that correct?

2. The [tensor binary extension](https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_binary_data.md) from Triton seems to allow to represent any datatype as binary data:
    ```
    All tensor data types are representable as binary data in the native size of the data type.
    ```
    Is that completely automated, i.e. can a user simply send `BYTES` data for a model that requires, e.g., 
  `TYPE_STRING` datatype (or any other datatype)?

3. According to the example in this [page](https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_binary_data.md), the datatype in the request body doesn't need to be `BYTES` for binary data? 

3. (Related to 2.) In the model examples, the `image_preprocess_nchw_3x224x224_inception` model requires a [`TYPE_STRING`](https://github.com/triton-inference-server/server/blob/6a7ef96627a3fd239811a580fc86fd00a4a321c4/docs/examples/ensemble_model_repository/image_preprocess_nchw_3x224x224_inception/config.pbtxt#L34) input. Which datatype should I use in the HTTP request? I.e. how do I know which datatype to use when the model datatype indicates `TYPE_STRING`? Looking at the backend implementation, it seems to directly process bytes ([GetInputTensor](https://github.com/triton-inference-server/server/blob/c22cb51ae3aa4a129203ae597a63d9d9f32bcd65/src/custom/image_preprocess/image_preprocess.cc#L188-L189)). So the only way I found to make it work is to use `BYTES` datatype in the request with the request body encoded in binary with the [Triton extension for binary data](https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_binary_data.md). In this case, it seems I need to look at the backend implementation to know which datatype to use in the HTTP request. The datatype in the model configuration doesn't seem to help. Is that expected? Or is there a link I'm missing?

**Comment by deadeyegoodwin** [comment]
Your request needs to use the datatypes expected by the model. If you use the binary data extension you do send the data as binary (instead of as part of the json), but you are still sending a specific datatype and so that must be reflected in the datatype you specify in the request.

TYPE_STRING in the model configuration corresponds to BYTES in the protocol. The element type is more accurately called "bytes" because it represents a variable length blob of bytes, and it doesn't necessarily have to be a string. All the other datatypes match as you would expect, for example INT64 == TYPE_INT64.

It sounds like you may be trying to create your own HTTP requests instead of using the client libraries. You may find it helpful to write some simple python clients using the HTTP client library and turn on verbose mode and then you  will see the http requests as generated by the library. That can help you understand the protocol if the documents are not clear enough.
