### ISSUE TITLE
Issues with CentOS client build

### ISSUE THREAD

**Issue by kpedro88** [triton-inference-server/server#2082]
**Description**

`docker build -f Dockerfile.centos_client .` does not run to completion.

**Triton Information**
What version of Triton are you using? Latest 2.3.0

Are you using the Triton container or did you build it yourself? Trying to build client myself

**To Reproduce**

`docker build -f Dockerfile.centos_client .`

Observed issues:
1. need `python3-devel` rather than `python3` to get `Python.h` etc.
2. need libb64 for https://github.com/triton-inference-server/server/blob/v2.3.0/src/clients/c%2B%2B/perf_client/data_loader.cc#L29; only provided by third-party repos (as far as I can [find](https://pkgs.org/download/libb64-devel)), so e.g.:
    ```
    rpm -Uvh http://www6.atomicorp.com/channels/atomic/centos/7/x86_64/RPMS/atomic-release-1.0-21.el7.art.noarch.rpm && \
    yum install -y libb64-devel
    ```
3. Need to add `-DCMAKE_INSTALL_LIBDIR:STRING=lib` to https://github.com/triton-inference-server/server/blob/v2.3.0/build/CMakeLists.txt#L142 or it installs to `lib64` and https://github.com/triton-inference-server/server/blob/v2.3.0/src/clients/c%2B%2B/library/CMakeLists.txt#L150 can't find it.

I could make a PR with these fixes, but even after all of that, I end up with:
```
[ 75%] Performing configure step for 'grpc'
cd /workspace/builddir/grpc/src/grpc-build && /usr/bin/cmake3 "-GUnix Makefiles" -C/workspace/builddir/grpc/tmp/grpc-cache-Release.cmake /workspace/builddir/g
rpc-repo/src/grpc
loading initial cache file /workspace/builddir/grpc/tmp/grpc-cache-Release.cmake
Re-run cmake no build system arguments
...
CMake Error at cmake/protobuf.cmake:55 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)
```
which just seems strange, because `protobuf-config.cmake` is definitely there.

Is this supposed to work out of the box? Is it automatically tested?

**Expected behavior**

Build succeeds.

**Comment by deadeyegoodwin** [comment]
Triton does not officially support Centos/RHEL, so it is not tested, which is why that dockerfile doesn't work. The Dockerfile was a contribution and so it should not be placed so prominently which gives the impression that it is fully supported. We will remove it. We have had requests to officially support RHEL but currently we don't.

You may have noticed that we are working on breaking the monolithic triton repo into smaller repos. Part of that transition will move the clients to their own repos with their own, simplier CMake builds which may make it easier to port to other OSes. We hope to have that transition completed before the end of the year.
