### ISSUE TITLE
CUDA Shared Memory for pytorch cuda tensor?

### ISSUE THREAD

**Issue by LightToYang** [triton-inference-server/server#2221]
I get pytorch tensor in cuda with VPF, can I share it directly to trition inference server with triton client ?

**Comment by tanmayv25** [comment]
Yes. as far as you can specify the cudaIPC handle and byte size to the triton client.
Concretely, if the tensor is in cuda shared memory, then you can use the following to register the memory region with triton server:
1. Using gRPC: https://github.com/triton-inference-server/server/blob/master/src/clients/python/library/tritonclient/grpc/__init__.py#L858
2. Using HTTP: https://github.com/triton-inference-server/server/blob/master/src/clients/python/library/tritonclient/http/__init__.py#L898

And then follow the example here:
1. Using gRPC: https://github.com/triton-inference-server/server/blob/master/src/clients/python/examples/simple_grpc_cudashm_client.py
2. Using HTTP: https://github.com/triton-inference-server/server/blob/master/src/clients/python/examples/simple_http_cudashm_client.py

Note: Unlike in our examples where we create the cuda shared memory region using `cudashm.create_shared_memory_region` and pass its cudaIPC handle, you must pass the cudaIPC handle of the pytorch  tensor.

Re-open if you have any other question or face any issues :)

**Comment by ald2004** [comment]
@tanmayv25 as my understanding i can reuse the same handler which assign to triton-server,
and use the same cuda memory address to infer, after one infer what needed to be done is reset 
cuda handler base_addr_ to new frame's cuda address or should i assign triton-server a new handler through 
http request(which maybe overhead for http or gRPC). 

i have 400 cameras, 25FPS per camera, reuse is important.
thank you.

**Comment by tanmayv25** [comment]
@ald2004  Yrs.. A handler is just the specifier for a cuda shared memory region. You can over-write the data of previous request in the underlying memory and issue a new request. Note that If using asynchronous inference API then you should wait for the server to run inference and return the results.

**Comment by ald2004** [comment]
@tanmayv25 
sorry for this problem,please help me confirm my solution is correct or not, thank you .
1. Use tritron_client (shm_ip0_handle = cudashm.create_shared_memory_region) function create a shm region.
2. Use python vpf decode a rtsp frame and get (surfPlane.GpuMem())
3. Write a python extension like flowing argument ptr_vpf is (surfPlane.GpuMem()) which is a unsigned long long :
```python
   int CudaSharedMemoryRegionSet_from_decoder(void* cuda_shm_handle, void* ptr_vpf,size_t offset, size_t byte_size) {
        // remember previous device and set to new device
        int previous_device;
        cudaGetDevice(&previous_device);
        cudaError_t err = cudaSetDevice(
            reinterpret_cast<SharedMemoryHandle*>(cuda_shm_handle)->device_id_);
        if (err != cudaSuccess) {
            cudaSetDevice(previous_device);
            return -1;
        }

        // Copy data into cuda shared memory
        void* base_addr = reinterpret_cast<SharedMemoryHandle*>(cuda_shm_handle)->base_addr_;
        auto res = cudaMemcpy(reinterpret_cast<uint8_t*>(base_addr) + offset, ptr_vpf, byte_size, cudaMemcpyDeviceToDevice);
        if (err != cudaSuccess) {
            cudaSetDevice(previous_device);
            return -3;
        }

        // Set device to previous GPU
        cudaSetDevice(previous_device);

        return 0;
    }
```
question is that surfPlane.GpuMem() is unsigned long long value pass to this function the data can not be copied to triton server created shared cuda memory region.

thank you for helping.

**Comment by ald2004** [comment]
@tanmayv25  finally got the problem solved: 
forget add .contiguous() ,the python extension CudaSharedMemoryRegionSet_from_decoder worked.
```python
surface_tensor=torch.as_tensor(input0_data,dtype=torch.float32,device="cuda:0").contiguous()
```
and 
```python
input_byte_size = surface_tensor.element_size() * surface_tensor.nelement() 
```
get the total gpu size in bytes.

**Comment by ald2004** [comment]
@tanmayv25 sorry for this problem again.
cuda_shm_handle->base_addr is it a unified memory address for all gpus in one server machine?
according to pull #824, in my understanding this cuda_shm_handle->base_addr address is unified address, that means the data copied to this address can be read from all gpus at infer time.(may be implement by auto peer to peer copy). 
so when create a cuda shared memory handler, every frame decoded by different gpus what needed to be done is copy it to handler->base address , then request triton server for infer , triton server will 
schedule the infer request to another gpu and that infer gpu can get the data by cuda_shm_handle->base_addr whatever the data is allocate on which gpu, because this is unified address.
am i correct ? my develop machine have only gpu so i can not confirm right now.
thank you again.

**Comment by tanmayv25** [comment]
You might be interested in [cudaMallocManaged ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gd228014f19cc0975ebe3e0dd2af6dd1b) in cuda toolkit. Use this pointer in your handler if you would like to take benefit from unified memory system.

**Comment by ald2004** [comment]
@tanmayv25 sorry again for my problem 
there is a weird problem, i have 2 images and python code list blew,
if frame_decoded is the first splited image triton server can infer correctly. and when i use the second one triton server 
can not infer the correct box .
i guess the problem is when copy image ndarray into gpu memory for some reason that i did not know may be gpu memory
storage is column premire. 

i guess this model is trained by torch tensor ,and torch tensor is default copy data to gpu memory by planar format,
and now i avoid torch tensor, decode directly copy ndarray into gpu memory which is not correctly read by the model.
so, i made it like the second picture planar can be read correctly by the model ? 
am i right ? thank u for your time , so many times.
Thank you.

the first one :
![image](https://user-images.githubusercontent.com/4443533/109275568-e387a800-784f-11eb-8a07-50289d9eac8c.png)
the second  one :
![image](https://user-images.githubusercontent.com/4443533/109275603-ec787980-784f-11eb-8cf8-e7c55da90eae.png)


```python
input0_data=np.copy(frame_decoded)
input0_data = input0_data.reshape(( c, h, w))
input0_data = np.ascontiguousarray(input0_data / 255., dtype=np.float32)
cudashm.set_shared_memory_region(shm_ip0_handle, [input0_data])  # cpu -> gpu
results = triton_client.infer(model_name=model_name, inputs=inputs, outputs=outputs)
```

**Comment by priya-dwivedi** [comment]
@ald2004 @tanmayv25 - We are trying to do exactly this and running into some issues. Will appreciate any tips from you.

Issue: We are trying to copy torch tensor to in the Cuda set_shared_memory_region function:

```
def set_shared_memory_region_2(cuda_shm_handle, input_values):
    """Copy the contents of the torch array into a shared memory region with
    the specified identifier, offset and size.

    Parameters
    ----------
    cuda_shm_handle : c_void_p
        The handle for the cuda shared memory region.
    input_values : list
        The list of torch arrays to be copied into the shared memory region.

    Raises
    ------
    CudaSharedMemoryException
        If unable to set values in the cuda shared memory region.
    """
    if not isinstance(input_values, (list, tuple)):
        _raise_error("input_values must be specified as a Torch array")
    for input_value in input_values:
        if not torch.is_tensor(input_value):
            _raise_error(
                "input_values must be specified as a list/tuple of Torch arrays"
            )
    
    offset_current = 0
    #byte_size = mem_handle[1]
    for input_value in input_values:
        input_value =  input_value.contiguous().flatten()

        byte_size = input_value.element_size() * input_value.nelement()
        _raise_if_error(
            c_int(_ccudashm_shared_memory_region_set_2(cuda_shm_handle, c_uint64(offset_current), \
                c_uint64(byte_size), input_value.data_ptr())))
    
        offset_current += byte_size
    
    return
```

The main issue we are running into is how to pass the pointer of the torch tensor to the C++ function _ccudashm_shared_memory_region_set_2. We have used  .data_ptr() to get the pointer location but that gives an error in the cudaMemcpyDeviceToDevice().
