### ISSUE TITLE
Protobuf version conflicts r19.10

### ISSUE THREAD

**Issue by 1048215790** [triton-inference-server/server#2243]
When I compile with cmake, but the server requires the protoc version to be 3.6.1, tensorflow 1.14 requires the protoc version to be 3.7，how do I choose?

**Comment by deadeyegoodwin** [comment]
How are you compiling TF 1.14 for use in Triton? You cannot just drop TF-compiled libraries into Triton... they will not work correctly. Due to protoc / tensorflow issues (https://github.com/tensorflow/tensorflow/issues/24976#issuecomment-576515214) it is very difficult to use TF libraries with other protoc code. There are also API deficiencies in TF that require us to patch TF for Triton. This is why the build instructions specifically say to use the NGC TF container if you need to build yourself. But in general you should be aware that it will be a significant task to take any arbitrary version of TF and get it working with triton.

**Comment by 1048215790** [comment]
> 
> 
> How are you compiling TF 1.14 for use in Triton? You cannot just drop TF-compiled libraries into Triton... they will not work correctly. Due to protoc / tensorflow issues ([tensorflow/tensorflow#24976 (comment)](https://github.com/tensorflow/tensorflow/issues/24976#issuecomment-576515214)) it is very difficult to use TF libraries with other protoc code. There are also API deficiencies in TF that require us to patch TF for Triton. This is why the build instructions specifically say to use the NGC TF container if you need to build yourself. But in general you should be aware that it will be a significant task to take any arbitrary version of TF and get it working with triton.

Thank you for your answer，i'll try
