### ISSUE TITLE
HTTPService is starting instead of started

### ISSUE THREAD

**Issue by chiyukunpeng** [triton-inference-server/server#2312]
I want to deploy `yolov5` with `triton-20.03`. 
`GRPCService` is started but `HTTPService` is starting instead of started.

**error**
I1204 08:17:45.082233 1 grpc_server.cc:1939] Started GRPCService at 0.0.0.0:8001
I1204 08:17:45.082251 1 http_server.cc:1411] Starting HTTPService at 0.0.0.0:8000
I1204 08:17:45.124574 1 http_server.cc:1426] Starting Metrics Service at 0.0.0.0:8002
I1204 08:17:45.130062 1 server.cc:224] Polling model repository
I1204 08:18:00.130377 1 server.cc:224] Polling model repository

(py38torch16) cp@ubuntu:~/project/yolov5/client$ curl -v 0.0.0.0:8000/v2/health/ready
*   Trying 0.0.0.0:8000...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 8000 (#0)
> GET /v2/health/ready HTTP/1.1
> Host: 0.0.0.0:8000
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Length: 0
< Content-Type: text/plain
< 
* Connection #0 to host 0.0.0.0 left intact

(py38torch16) cp@ubuntu:~/project/yolov5/client$ curl -v 0.0.0.0:8000/v2/health/live
*   Trying 0.0.0.0:8000...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 8000 (#0)
> GET /v2/health/live HTTP/1.1
> Host: 0.0.0.0:8000
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Length: 0
< Content-Type: text/plain
< 
* Connection #0 to host 0.0.0.0 left intact

**Comment by deadeyegoodwin** [comment]
The HTTP service is started ("starting" is just incorrect wording that is fixed in more recent versions of Triton).
The reason your HTTP requests are failing is because you are using V2 endpoints (v2/health/live) but 20.03 is older and so only supports V1. You either need to look at the 20.03 documentation (https://docs.nvidia.com/deeplearning/triton-inference-server/archives/triton_inference_server_1120/triton-inference-server-guide/docs/index.html)... or better yet use a recent version of triton where the V2 endpoints are supported.
