### ISSUE TITLE
L4T images for Triton

### ISSUE THREAD

**Issue by turowicz** [triton-inference-server/server#2361]
Any chance of getting official L4T images in the Nvidia's docker registry?

**Comment by CoderHam** [comment]
We do not have decided timeline for the official Jetson docker images but you can create the same for your consumption using the Jetson tar file we share with our monthly releases.

**Comment by turowicz** [comment]
@CoderHam that's what I'm currently doing but of course it would be nice to get something official. Most likely it would be more optimised for production.

**Comment by turowicz** [comment]
@eshcheglov https://github.com/Surveily/Images/blob/master/src/surveily.developer.triton.l4t.dockerfile

**Comment by eshcheglov** [comment]
@turowicz Hey there! It seems that official nVidia inaction has led to the creation of a wonderful community around! Thank you!


P.S in the new versions of Triton (at least in 2.35.0), the inside directory format of the archive has changed. A root directory named `tritonserver` has appeared. So, change the `WORKDIR` from `/opt/tritonserver` to `/opt` if you want to use newer versions, otherwise, the final file structure will look like `/opt/tritonserver/tritonserver`
