### ISSUE TITLE
How to optimize config: instance_group vs. dynamic_batching

### ISSUE THREAD

**Issue by flyingmrwang** [triton-inference-server/server#2399]
It is said that both instance_group and dynamic_batching can improve service performance. 
To maximize the throughput, I try to use large number of instance_group and keep dynamic_batching on w/o preferred batch size. 
While I noticed that the throughput is quite low. And the averaged batch size calculated with metric is like 1.2, which means dynamic_batching is suppressed by multi instance. 
Further, when use single instance, the overall throughput is like 30% higher than previous test. Although gpu memory usage is much lower. 
So I feels confused about the behavior and cannot find a rule to optimize my model. 
Any suggestion will be appreciated.

**Comment by deadeyegoodwin** [comment]
Make sure to read the optimization section carefully, including this section: https://github.com/triton-inference-server/server/blob/master/docs/client_libraries.md

Multiple instances will typically help as described, but not always. And large numbers of instances are often not beneficial because the GPU is already saturated and having a large number of instances just add more management overhead. Also, some frameworks handle multiple instances better than others. TensorRT is very good with multiple instances, TF and ONNXRuntime less so, and PyT not at all (https://github.com/pytorch/pytorch/issues/27902).

The optimization docs outline the best approach. 1) enable dynamic batching is possible for your model, 2) try a small number of instances (1, 2 and 3) and see if it helps for your model.

The Triton project is also working on a "Model Analyzer" tool that will automate some of this for you. So you should keep an eye on that project: https://github.com/triton-inference-server/model_analyzer

**Comment by flyingmrwang** [comment]
@deadeyegoodwin Thanks for your kind explanation about why small number of instances can be the best choice. That really make sense and help me understand the phenomenon that I observed.  
Actually, I have already read the doc and model analyzer tool is exactly what I use to evaluate the throughput. And from my test for current model and platform (nvidia t4 gpu), instance number of 1 is always the best. Maybe tensorrt accelerator is the only way to further improve onnx model. Just tested before and it seems like this option is not quite stable in previous version. I'll try give it a try in latest version and report what I find. Thanks again :-)
