### ISSUE TITLE
How to specify the memory type of an output and collect the output to a response?

### ISSUE THREAD

**Issue by gpudavid** [triton-inference-server/server#2490]
I didn't find a proper place in model config to specify the property.

https://github.com/triton-inference-server/server/blob/d00333245400fb0aad844b15e017ab1e15a37dbd/src/core/model_config.proto#L351

Here in a example, the backend can retrieve the output memory type, so the information has to be specified some where.
https://github.com/triton-inference-server/square_backend/blob/289b9caba9c429c8d2adf1b1a40202a21f843bda/src/square.cc#L402-L407

And here is an example of how collector collect the outputs. Where to specify the source memory type and where the destination type? In this line, it is specified as GPU (considering the case pytorch running in GPU), so I suppose the parameter here is specifying the source memory type, which trigger the question above, where and when the output destination type is specified?

https://github.com/triton-inference-server/pytorch_backend/blob/05a7402aaf956a0e588dba513b1affeef9c6f620/src/libtorch.cc#L917-L922

**Comment by gpudavid** [comment]
I have get the output data forwarded to Triton client through CPU side.

I would make this question more clear as, if the output of a model is at GPU, can Triton deliver the data to client directly trough GPU? 
If it is a no, then the answer of above question would be there is no where and no need to specify the the output memory type.
If it is a yes, then we may have to specify the output memory type and receive and deliver the client data through CPU/GPU.

**Comment by GuanLuo** [comment]
Here is the declaration of [TRITONBACKEND_OutputBuffer](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonbackend.h#L239-L260), you can see that the memory type and memory id serves as preferred value when being read as input, you can set them to specify a GPU device if that is closer to the model output.

Yes if the client is on the same machine with the server so that they have access to the same GPU memory, you can take a look at  [CUDA shared memory extension](https://github.com/triton-inference-server/server/blob/master/docs/protocol/extension_shared_memory.md#cuda-shared-memory)

**Comment by deadeyegoodwin** [comment]
Closing. Re-open if you have additional questions.
