### ISSUE TITLE
QA：Framework installation is needed or not after the construction of the backend?

### ISSUE THREAD

**Issue by linmuchuiyang** [triton-inference-server/server#2552]
According to the instruction of Triton, we need to install the backend for the corresponding framework, for examples, PyTorch, TensorFlow, etc. 
If we setup the backend of the framework, do we still need to install the related framework? And if/if not, how could we control the requirement of the minor version of the corresponding framework and whether it will influence the function and the performance of the Inference Server?

**Comment by tanmayv25** [comment]
The backend build scripts (except TensorRT which depends upon the host installation of the compiler library) includes all the required framework libraries in the installation. Look at https://github.com/triton-inference-server/backend#backend-shared-library

The specific backend repo(for example, [tensorflow-backend](https://github.com/triton-inference-server/tensorflow_backend#build-the-tensorflow-backend-with-custom-tensorflow)) will provide the needed documentation for the custom builds. However, note that the build success is not guaranteed because we only check the build against specific release versions.
