### ISSUE TITLE
No rule to make target "client"

### ISSUE THREAD

**Issue by kjdrew** [triton-inference-server/server#2576]
**Description**
Attempting to build branch r20.02 client libraries with cmake fails with the error:

`make: *** No rule to make target 'client'.  Stop.`

Checking out r21.02 works as expected, but not this version. 

**Triton Information**
r20.02

Are you using the Triton container or did you build it yourself?
Using a Centos7 container.

**To Reproduce**
```
$ git clone https://github.com/triton-inference-server/server.git
$ mkdir builddir
$ cd builddir
$ cmake -DCMAKE_BUILD_TYPE=Release ../build
$ make -j8 client
make: *** No rule to make target 'client'.  Stop.
```

**Expected behavior**
Make begins to build the target rule.

**Comment by tanmayv25** [comment]
`r20.02` is ancient. We have made several changes in our build process since then. For instance, the target is `trits-clients` and not `just client`. Please follow the build instructions from the corresponding branch.
https://github.com/triton-inference-server/server/blob/r20.02/docs/client.rst#ubuntu-1604--ubuntu-1804
