### ISSUE TITLE
How triton determine when to remove an idle instance?

### ISSUE THREAD

**Issue by sijin-dm** [triton-inference-server/server#2659]
We notice that the gpu memory will not be automatically released after the model is not used for a long time. It seems that when a new request for another model is received, it will unload the idle model instance and load the new model. So how triton determine when to remove an idle instance?

**Comment by deadeyegoodwin** [comment]
Triton does not automatically load or unload models. Model loading/unloading only happens when the server starts or when the model control API is used: https://github.com/triton-inference-server/server/blob/master/docs/model_management.md

Different frameworks use GPU memory differently. Some allocate all GPU memory when the model is loaded. Some allocate some memory at load time and then alloc/free additional memory for each inference request.
