### ISSUE TITLE
Call other backends within python backend

### ISSUE THREAD

**Issue by vignesh34v** [triton-inference-server/server#2689]
I am trying to implement end to end model in the triton server. For preprocessing and postprocessing, python backend is used. I would like to call onnxruntime backend model directly from python backend. Currently using tritonclient API to infer from onnx model within python backend. As expected, performance dropped. Is there any efficient way to achieve the same?

Tried ensembling models, but a lot of data needs to transmit from preprocessing model to postprocessing model. And it is complex.

**Comment by Tabrizian** [comment]
How are you calling other backends from the python backend? Do you mean you have installed ONNX dependencies and performing inference on an ONNX model inside python backend? We are working on some performance improvement for the python backend and it should hopefully help your situation.

**Comment by vignesh34v** [comment]
onnx model runs in triton inference server using onnxruntime backend. 
Installed [python tritonclient library](https://github.com/triton-inference-server/server/blob/master/docs/client_libraries.md). Used this library to call onnxruntime_backend model within python backend model.

**Comment by GuanLuo** [comment]
Can you elaborate on why you can't do so in ensemble? Is the ensemble not expressive enough for you to describe your pipeline? For ensemble, the data movement is minimal because setting the input of one model from the output of the other model is done by moving pointers around.

**Comment by vignesh34v** [comment]
In my case, I am working with a language model. It is a kind of sequential model where intermediate results are scored and again fed into the language model till threshold. 

If possible, Can I access those shared memories within the python backend?

**Comment by GuanLuo** [comment]
So your pipeline will be iteratively invoking the models (like "preprocess model -> onnx model -> postprocess model -> (repeat) -> preprocess model -> ...")? In such case, as you mentioned that the last model must issue a next request to the first model, and you should take a look at the [Triton C APIs](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonserver.h) which will not have network overhead compared to using the Triton clients.

However, you will need to experiment to see if the Triton C APIs can be called properly from within Python. And if performance is actually important, you should port your pre / post-processing code from Python (to your own custom backend) because the interaction between Python backend and Triton has additional overhead.

Besides that, I will still suggest you to use ensemble to group "preprocess model -> onnx model -> postprocess model" together.  I am wondering how do you enforce the pipeline without using ensemble?

**Comment by vignesh34v** [comment]
Thanks, I will look into Triton C API. Definitely network overhead is one of my concerns.

Do you suggest ensemble model -> (repeat) -> ensemble model ? How can achieve it ?

**Comment by GuanLuo** [comment]
Currently the (repeat) part must be done by your backend / model by calling either the Triton C API or the client (like what you are doing earlier) to request the ensemble to perform the next inference.

**Comment by vignesh34v** [comment]
Okay. Thanks
