### ISSUE TITLE
Question about custom backends under the 21.x API

### ISSUE THREAD

**Issue by mvpel** [triton-inference-server/server#2711]
**Description**
I'm having some trouble nailing down what changes will need to be made to a custom backend "elementwise" (which does an elementwise sum, product, or average of up to 8 input tensors to a single output tensor), which I adapted from the old addsub.cu example, in order to get it to work under the 21.x API. The new "identity" backend is substantially different from addsub, so I'm not sure what's relevant to the port. I'm also having some trouble figuring out how to compile the .so file.

I made all the changes based on the latest version of addsub.cu in the src/test/custom directory in the "server" repository, so I think what I have should compile, but I'm not clear on whether it will work with the 21.x release, and some proxy problems block the libFuzzer clone when I try to build, I see there's now a few separate "backend" repositories, so should that be the foundation on which a new 21.x custom module should be constructed? If so, how's it work?

If anyone could point me to more detailed documentation on the procedure to create and build a shared library backend, I'd really appreciate it. My users use the elementwise average as part of one of their inference workflows, and it'd be great to get it up and running on the latest version of Triton.

**Triton Information**
21.03 from the container, modified to use OpenSSL curl instead of GnuTLS due to issues with our firewall proxy's behavior.

**Comment by deadeyegoodwin** [comment]
General information about the new backend API is here: https://github.com/triton-inference-server/backend
With the new API, backends can be build completely independently of the core of triton, which is why they are organized as separate repos. You don't need to have a separate repo for each of your backends, but you should follow the cmake pattern that you find there for your build if you want to have an easy time building.
I agree that we could have a simpler example, but for now the identity backend is the best we have. The ModelInstanceExecute function is where you will make most of your changes and much of the rest you can likely keep. https://github.com/triton-inference-server/identity_backend
Another option is to implement your logic in python. You will give up some performance but recent changes coming out in 21.04 release (next week) make the python backend much more performant. https://github.com/triton-inference-server/python_backend
