### ISSUE TITLE
Question: Performance differences between v1 and v2

### ISSUE THREAD

**Issue by JulianOrteil** [triton-inference-server/server#2807]
Good afternoon.

I just have a simple question for the team here. I'm currently using a v1 build of Triton as my production DL server. I will be upgrading the hardware soon and I am just curious if there is any recorded performance benefit between v1 and v2 of Triton?

If there is, where is the performance boost?

Thanks,
Jules

**Comment by tanmayv25** [comment]
IMO there should be no perf difference within v1 to v2 as far as just API is concerned. The V2 API conforms with more standardized practice for inference servers. However, we made this switch almost a year back. Since then, we have progressed to the newer releases of frameworks and added other enhancements in our backends. Hence, there is a good chance you can find some perf improvement with recent releases of Triton which only support v2.

**Comment by JulianOrteil** [comment]
Very good, thank you for the answer.
