### ISSUE TITLE
when a large amount of data needs to be transferred between ensemble models, it is very time consuming

### ISSUE THREAD

**Issue by zhaohb** [triton-inference-server/server#2959]
**Description**
first model is a pre-processing model, which runs on the CPU and outputs a processed picture. The amount of data is relatively large, and the stress test will find that data transmission will take up a lot of time. And then to the second model, again, it takes a long time, second model runs on gpu.

**Triton Information**
21.02

Are you using the Triton container or did you build it yourself?
yes

**Expected behavior**

Is there a mechanism to reduce data transfer time, since preprocessing is usually easy and fast, data transfer will become a new performance bottleneck.

**Comment by CoderHam** [comment]
@zhaohb can you share numbers on how many data is transferred from CPU to GPU and quantify how long these transfers are taking? You can use the perf_analyzer to get a breakup of the compute times.
cc @GuanLuo

**Comment by zhaohb** [comment]
yes, I have been using perf_analyzer to get the time and the results are as follows: 
If model 1 does not return the perf_analyzer time is approximately 35ms, the difference is that if model 1 returns 3*1000*750 float integers, the perf_nalyzer time is approximately 90ms.

Is there a mechanism to direct feed the output of model 1 directly to model2？

**Comment by GuanLuo** [comment]
The ensemble scheduler avoids data copies between models as many as possible, but you can reason that some data copies are inevitable due to the model encapsulation, for example, the output copy from model managed output buffer, which may be overwritten by future inference, to the buffer managed by the ensemble.

If you want to go further to minimize such data copy, then you will need to bypass the model encapsulation by modifying your models. For example, your preprocessed model will reserve a buffer and return the pointer to the buffer, while the other model will retrieve the data via the pointer and be responsible to release the buffer to avoid memory leak.

By the way, when you use perf_analyzer, the end-to-end latency reported includes the network latency so the time would be much higher than what it actually takes within an ensemble.

**Comment by zhaohb** [comment]
the output copy from model managed output buffer, which may be overwritten by future inference, to the buffer managed by the ensemble.  I can not understand that, can you explain it？
my first model pre_prcess just resize the input image,  and then pass it to the second model, I don't know if this step prevents data copying.

**Comment by GuanLuo** [comment]
In general, when your model produces the output, you will need to request a buffer in the inference response to store the output, copying the output to that buffer is the inevitable data copy that I mentioned.

**Comment by zhaohb** [comment]
so where does avoiding copying data between models generally occur?

**Comment by zhaohb** [comment]
I think we might need a zero-copy solution between ensemble models , support for python backend and tensorrt backend

**Comment by GuanLuo** [comment]
If you want some form of pipelining without using ensemble, you would have the copies from "model A request -> model A -> model A response -> model B request -> model B -> model B response". With ensemble you have "ensemble request -> model A -> model A response (model B request) -> model B -> ensemble response"

If you want a zero-copy solution, you may implement your custom backend that performs "preprocessing + inference". And in the custom backend you can tightly couple the transition from model to model.

**Comment by zhaohb** [comment]
ok, thank you very much, maybe there is no way to avoid copying happened, but ensemble had reduce unnecessary copy.
