### ISSUE TITLE
How to rename input name of torchscript model?

### ISSUE THREAD

**Issue by CPFelix** [triton-inference-server/server#3307]
**Is your feature request related to a problem? Please describe.**
I use export.py to export torchscript model of yolov5s,but found its input name is 'x' and output name '435',and it can't be load by Triton that  require "name_index" fromat.

**Describe the solution you'd like**
Triton can allow input name like 'x' for TorchScript model or how can I modify torchscript model input name?

**Describe alternatives you've considered**
None.

**Additional context**
None.
@dyastremsky @jbkyang-nvi @CoderHam Sorry to disturb!

**Comment by dyastremsky** [comment]
The current backend logic is dependent on the current format, with the explanation [here.](https://github.com/bytedance/triton-inference-server/blob/master/docs/model_configuration.md)

I'd imagine that the index is important for knowing the order of the inputs. Your best bet is to create a custom backend for your needs or modify the script you are using to follow the expected format. That would be outside the scope of Triton.

**Comment by CoderHam** [comment]
@CPFelix The names of the inputs/outputs in the TorchScript model are inconsequential. If you follow the naming convention @dyastremsky pointed to you can load any model where the inputs are `name__index` without worrying what the respective name for that input is. 

This is done because TorchScript does not always capture the names (and dtypes) of the i/o as model metadata.
