### ISSUE TITLE
2 or more models running in parallel

### ISSUE THREAD

**Issue by audrey-siqueira** [triton-inference-server/server#3369]
Hi, which is the best way to run in parallel 2 or more models that are already loaded?

Is there any command like this for example?

python image_client.py -m  **MODEL_1**   **MODEL_2**   -c 1 -s INCEPTION images

**Comment by CoderHam** [comment]
You need to make 2 independent requests to the server. If you wish to use the example image client as is, you could run two instances of it but I would recommend writing a custom client that makes the requests to the N models. Triton supports async infer requests so that would be useful to use here.

**Comment by audrey-siqueira** [comment]
Independent requests turned my pipeline very slow. 

Where can I find documentation to work with asynchronous inferences?

 Would you recommend to use the 2 models in ensemble mode?
