### ISSUE TITLE
tritonclient.utils.shared_memory not available on Jetson tritonclient[all]=2.8.0

### ISSUE THREAD

**Issue by philipp-schmidt** [triton-inference-server/server#3372]
**Description**
Can not import shared memory libs in tritonclient 2.8.0 on Jetson.

**Triton Information**
`pip3 install tritonclient[all]=2.8.0`
On Jetson Xavier AGX.

**To Reproduce**
```
pip3 install tritonclient[all]=2.8.0
export OPENBLAS_CORETYPE=ARMV8
python3

import tritonclient.grpc as grpcclient
import tritonclient.utils.shared_memory as shm
--> ModuleNotFoundError: No module named 'tritonclient.utils.shared_memory'
```

The env export is necessary or I get Illegal Instruction, see [this](https://stackoverflow.com/questions/65631801/illegal-instructioncore-dumped-error-on-jetson-nano), but I don't think it's related to the issue.

**Comment by philipp-schmidt** [comment]
Jetson release for 2.8.0 states that shared memory is supported. Is this only for server and not for client?

**Comment by CoderHam** [comment]
You are likely using the pip wheel for x86. The Jetson python wheel is available inside the Jetson tar file shared in our release notes. Can you use that wheel instead?

**Comment by philipp-schmidt** [comment]
Yes, sure we can install via tarball.  I'm confused though, what's the difference with installing via pip? Everything apart from shared memory seems to work just fine on Jetson with pip install. Does wheel not build shm support?
Same docker build instructions for dGPU server and jetson deployments would be nice and pip3 install is very convenient.
It's only "cosmetic", so don't bother too much.

**Comment by philipp-schmidt** [comment]
I think I have to look up how pip handles cross-platform, this is kinda confusing me right now.

**Comment by philipp-schmidt** [comment]
So the package `tritonclient-2.8.0-py3-none-any.whl` with "-any" ending should work for aarch64 / arm64 but does not ship with shared memory in that case, is that right?

**Comment by CoderHam** [comment]
To clarify the tar file (https://github.com/triton-inference-server/server/releases/download/v2.13.0/tritonserver2.13.0-jetpack4.6.tgz) I mentioned is not the wheel itself but contains the wheel along with the sever and client libraries + executables.

The release note specifically mention the install instructions for jetson as below:

```
pip install --upgrade clients/python/tritonclient-2.13.0-py3-none-linux_aarch64.whl[all]
```

> So the package tritonclient-2.8.0-py3-none-any.whl with "-any" ending should work for aarch64 / arm64 but does not ship with shared memory in that case, is that right?

Thats right. My understanding of the pip packaging is that the `-none-any.whl` is built for all platforms and hence does not support shared memory since system shared memory is not supported on all platforms. 
Additionally the jetson wheel is `-none-linux_aarch64.whl` does contain system shared memory support but does not support cuda shared memory since it is not supported on all platforms.

One important thing you pointed out was that the aarch64 wheel is not available via pypi. I will propose adding this to the team.

**Comment by philipp-schmidt** [comment]
Yes, makes perfect sense. Thanks for the clarification.

Issue considered closed on my end.

**Comment by philipp-schmidt** [comment]
Just curious: have you decided whether the aarch64 wheel for tritonclient will be available via pypi soon?
