### ISSUE TITLE
[Questions] Why is the queue time high?

### ISSUE THREAD

**Issue by shipengAlan** [triton-inference-server/server#3416]
I encountered a puzzle and I don't get the reason. Maybe it is a basic problem.

Suppose we have two client A, B to request the Triton server. They have the same RPS(requests per second), which means the number of requests in one second is same.

BUT, they have different concurrency. A's concurrency is 20 but B's is only 4.

The client A's Triton queue time is much longer than the B's queue time. 10s vs 400ms. 
Do you know what the reason is ?
Thanks so much.

**Comment by CoderHam** [comment]
@shipengAlan the queue time is larger because you are sending more requests when you increase the concurrency. Triton is unable to run the inferences at the rate at which they are coming in and hence you see a larger queue time. (If your GPU is not being saturated maybe increase the number of model instances?)
This is to be expected for higher concurrencies. The queue time will also continue to increase over time if you are sending async requests since the length of the queue will keep increasing.
