### ISSUE TITLE
will ensemble model pass the GPU pointer to next model?

### ISSUE THREAD

**Issue by royinx** [triton-inference-server/server#3441]
I have an TensorRT model X  in Triton IS, and a preprocess for image resize and normalisation.

I want to achieve highest performance, I am thinking to minimise the data copying cost through PCIE.

As I remember there are a CUDA_backend mentioned in TRTIS docs in 2018-2019, which can deploy custom CUDA script. I saw it in ensemble model and NLP example at that moment.
seems the docs have been removed already, is CUDA_backend deprecated?

I'm thinking about the following options.
- DALI (decode image with mixed nvJPEG, normalize with GPU) 
- CUDA custom backend (if available)
- python backend (using pycuda to perform preprocess and ruturn dst_device)
- baseline: python backend ( CPU to run all process )

will these method / which one will pass the GPU pointer to model X directly ?
and which of the method can minimise the copy operation between device and host for the preprocessing model?

also for pycuda part, will the memory address conflict will other models

**Comment by royinx** [comment]
@tanmayv25  As I rmb, thats the ensemble method in 2019, while DALI and python backend hvnt released yet. 

I have created a DALI model for pre/post-process.
I wanna measure the kernel time like Nsight, how can I profile the DALI / TRITON model with NSight or any profiling tool?

**Comment by tanmayv25** [comment]
1. Launch triton via nsys cli like below:
`nsys profile -t cuda,nvtx  --output run1 tritonserver ...`

2. Run your workload of inferences.
3. SIGINT tritonserver. It will create a qdrep file.
4. Open it in NSight systems to view and analyze it.

We have some additional nvtx markers included in our sources for profiling ease. However, they are not enabled by default. In order to enable these additional nvtx marker you need to rebuild triton. You can use the build.py with [this ](https://github.com/triton-inference-server/server/blob/main/build.py#L1577) option enabled.

**Comment by Tabrizian** [comment]
Closing the issue due to in-activity.

**Comment by tanmayv25** [comment]
@caoshuaibingcao  Can you create a new github issue describing what problem are you running into while trying to use nsight profiling.
