### ISSUE TITLE
Can the ensembled model implement branching logic?

### ISSUE THREAD

**Issue by grapefruitL** [triton-inference-server/server#3483]
**Is your feature request related to a problem? Please describe.**
Enter a picture, use model A to detect people and vehicles, use model B to classify everyone by gender, and use model C to classify all vehicles by colors

**Describe the solution you'd like**
The above logic can be implemented using such a [configuration](https://github.com/triton-inference-server/dali_backend/blob/main/docs/examples/inception_ensemble/model_repository/ensemble_dali_inception/config.pbtxt) file

**Describe alternatives you've considered**
Is there any method that can combine custom logic into a model?

**Additional context**
What is the most efficient way to achieve the above process by using triton so far？

**Comment by grapefruitL** [comment]
@Tabrizian thx very much!
another 2 questions：
1. as https://github.com/triton-inference-server/python_backend#using-custom-python-execution-environments said, where can I check the modules already included in the Triton container？ use 'pip3.8 list' command?
2. can I just use "pip install" to install the package that the custom python backend need?

**Comment by wiekern** [comment]
Hi, is it possible to ensemble two models (detection + classification), in which the shape of detection output is not matched with the shape of classification input, since the detection model outputs dense bboxes and I need to filter some out by NMS. Actually I expect the classification model accepts arbitrary input shape and I will do the preprocess before sending infer request to classifcation model. 
The detection output: shape (1, 25500, 6)
some data process needs to be inbetween
The classification input: shape (3, 224, 224)

**Comment by wiekern** [comment]
Hi, I found a solution for my sequentially ensemble models. 
Put your models separately in model repos, structures like below
```
model_repos/
        detection_model/
                    1/model.onnx
                     config.pbtxt
        classification_model/
                    1/model.onnx
                     config.pbtxt
```
And the infer logic: input_img ->preprocess -> **detection_model** -> detection_output -> postprocess1 -> **classification_model** -> cls_output -> postprocess2 -> final_output
in order to infer an image, you need to write code sending an inferring request and you will get a response, in my case, I am using Python, so the pesudo code is
```
img = read_image(input_img)
detection_input_img = preprocess(img)
detection_response = InferReuqestToDetectionModel(detection_input_img)
classification_input_img = postprocess1(detection_response)
classification_response = InferRequestToClassificationModel(classifictation_input_img)
final_output = postprocess2(classification_reponse)
```

It fulfills my needs and works well.

**Comment by sprint2200** [comment]
> Hi, I found a solution for my sequentially ensemble models. Put your models separately in model repos, structures like below
> 
> ```
> model_repos/
>         detection_model/
>                     1/model.onnx
>                      config.pbtxt
>         classification_model/
>                     1/model.onnx
>                      config.pbtxt
> ```
> 
> And the infer logic: input_img ->preprocess -> **detection_model** -> detection_output -> postprocess1 -> **classification_model** -> cls_output -> postprocess2 -> final_output in order to infer an image, you need to write code sending an inferring request and you will get a response, in my case, I am using Python, so the pesudo code is
> 
> ```
> img = read_image(input_img)
> detection_input_img = preprocess(img)
> detection_response = InferReuqestToDetectionModel(detection_input_img)
> classification_input_img = postprocess1(detection_response)
> classification_response = InferRequestToClassificationModel(classifictation_input_img)
> final_output = postprocess2(classification_reponse)
> ```
> 
> It fulfills my needs and works well.

thx. it help me to slove big problem

**Comment by grapefruitL** [comment]
@Tabrizian thanks! 21.10 worked! I have more questions beblow:
1. I use cuda shared memory in the request input, can python backend receive and work with it ? is there any example ?
2. If the answer of question 1 is yes, which following 2 ways is faster? 
way 1: set cuda shared memory --> send request to model1 --> get output from shared memory --> put output into the new shared memory --> send request to model2 --> get final result
way2: set cuda shared memory --> send request to python backend model which will  do the work of way 1 --> get final output from the python backend model
3. how does python backend send inference request to other models ? also the http or grpc way?

**Comment by Tabrizian** [comment]
@grapefruitL Sorry about the delay.

1. Yes, you can use any protocol in the client side and Python backend should work with it.
2. I think you are referring to using BLS. I think way 2 (or using ensemble) should be faster because the network overhead of registering and unregistering shared memory regions is removed.
3. Python backend uses [Triton C API ](https://github.com/triton-inference-server/server/blob/main/docs/inference_protocols.md#c-api) to send requests to other models. It is faster than HTTP or GRPC since it doesn't have the network overhead.

Closing this issue. Feel free to re-open the issue if you have follow up questions.
