### ISSUE TITLE
triton-client no matches found from pip install ?

### ISSUE THREAD

**Issue by Stephenfang51** [triton-inference-server/server#3544]
```
pip install tritonclient[all]

>>> no matches found: tritonclient[all]
```
even nvidia-pyindex 1.0.8 was installed 
PS. pip version pip 21.3.1

**Comment by dzier** [comment]
You may need to uninstall nvidia-pyindex. The triton client can be installed directly from PyPI now. I have confirmed the following works...

From a fresh ubuntu docker container:
```
$ docker run -it --rm ubuntu:20.04
```

Inside docker container:
```
# apt-get update && apt-get install -y --no-install-recommends python3 python3-pip
# pip install tritonclient[all]
```

Everything was found and installed correctly.  Please re-open the issue if it persists.

**Comment by Stephenfang51** [comment]
> You may need to uninstall nvidia-pyindex. The triton client can be installed directly from PyPI now. I have confirmed the following works...
> 
> From a fresh ubuntu docker container:
> 
> ```
> $ docker run -it --rm ubuntu:20.04
> ```
> 
> Inside docker container:
> 
> ```
> # apt-get update && apt-get install -y --no-install-recommends python3 python3-pip
> # pip install tritonclient[all]
> ```
> 
> Everything was found and installed correctly. Please re-open the issue if it persists.

Well what if I want to install tritonclient in my host ?
My host OS is ubuntu 18.04

**Comment by dzier** [comment]
I was able to find and install with:
```
# pip3 install tritonclient[all]
```
However the installation will fail. We only officially support Ubuntu 20.04 and windows. You can try to follow the instructions here to download and install directly from source: https://github.com/triton-inference-server/client/tree/r21.11#download-from-github

**Comment by leemengwei** [comment]
@dzier  Hi, I'm installling tritonclient by pip on Jetson Jetpack4.6 , python3.6,  throws me:
`nxin@nxin-desktop:~/lmw/triton_pack/arm/triton_model_stuff/saved_files$ pip install tritonclient[all]
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/, https://pypi.ngc.nvidia.com
WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
Collecting tritonclient[all]
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.13.0-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 2.4 MB/s            
WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.12.0-py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 9.4 MB/s             
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.11.0-py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 7.8 MB/s             
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.10.0-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 13.3 MB/s            
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.9.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 15.3 MB/s            
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.8.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 14.2 MB/s            
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.7.0-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 15.5 MB/s            
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.6.0-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 16.2 MB/s            
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.5.0-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 15.0 MB/s            
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.4.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 15.3 MB/s            
  Downloading https://developer.download.nvidia.cn/compute/redist/tritonclient/tritonclient-2.3.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 15.4 MB/s            
ERROR: Cannot install tritonclient[all]==2.10.0, tritonclient[all]==2.11.0, tritonclient[all]==2.12.0, tritonclient[all]==2.13.0, tritonclient[all]==2.3.0, tritonclient[all]==2.4.0, tritonclient[all]==2.5.0, tritonclient[all]==2.6.0, tritonclient[all]==2.7.0, tritonclient[all]==2.8.0 and tritonclient[all]==2.9.0 because these package versions have conflicting dependencies.`
