### ISSUE TITLE
Documentation for jetson should be updated for client installation

### ISSUE THREAD

**Issue by fciannel** [triton-inference-server/server#3551]
**Description**
In the documentation for jetson in the release file I see this:

```
python3 -m pip install --upgrade clients/python/tritonclient-2.15.0-py3-none-manylinux2014_aarch64.whl[all]
```

**Triton Information**
Triton on Jetpack 

**Expected behavior**
It should be:
```
python3 -m pip install --upgrade clients/python/tritonclient-2.15.0-py3-none-any.whl[all]
```

**Comment by dzier** [comment]
For versions 2.15.0 and onward, the first instruction is correct. Due to a platform issue on ARM, we had to rename the wheel file.

```
python3 -m pip install --upgrade clients/python/tritonclient-2.15.0-py3-none-manylinux2014_aarch64.whl[all]
```

The `tritonclient-2.15.0-py3-none-any.whl` also exists and works, but it is only a small subset of the client library package. It does not contain support for system/cuda shared memory and perf analyzer. 

Are you experiencing an error when you run the first command? If so, can you reply with the error message?

**Comment by dzier** [comment]
Closing issue for now, please re-open if you are still having issues.
