### ISSUE TITLE
 RPC Client report Unimplemented desc

### ISSUE THREAD

**Issue by GuoGuiRong** [triton-inference-server/server#3554]
**Description**
I have use v21.09 to run my model within CPU, and use go client to request it success. But when I use my GPU prod, because my cuda version match error, I have to use v20.6 to rum my mode within GPU, the model is running ok, But the go client cant't use anymore, model's conf.pbtxt never change, but client failed.? 

**Triton Information**
What version of Triton are you using?
v20.6 

Are you using the Triton container or did you build it yourself?
use docker Triton image,like   xxxv20.6-py

**Expected behavior**
I want to use go client to request my model

**Comment by dzier** [comment]
There was a major change in the Client API between that happened around r20.09 when we moved Triton to version 2.0.0. So any Triton server prior to r20.09, including r20.06, will not work with a client using the newer API. Your options are:
1) Upgrade your GPU and CUDA driver. This is preferred since it appears you are using a driver that is more than 18 months old.
2) Use the clients from the matching Triton release. In this case the r20.06 clients.
