### ISSUE TITLE
Is it possible to release the additional gpu memory occupied for inference on a batch?

### ISSUE THREAD

**Issue by shv07** [triton-inference-server/server#3565]
Hello,

My use case requires deploying multiple models with same gpu. I have been deploying models in Tensorflow_Serving format with triton and have noticed the gpu usage increasing when an inference is made. 

Initially it seemed the increase is just to load the model weights during the first inference request, but it is not the case as depending upon the available memory it tends to occupy it almost entirely (currently using 6 GB gpu). And thus leading to OOM error when inferring on other deployed models.

Is it possible that the triton server releases the additional unused gpu memory after each inference is complete? This would allow performing inferences on other deployed models.

**Comment by dzier** [comment]
Triton does not automatically unload and load new models based on the request. This is a feature we are considering but have not committed to. For now, the best practice is to configure the models, if possible, so that they all can fit on the GPU simultaneously.

See https://github.com/triton-inference-server/server/blob/main/docs/model_management.md for the current information on how to manage multiple models.

**Comment by shv07** [comment]
> Triton does not automatically unload and load new models based on the request. This is a feature we are considering but have not committed to. For now, the best practice is to configure the models, if possible, so that they all can fit on the GPU simultaneously.
> 
> See https://github.com/triton-inference-server/server/blob/main/docs/model_management.md for the current information on how to manage multiple models.

Thank you for your reply @dzier. 

However, I didn't mean to unload models. I was wondering if somehow the additional gpu memory occupied due to a batch of examples could be freed somehow (after the inference is complete).

**Comment by shv07** [comment]
Any updates on this?
