### ISSUE TITLE
Class InferResult not released causing memory leak

### ISSUE THREAD

**Issue by chuanzhao0626** [triton-inference-server/server#3655]
**Description**

    union TritonClient {
      TritonClient()
      {
        new (&http_client_) std::unique_ptr<nic::InferenceServerHttpClient>{};
      }
      ~TritonClient() {}
    
      std::unique_ptr<nic::InferenceServerHttpClient> http_client_;
      std::unique_ptr<nic::InferenceServerGrpcClient> grpc_client_;
    
    };

    nic::InferResult* resultGrpc;
    nic::InferInput* input;
    nic::InferRequestedOutput* output;

    err = triton_client.grpc_client_->Infer(
                &resultGrpc, options, inputs, outputs, http_headers);
    if (!err.IsOk()) {
        std::cerr << "failed sending synchronous infer request: " << err
                << std::endl;
        return false;
    }   

I wrapped the above code into a function that the program would Multithreaded call over and over again. Because there is a Create operation in the pointer class, the requested space is not released, which leads to memory leakage.
Please ask how to release the above class pointer, you can give an example.
Looking forward to your reply.

**Triton Information**
21.03

**Comment by tanmayv25** [comment]
[This section](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/examples/simple_grpc_infer_client.cc#L259-L266) in the example demonstrates how you can wrap the pointer to a smart pointer(shared_pointer or unique_pointer, whatever better represent your case) and not worry about freeing up the memory. Otherwise you have to explicitly call `delete` on the object pointer to free the memory allocation
