### ISSUE TITLE
question about batch inference

### ISSUE THREAD

**Issue by ggslayer** [triton-inference-server/server#3693]
Hi, I have a question about the batch.

Now, I run my model with triton, batch disabled, I run a test program with concurrent inference call, the gpu usage can grow up to 100%, and the throughput is 21/s.

I wan't to know, if i enable batch, can increase the throughput more than 21/s?  if it can, why? can you give me some backgound knowleges about this?  thank you!

**Comment by Tabrizian** [comment]
By "GPU usage" do you mean the GPU utilization or GPU memory usage? Using [dynamic batching](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#dynamic-batcher) can help your model better utilize the memory bandwidth available in GPUs by transferring larger chunks of memory instead of transferring smaller chunks of memory multiple times.

**Comment by ggslayer** [comment]
I mean GPU utillzation got by nvidia-smi, 
with no batch, it reach 100% under concurrent call, the max throughput is 21/s.
batch can increase the throughput more?

**Comment by dyastremsky** [comment]
It's possible. The best way to know for your specific model and environment is to try running it with batching. Perf_analyzer and model analyzer can help with measuring performance.

**Comment by ggslayer** [comment]
thank you for your reply @dyastremsky  @Tabrizian
