### ISSUE TITLE
Onnx  with TensorRT in Windows 10 platform

### ISSUE THREAD

**Issue by umutozturk95** [triton-inference-server/server#3742]
I add the following parameter to the config file. Triton server is included into my application by using C api on windows platform.

**
optimization { execution_accelerators {
  gpu_execution_accelerator : [ {
    name : "tensorrt"
    parameters { key: "precision_mode" value: "FP32" }
    
    }]
}}**

But  TRITONSERVER_ServerNew function gets stuck. I am sending detailed log to solve the problem(this log file is created by using verbose parameter). TritonServer gives me warning message  onnxruntime::TensorrtLogger::log] [2021-12-28 15:53:04 WARNING] Detected invalid timing cache, setup a local cache instead
[logs.txt](https://github.com/triton-inference-server/server/files/7785467/logs.txt)

Thanks

**Comment by umutozturk95** [comment]
I added warmup but it does not work .Does warmup mechanism support in  Windows platform?

**Comment by dzier** [comment]
The TensorRT warmup does work on Windows, since it is a fundamental part of TensorRT. Does the TRITONSERVER_ServerNew never return? Or can you still perform an inference and it is just slow?

It can take some time for the onnx runtime backend to perform the TensorRT optimization when loading a model. Is this what you mean by "stuck"?

If it does eventually return the request, are subsequent requests also slow, or do they return with the expected end to end latency?

**Comment by umutozturk95** [comment]
@dzier  This stuck is that occurs when initializing tensorrt optimization. I am using densenet_onnx model, so  this at the firstinference phase takes more than 1 minute.But the other requests/inferences  is very fast(takes about 30 ms inference). I think it's a bit troublesome that this first inference is stuck for a long time. I used warmup to solve this delay.But it is not work.Maybe I did it wrong.Can anything be done to speed it up for first inference? 
Th other question, are there any other optimization parameters for onnx with tensorrt? Perhaps the 30 ms inference time can  be lowered. I am inferecing on streaming data in real time, so it will be great if triton can reduce the delay.
Thanks.

**Comment by dzier** [comment]
There is nothing you can do in Triton to speed up the optimization step in ORT-TRT? For further optimizations within ORT-TRT, you would need to ask in the ORT forums, not Triton Inference server.

There are plenty of options of that you can change to improve the general Triton performance, including the batch size and number of model instances. We have a tool called [Model Analyzer](https://github.com/triton-inference-server/model_analyzer) that can help find the best Triton model configuration for your current system configuration. However, this does not yet work on Windows.

Alternatively, you could convert your entire ONNX model to TRT offline and just run the TRT model. This will remove the optimization step all together, however, you will loose in portability, since the model will be very specific to a version of TRT and a GPU.

**Comment by umutozturk95** [comment]
@dzier  Thank yo very much.
