### ISSUE TITLE
Python backend ensemble model extra input params

### ISSUE THREAD

**Issue by gandharv-kapoor** [triton-inference-server/server#3794]
I am currently using triton python backend where I have following sequence **preprocess -> onnx-model predict -> postprocess** as three different models sequenced together using the ensemble feature. Now in my preprocess step I split input string paragraphs into sentences which are tokenized before being sent to the onnx model. 

I basically want to assign **two extra parameters/metadata basically a Paragraph Id and a Sentence Id to uniquely identify each tokenized input** and also want that information to be returned and available in the post-process stage so as to combine results from onnx model. **These extra metadata/params generated in pre-process are not the inputs to the onnx models as model just cares about tokenized array per sentence for classification but still required in the last step (post process). I want to ask if theres a way to pass and flow this extra information in this three stage pipeline?**

What would be the best way to go about such requirement?

**Comment by dyastremsky** [comment]
If only that metadata needs post-processing, you can send it directly to postprocess. However, if you need it with your classification, then you should send it to the onnx-model predict step, do nothing with it, and have your model output it in that stage.

I do not believe there is a way to send your postprocess model the paragraph and sentence IDs associated with a specific classification otherwise. Moreover, any such attempt would involve using an identifier anyway, diminishing any advantage or performance gain over not sending the identifiers in the first place.
