### ISSUE TITLE
its easy to compilation failure in China

### ISSUE THREAD

**Issue by lixiong4788** [triton-inference-server/server#3820]
Hi, I’m @lixiong4788
I’m interested in the third-party build, 
why we can't find the file(like /tmp/tritonbuild/tritonserver/build/third-party/libevent/include/evhttp.h) in the local system. 
the /tmp don't contain anything about the tritonbuild ,how can we do that? 
Is there a way to cache the git files of third-party libraries？ 
China's network is not good, it is often easy to interrupt and cause compilation failure.

**Comment by deadeyegoodwin** [comment]
The Triton build requires that it pull code from github using the cmake FetchContent and ExternalProject commands. You can find this in almost all CMakeLists.txt files in the various repos that make up Triton. You can likely change those to use local copies of the source code so that the build does not need so much network access. You will need to edit the FetchContent to point to your local copies.
