### ISSUE TITLE
Understanding Backends

### ISSUE THREAD

**Issue by bro-adm** [triton-inference-server/server#3847]
Hello, I have some questions regarding how to handle different backend situations:

## Main Information
- triton version: 21.12-py3
- running the image on windows 10

## Use Cases
1) I have a multi model repository where all the models want to use the python backend with the same python version and the same dependencies. What is the best way to configure such a case?
We have noticed that the python backend works according to the main python version in the container, meaning that if we install on the container the extra python version we want to use 
and make that the main env python, the python backend will use that python version?
(that is an interesting point that is not written in the docs -> are we wrong in our understanding?)
Next question in the same story line -> What do we do about dependencies? Can I just pip install them globally?
We think it shouldn't affect any backend or your code because the backends are .so files, each backend is a singular point of execution and are separated from one another and your code in not in python. Are we wrong?

2) I once again have a multi model repository and once more all of them use the python backend, but this time each one is in different python versions. 
I don't want each time I deploy a triton server with this same case, to create the corresponding stubs and insert them into the according models directories.
Would the desired solution be to build an image over the triton version image that holds the stubs inside different directories and while creating the model repository copy the stubs to their matching models directories?
Now let's say I don't have the ability to copy those stubs myself into the model repository, 
would creating a custom backends-directory that holds python-3.7, python-3.8, python-3.9 ... backend directories with only the corresponding stubs inside them give me what I am looking for (using the --backend-directory parameter + then I just put the matching backend key in the config.pbtxt)?
What should I do with the different dependencies in this scenario, maybe put in the code itself in the model class in the initialize method (that loads the model) a pip install call for my requirements.txt file), if not, what would you advise me to do?
note: the custom backends would not have the libtriton_python.so and the utils.py file -> is this of relevance?

## Extra
- What would happen if inside a conda environment, I would use the available env pip and installed my dependencies, and the conda-pack works, would it work for you as well or should I expect a weird error?
![conda inner pip install](https://user-images.githubusercontent.com/88341155/150781977-43932501-5f22-40b5-9e15-a790df0a93b8.png)
I pip installed flask inside the conda env just for demonstration and all the ones with the channel pypi and build pypi_0 were added.
https://www.anaconda.com/blog/using-pip-in-a-conda-environment

- Running ‘which python’ in the container gives us the python3.8 and doing ‘whereis python’ gives us a big list of multi python3.8’s and one 2.7 and one 3.9. What should I expect to happen if I delete all the global pythons in the container?
How would the default python backend work? 
Will the other backends such as pytorch not be affected because they are represented by .so files or would they fail (same for just changing the main env global python version)?
Note:
![weird gloabl python](https://user-images.githubusercontent.com/88341155/150782310-9cc79b2c-5884-42df-ada9-1457e913a19a.png)
Somehow the 3.8 returns an answer to the which command but in the whereis all the others appear. After deleting the 3.8 the whereis shows only the 3.8 like the 2.7, 3.9 where deleted. I don’t understand. 

- Would there be a way with the concept of a custom backends directory to have multiple versions of other backends such as pytorch?
Reason: I would like to to have the pytorch version of triton 21.09 in the 21.12 version + the one currently supported in the 21.12

- Does the python version x stub need to be created per triton version on the matching triton server version container that it is going to be deployed on (and if so does it need to be created on the same container itself or can it be different containers of the same image (I would bet on the former))?
And are we incorrect in assuming that the python backend stub is per python major and not minor?

- In your documentation about creating the stub, step 1.2 is to create and activate a stub that is later used in step 2 and does not seem to be used in step 1. Is it required for the creation of the stub itself? 
If it is required, is the same conda pack required for the model dependencies or can it be a fresh one?
https://github.com/triton-inference-server/python_backend#important-notes

- Are we wrong in thinking that when loading a model first the base triton loading happens such as setting the environment (for python it would be loading the stub) and then the initialize method of the model class?

- Is there a script that builds all the backends according to configuration like multi pytorch versions with the triton version and same for python and more…?

- Is there a reason that cmake and conda are not installed on the image (just to know)?

**Comment by GuanLuo** [comment]
@Tabrizian Can you take a look at the Python backend questions?

In general it is not good to have multiple versions of the same backends reside in the same environment, as it is likely to crash the server when it tries to load different versions of the same library due to conflicting symbols. Yes, you may provide various "custom backends" each corresponds to different version of the library and specify the proper version via "backend" field in model config. But then you need to carefully manage the model being served to avoid loading different versions of the library. TensorFlow backend is an example of allowing Triton to serve either TF1 or TF2, you may refer that in your custom backend implementation. But note that even in TF backend, Triton uses a command line argument to select one of the TF versions throughout the run.

**Comment by Tabrizian** [comment]
> I have a multi model repository where all the models want to use the python backend with the same python version and the same dependencies. What is the best way to configure such a case?

You can use the [Python execution environments ](https://github.com/triton-inference-server/python_backend#using-custom-python-execution-environments) but you don't have to compile the stub since the Python version of the dependencies is matching the Python version that is available in the container. All your models can point to the same execution environment and it will be extracted only once.

Alternatively, you can install all the dependencies in the container and your Python models will automatically pickup the default environment.

> We have noticed that the python backend works according to the main python version in the container, meaning that if we install on the container the extra python version we want to use and make that the main env python, the python backend will use that python version?

I don't think Python backend will pick that environment if the Python version is different. The reason is that there is a Python interpreter embedded in the `triton_python_backend_stub` file that is not dependent on the Python version available in the environment (it is always 3.8 unless you are compiling your own stub). If the Python version is different you need to compile your own stub.

> What do we do about dependencies? Can I just pip install them globally?

You can just pip install all the dependencies in Python backend and all your python models will be able to use them.

Regarding the second point, as you mentioned, you could create different backend directories and control it using the backend parameter field but you need to put the full Python backend compiled with different Python versions in the backends directory (it must include the stub file, `triton_python_backend_utils` and everything else included). For the environment you need to create a tar file using conda-pack and use that for each of the models.

> I pip installed flask inside the conda env just for demonstration and all the ones with the channel pypi and build pypi_0 were added.

I think if you use the `pip` inside the conda env you should be fine. However, you need to set the `export PYTHONNOUSERSITE=True` to make sure it is not using dependencies that are not available in the env.

>Will the other backends such as pytorch not be affected because they are represented by .so files or would they fail (same for just changing the main env global python version)?

I don't think other backends will be affected (@CoderHam can provide a definitive answer). But Python backend may not work if you have also uninstalled dependencies.

> Would there be a way with the concept of a custom backends directory to have multiple versions of other backends such as pytorch?
Reason: I would like to to have the pytorch version of triton 21.09 in the 21.12 version + the one currently supported in the 21.12

@CoderHam

> Does the python version x stub need to be created per triton version on the matching triton server version container that it is going to be deployed on (and if so does it need to be created on the same container itself or can it be different containers of the same image (I would bet on the former))?
And are we incorrect in assuming that the python backend stub is per python major and not minor?

The stub must be created for the for each Triton version. The previous versions of stub may not work with newer version of Triton or vice versa. I think it can be created on different containers of the same image.

> Are we wrong in thinking that when loading a model first the base triton loading happens such as setting the environment (for python it would be loading the stub) and then the initialize method of the model class?

No, you are not wrong. This is correct. It sets some environment variables to make sure the conda env is picked up correctly.

> Is there a reason that cmake and conda are not installed on the image (just to know)?

We try to keep Triton container dependencies minimal and that's why CMake and conda is not installed in the container.

> Is there a script that builds all the backends according to configuration like multi pytorch versions with the triton version and same for python and more…?

@CoderHam 

> In your documentation about creating the stub, step 1.2 is to create and activate a stub that is later used in step 2 and does not seem to be used in step 1. Is it required for the creation of the stub itself?


Yes it is required for the creation of the stub itself too. As shown in the next command, the output of the `ldd` depends on which environment you have activated.

> If it is required, is the same conda pack required for the model dependencies or can it be a fresh one?
https://github.com/triton-inference-server/python_backend#important-notes

It is the same environment.

**Comment by CoderHam** [comment]
> Would there be a way with the concept of a custom backends directory to have multiple versions of other backends such as pytorch?

@bro-adm this might cause symbol conflicts or issues with deps if the pytorch versions between the two are built with different cudnn/cuda versions.  I encourage you to try the same with a custom backend for pytorch (say pytorch2 for example)

Triton does not plan to officially support this as of now.

> Is there a script that builds all the backends according to configuration like multi pytorch versions with the triton version and same for python and more…?

We have something like this for Openvino as described [here](https://github.com/triton-inference-server/server/blob/main/build.py#L67-L92). While we do not plan to officially support this you can try to build it using a similar path.  

What is the motivation behind needing two versions of pytorch?

**Comment by naor2013** [comment]
@CoderHam since the Pytorch backend isn't based on Pytorch releases but based on Nvidia's Pytorch which takes from master and changes things on top of it, there isn't a good compatibility.
A model built on Pytorch 1.10 might not work on Triton's pytorch backend.
That seems like something that isn't going to change.
We want to provide many options for our users with multiple versions of pytorch supported based on what versions they used.

**Comment by bro-adm** [comment]
I am a bit confused

## Pre Stub Creation Steps
This are the steps I took to install the needed stuff to create the python backend stub:
    1  apt-get update
    2  apt-get install curl
    3  cd /tmp
    4  curl -O https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
    5  bash Anaconda3-2021.11-Linux-x86_64.sh -b -p $HOME/anaconda3
    6  eval "$($HOME/anaconda3/bin/conda shell.bash hook)"
    7  conda deactivate
    8  conda init
    9  source ~/.bashrc
   10  conda deactivate
   11  conda info
   12  apt-get install build-essential libssl-dev
   13  cd /tmp
   14  wget https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2.tar.gz
   15  tar -zxvf cmake-3.22.2.tar.gz 
   16  cd cmake-3.22.2
   17  ./bootstrap
   18  make
   19  make install
   20  apt-get install rapidjson-dev libarchive-dev -y
   21  apt-get install zlib1g-dev
###### Notes:
- I tried to make the anaconda installation be silent, that is why I put the -b -p parameters when running the script in step 5.
- I ran step 21 because it was missing for the next steps in the tutorial to work?

## Questions:
- Without running step 6 conda was not recognized and after running step 6 it started an environment called 'base', I don't yet fully understand the conda init I was told I could run (step 8), and I think I need to run step 9 witch again activates the 'base' environment. Can I skip some of this steps (referring to the conda related steps) and I don't know if the base environment means anything (just making sure it doesn't)
https://phoenixnap.com/kb/how-to-install-anaconda-ubuntu-18-04-or-20-04
https://docs.anaconda.com/anaconda/install/silent-mode/

- The creation of the stub itself which was created according to the next steps in the docs (https://github.com/triton-inference-server/python_backend#1-building-custom-python-backend-stub) only worked inside the /tmp/cmake-<version> directory.
This makes me think maybe the stubs can only work in an environment where the cmake directory exists fully.
We already understand that the conda pack needs to  be the same one that the stub is created from (+the extra dependencies), but does the /tmp directory with all the new conda and cmake stuff need to be created as well in the triton server image where I am actually running the triton server or the stub on it's own is sufficient? Do you maybe know why the stub creation itself would only work inside the cmake dir?

- You have the possibility for the model repository to be set in remote systems such as S3, how does that work if the stubs and conda need to be a part of the server container itself. Should the steps be to put everything I want in the s3 directories and then in the triton container create the stub, extract the conda pack and stub and put it in the s3 directory only to pass the s3 to you again as a parameter, or should the building of the model repository be a 2 part set up (one creating everything outside and then finishing up the extra layers inside the container) or is the wanted way of working with this to build it all from the container and then start the server

**Comment by bro-adm** [comment]
@Tabrizian, you said that pip installing globally would work, but as I understand, it will only work with the default (in this case 3.8) python version. Correct?
if it were to work on more than one version it will be with just adding the stubs for each model dir in the model repo, but then shouldn't the pip be of the matching python version (like 3.7 should have a different pip from 3.8)? If so what should be done?

**Comment by Tabrizian** [comment]
> Can I skip some of this steps?
 
You don't have to compile CMake from source. You can use the cmake Ubuntu repository to install an appropriate version.  https://github.com/triton-inference-server/server/blob/main/qa/L0_backend_python/common.sh#L46-L52

The base env is default environment that conda creates when being installed. I think there are some flags to disable it's activation.

> next steps in the tutorial to work?

I'll update the docs to mention this dependency.

> Do you maybe know why the stub creation itself would only work inside the cmake dir?

Stub creation requires dependencies that you installed. But running the stub only requires your conda env to be tarred using conda-pack. Are you saying that you couldn't run the stub outside the build env or only you couldn't compile it?

>  I want in the s3 directories and then in the triton container create the stub, extract the conda pack and stub and put it in the s3 directory only to pass the s3 to you again as a parameter,

Correct. When using S3 everything should be in the model directory. You can reference your conda-pack env relatively using `"$$TRITON_MODEL_DIRECTORY`.


> the global pip idea should work per only for python 3.x because the pip should be according to major python version correct? am I missing something?

Yes. Even if the minor version is different you need to put your stub in the `/opt/tritonserver/python/triton_python_backend_stub` so that all the models can use it. I don't think you can get the Python backend working with Python 2.x. Python 2 is end of life now.

**Comment by bro-adm** [comment]
> Are you saying that you couldn't run the stub outside the build env or only you couldn't compile it?

I couldn't run this commands when I wasn't inside the /tmp/cmake directory:
- cmake -DTRITON_ENABLE_GPU=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install ..
- make triton-python-backend-stub

That made me think that the cmake dependencies would be required not only in the container I was creating the stub but also in the container where I was running the server. From what I understand now cmake is not required to run stub in the container where I run the server... it is only required for the stub creation.

I need to create the stubs and conda-packs on a triton server container but the actual server I am deploying is not on the same container. So I now understand that after creating the stubs and the conda tars, in the container where I will run the server I don't need to have installed cmake and I do need to have conda installed.

> /opt/tritonserver/python/triton_python_backend_stub

I will look into that further...

Thanks

**Comment by bro-adm** [comment]
> /opt/tritonserver/python/triton_python_backend_stub

python isn't a directory inside /opt/tritonserver -> do I need to create it or are you reffering to the /opt/tritonserver/backends/python directory?

if it is the second option do I just replace the stub in there with my version of python stub and how does that affect the triton_python_backend_utils.py file and the libtriton_python.so file and where does the conda pack fir here?

**Comment by CoderHam** [comment]
@bro-adm yes Iman meant  `/opt/tritonserver/backends/python`. You will likely need to replace the libtriton_python.so if you have built a custom one.

**Comment by Tabrizian** [comment]
Sorry I missed this message.

>  From what I understand now cmake is not required to run stub in the container where I run the server... it is only required for the stub creation.

Correct.

Yes, I meant the /opt/tritonserver/backends/python directory. You don't need to replace the `libtriton_python.so` but you need to make sure that your stub is built for the exact same version of Triton. For example, you can't build a stub from 21.10 release and expect it to work with 21.12 release. You only need to replace /opt/tritonserver/backends/python/triton_python_backend_stub file.

**Comment by bro-adm** [comment]
Thanks, 
You made my day!!!

**Comment by bro-adm** [comment]
@Tabrizian 
Hello again,

After your help we decided to move on with the concept of the changing the stub inside /opt/tritonserver/backends/python directory according to the python&triton versions we are asked for.
Some new information:
- we are working on an on-prem environment so we don't have the privileges with working online.
- we are working with k8s.
- I am working outside the premise on a windows 10 pc
- triton version 21.12-py3

The situation with cmake and conda on our on-premise isn't as easy as just installing them and creating the stubs (which takes quite some time). All the things shown next were done outside the on-prem environment.

As concluded before in our chat, `cmake` and `conda` are only needed for creating the stubs and not for using them, so we tried to create different stubs per the matching triton version. In order to achieve that, we needed to save the stubs created outside of the container they were created on, so we ran the container with a mount to some folder on the windows computer we were running the container on.

`docker run -it --rm --mount type=bind,source=%cd%/future_stubs_on_computer_folder,target=/opt/tritonserver/new_folder_name nvcr.io/nvidia/tritonserver:XX.YY-py3`

So we tried running the stub creation steps as shown in our previous conversation, but now we tried to download cmake as shown in https://github.com/triton-inference-server/server/blob/main/qa/L0_backend_python/common.sh#L46-L52 as you showed us, that went with no success because `gpg` and `tee` commands were unknown (we successfully installed `gpg` but `tee` wasn't found -> we didn't waste much time on that so we just ran the same steps as shown before).
After creating the stubs we ran the `ldd` command on them in order to verify what you say in the docs is the case.

```bash
$ ldd triton_python_backend_stub
...
libpython3.6m.so.1.0 => /home/ubuntu/envs/miniconda3/envs/python-3-6/lib/libpython3.6m.so.1.0 (0x00007fbb69cf3000)
...
```

All I did is just exporting the stubs created on the triton container to my local machine (Windows),
and then mounted the relevant stubs to another triton container (`docker ... --mount` ) and surprisingly the `so` 
file (`libpython3.7m.so.1.0`) wasn't found.

We are now at a stage where the stubs are good and the container is running and they are already present as well on the computer mount..., so we exit the container -> once we try to see what will happen when we load the same stubs inside another container of the same triton version (still outside the premise jus to mimic that scenario) we run the same docker run command shown above with the mount now holding the stubs, but now inside the container the` ldd` command shows that the component which was specified in the stub is 'not found'.

![ldd fail](https://user-images.githubusercontent.com/88341155/153161722-7f9a1e95-3bbb-4ec9-bb21-d2b9cf663615.png)
 
We don't know if it has something to do with windows.

To sum up, on the first container (the same container on which the stubs were created) we were at a point where the stubs were working and the container was running and they were already present as well on the computer (because of the docker mount)..., after closing the container and exporting the stubs into another container (using again docker mount) the `libpython3.7m.so.1.0` wasn't found.

We tried some other stuff after that as well:
- we tried saving the conda-packs with the stubs in that mount, and loading them into a new container with conda already installed in order to unpack them and then run the `ldd` command on the matching stub.
- we tried saving the stubs inside a tar in the container they were created and then exiting it and opening another container.
- some other combinations of the same ideas.

All of them led to the same `ldd` missing file result.
Do you have some idea of what might have caused it and maybe some ways to fix it?

We are trying to keep the image as small as possible so we want to find a way without building an image over the triton server image with `cmake` and `conda` installed.

### EXTRA
Do you have any backlog task on adding a python version backend config (`--backend-config=python,version=<PYTHON_VERSION>`)  + keeping the global pip install?

**Comment by Tabrizian** [comment]
> To sum up, on the first container (the same container on which the stubs were created) we were at a point where the stubs were working and the container was running and they were already present as well on the computer (because of the docker mount)..., after closing the container and exporting the stubs into another container (using again docker mount) the libpython3.7m.so.1.0 wasn't found.

Do you specify `EXECUTION_ENV_PATH` in the config.pbtxt file of your model in this scenario or you want all your Python models to pick up Python 3.7? If you are specifying the `EXEUCTION_ENV_PATH`, it will automatically modify the LD_LIBRARY_PATH such that when the stub is being loaded libpython3.7 can be found. Does the model load successfully in this scenario? I think it is expected that the ldd output looks like what you have shared above when you change the container. The verification is only required for when you are compiling the stub. 

> We are trying to keep the image as small as possible so we want to find a way without building an image over the triton server image with cmake and conda installed.

After the tar file is created you won't need cmake or conda. https://github.com/triton-inference-server/server/blob/main/qa/L0_backend_python/env/test.sh#L55 In this test if you transfer the environments created to another container that doesn't have conda or cmake, it should work properly.

> Do you have any backlog task on adding a python version backend config (--backend-config=python,version=<PYTHON_VERSION>) + keeping the global pip install?

I don't have any tasks like this in the backlog and I don't think it is possible. I think some python dependencies require a specific version of Python. For example, one version of TF may only work with a specific version of Python and you can't use the same TF with different Python versions. However, you can simulate this environment by creating different versions of Python backend that is compiled with different Python versions and instead of specifying `backend: "python"`, you can specify `backend: "python_3_6"` for example. You need to rename the `libtriton_python.so`  to `libtriton_python_3_6.so` so that your model works properly.

**Comment by bro-adm** [comment]
@Tabrizian 
Thanks, currently working on changing the stub in `/backends/python` dir :slightly_smiling_face:

###### just to know

- With the repository agents (if they weren't in beta), we could have ideally create a repo agent that reads in the model config a python version parameter and add into the matching model dir the matching stub -> if so according to our understanding we would also need to include the conda pack tar gz in the same place, but as you already know we are trying to avoid using conda, so would pip installing globally (while we are still putting the stub and the conda pack in each required models dirs because its required) still be usable or would we need to conda pack using the inner conda pip and put a shared EXECUTION_ENV_PATH in all the configs?

- We have arrived at an understanding that a global pip install should work with any stub we put in the `/backends/python`, so why if we were to put the stub inside the model dir itself per each model would we have needed to provide the conda pack tar gz as well?

**Comment by shoval-a** [comment]
@Tabrizian it seems that the issue with `libpython3.7m.so.1.0` not found - has been solved.
All you need to do is to run `export LD_LIBRARY_PATH=/path/to/libpython/directory` in the container.

**Comment by Tabrizian** [comment]
@bro-adm / @shoval-a Sorry for delayed response.

> We didn't really understand the TF comment -> are you talking about the TF backend? is it dependent on the python one? where are this python dependencies set? how would using the same TF version come about with using different Python versions?

It is not about the TF backend but just an example of using a certain version of TF with different Python versions. Some TF versions are not compatible with some Python versions. You could have multiple global Python versions but I have not tried it.

> With the repository agents (if they weren't in beta), we could have ideally create a repo agent that reads in the model config a python version parameter and add into the matching model dir the matching stub -> if so according to our understanding we would also need to include the conda pack tar gz in the same place, but as you already know we are trying to avoid using conda, so would pip installing globally (while we are still putting the stub and the conda pack in each required models dirs because its required) still be usable or would we need to conda pack using the inner conda pip and put a shared EXECUTION_ENV_PATH in all the configs?

With the global python interpreter you don't need to have the EXECUTION_ENV_PATH.

cc @GuanLuo to comment on the model repository agents.

> We have arrived at an understanding that a global pip install should work with any stub we put in the /backends/python, so why if we were to put the stub inside the model dir itself per each model would we have needed to provide the conda pack tar gz as well?

I think you don't need to provide the conda pack if you only provide the stub.

**Comment by bro-adm** [comment]
@Tabrizian 
Hey, just to sum up

> I think you don't need to provide the conda pack if you only provide the stub.

> @Tabrizian it seems that the issue with libpython3.7m.so.1.0 not found - has been solved.
All you need to do is to run export LD_LIBRARY_PATH=/path/to/libpython/directory inside the container.

> 
![image](https://user-images.githubusercontent.com/88341155/158355959-f404e0da-c9a6-484a-b90b-ca1202e283bc.png)

As said above, other than the stub that we set inside the /backends/python dir, the  libpython3.7m.so.1.0 is required as well. 
So after creating the stubs we just need to export into our on prem the conda pack as well.

In the new image we build over the triton image (that holds the matching triton version python versions stubs and conda packs) we run this steps:
- load the wanted stub in the /opt/tritonserver/backends/python
- untar the matching conda pack (without conda)
- we set the LD_LIBRARY_PATH to the /path/to/libpython/directory which will be set inside the untared directories from the conda pack
- we then need to link /opt/venv/bin/python /path/to/untared-python (..../bin/python3.7)
- remove recursively the /opt/venv/lib/python3.8 (this is the already set default python that exists in the container)
- copy the new python from the lib dir in the untared conda pack dir into the /opt/venv/lib/<PYTHON_VERSION> (3.7 -> python3.7)
- export PYTHONPATH=/opt/venv/lib/<PYTHON_VERSION>
- reinstall numpy -> the one that comes from the untared conda pack is weird (uninstall numpy + install numpy)

###### all the links and removals and new directories need to match what they are trying to replace (for exampe -> /lib/python to /lib/python and same for bin...)

### PS

> EXTRA
Do you have any backlog task on adding a python version backend config (--backend-config=python,version=<PYTHON_VERSION>) + keeping the global pip install?

We are trying to implement a --backend-config=python,version=? parameter externally from the tritonserver command cli.
That worked for us but I am pretty sure from what said above in this conversation and from some other issues that we may have ruined the pytorch backends for example because it seems to use the stub inside the opt/tritonserver/backends/python dir. 

THANKS
