### ISSUE TITLE
[Question] how to update config.prototxt to support different model input shape

### ISSUE THREAD

**Issue by zijin520** [triton-inference-server/server#3865]
For a onnx model with input shape[1,3,32,32], it works well with the config.prototxt bellow.
    _name: "cat_dog_onnx"
    platform: "onnxruntime_onnx"
    max_batch_size : 0
    input [
      {
        name: "data_input"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: [ 3, 32, 32 ]
        reshape { shape: [ 1,3, 32, 32   ] }
      }
    ]
    output [
      {
        name: "prob_Y"
        data_type: TYPE_FP32
        dims: [ 2 ]
        reshape { shape: [ 1,2  ] }
        label_filename: "cat_dog_labels.txt"
      }
    ]_

(1) If the onnx model with input shape[2,3,32,32], how to modify the model.prototxt to make it works? 
If I continue to use the former config.prototxt, I got error bellow.
![image](https://user-images.githubusercontent.com/83391270/151475033-f3364f5c-912b-4566-94a7-e4a3c178c6fb.png)

If I modify the reshape part of the former config.prototxt to be "reshape { shape: [ 2, 3, 32, 32   ] }", I got another error bellow.
![image](https://user-images.githubusercontent.com/83391270/151474854-b7c98f93-f451-49aa-98f0-014e2ef58665.png)
(2) If I want to use dynamic batching, how to modify the model.prototxt? 

Thanks very much.

**Comment by GuanLuo** [comment]
(1) You don't need to use `reshape` for your model, you just specify the input dims to be `dims: [1, 3, 32, 32]`. And similarly for the new model with shape that you mentioned, you specify `dims: [2, 3, 32, 32]`

(2) Firstly your model should support batching, in other words, the first dimension of all inputs / outputs should be dynamic size (-1). Otherwise, your model actually expects batches of specific batch size which can't be dynamic batched.

Then in the model config, you specifies the `max_batch_size` to be the largest batch size that Triton may form a batch to. And the `dims` for the inputs and outputs will need to be the shape excluding the batch dimension, so if your model input has full shape [-1, 3, 32, 32] where -1 is the batch dimension, you will specify `dims: [3, 32, 32]` for the input.
