### ISSUE TITLE
Best practices for loading a new model version across Triton instances

### ISSUE THREAD

**Issue by cakeislife100** [triton-inference-server/server#3935]
Hello! We are using the method described [here](https://github.com/triton-inference-server/server/blob/main/docs/faq.md#how-would-you-use-triton-inference-server-within-the-aws-environment) and running multiple Triton instances between a load balancer to be able to scale up our model servers. This is working great except for when a new model is loaded to the repository. Normally we can just call `POST /v2/repository/models/<model_name/load`, but in the case with a load balancer, it will just send that request to one of the Triton servers and that's the only one that will have loaded the model.

Are there best practices for how to load the model across all the different Triton instances behind the load balancer?

**Comment by Tabrizian** [comment]
I'm not very familiar with load balancers but is there an option to change the behavior based on the request type? For example, if the request pattern matches what you have described above it should broadcast the request to all the instances, instead of only sending the response to one of them.

cc @rmccorm4

**Comment by rmccorm4** [comment]
Hi @cakeislife100, I don't believe there is a way to explicitly reach every instance behind a load balancer or ensure that the load balancer routes a request to a specific instance without some kind of special workaround.

Typically for something like this, I would expect a user to explicitly send the model load requests to each individual instance rather than through the load balancer. You would need to allow the incoming traffic in the security group to do so, but you can limit this to only specific IPs for security purposes.

You may be able to programatically do this via AWS APIs by grabbing all instances in a certain security group or grabbing the instances associated with a certain load balancer.

In general, it's a good practice that instances behind a load balancer are stateless so you don't need to worry about any individual instance when scaling up/down.

**Comment by rmccorm4** [comment]
Closing since no response in > 2 weeks.
