### ISSUE TITLE
[Question] About perf_analyzer request & execution count

### ISSUE THREAD

**Issue by gggaugau** [triton-inference-server/server#3941]
Hello guys. I have a question about perf_analyzer request & execution count. 
```
root@ai-gpu-2:/workspace# perf_analyzer -m ensemble_models -b 32 --shape INPUT:640,640,3 
*** Measurement Settings ***
  Batch size: 32
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
  Client: 
    Request count: 17
    Throughput: 108.8 infer/sec
 ...
  Server: 
    Inference count: 672
    Execution count: 21
    Successful request count: 21
```
Why is execution count > request count in the example below? What exactly does execution count mean?
Thanks in advance.

**Comment by naor2013** [comment]
@gggaugau I'm not from the triton team but what it means is that there were 21 requests of batch 32 (which is what you specified in -b 32) so that makes a total of 672 "single" inferences in 21 requests.

**Comment by GuanLuo** [comment]
The client stats and server stats are being collected in different location where client stats is collected inside perf analyzer while server stats is calculated based on the delta reported from server stats API, so the variance will be observed if you compare client stats with server stats.

**Comment by GuanLuo** [comment]
Execution count is the number of the model run, where request count is the number of inference request sent to the model. When using dynamic batching, Triton may batch multiple requests for one model run and in such case you can have smaller execution count than request count.

**Comment by Jackiexiao** [comment]
but in this example, execution count 21 is bigger than request cout: 17, and why inference cout is different from request cout.

**Comment by Tabrizian** [comment]
You should compare the Server Request count with server execution count. As shown in the report that you've shared, server execution count is equal to the server request count. The client request count can be lower than the server request count since some requests might be ignored if they are not received within the expected timeframe. The inference count is the batch size of your request multiplied by the execution count.

**Comment by Jackiexiao** [comment]
> The client request count can be lower than the server request count since some requests might be ignored if they are not received within the expected timeframe.

I am still confused, if some requests might be ignored, doesn't it means server get less request?

**Comment by matthewkotila** [comment]
> @Jackiexiao: I am still confused, if some requests might be ignored, doesn't it means server get less request?

Perf Analyzer is split into two parts that run concurrently. There is one part that sends requests to the server. And there is another part that observes and measures the requests being sent/received back from the server, to calculate performance metrics. In this situation, when a request is "ignored", it means that the second "part" of Perf Analyzer mentioned earlier is not observing a request sending/receiving that is happening concurrently in the first "part" of Perf Analyzer. This could be due to requests falling on the edge of the observation/measurement window.

> @Tabrizian: Maybe we can clarify the difference between server request count and client request count in the perf analyzer docs?

I've created a ticket for this 👍.

**Comment by Jackiexiao** [comment]
thx
