### ISSUE TITLE
Questions about ragged batching of higher dimensional tensors

### ISSUE THREAD

**Issue by stengoes** [triton-inference-server/server#3951]
After reading the [ragged batching documentation](https://github.com/triton-inference-server/server/blob/main/docs/ragged_batching.md) a couple of things still remain unclear to me. 

The example provided is really quite helpful, but I would like to know how I can adapt it to my situation in which I have higher dimensional tensors. Let us say that, like the example in my situation I also send 3 requests but instead of sending shapes `[1, 3], [1, 4], [1, 5]` I have shapes `[1, 3, 32, 32, 1], [1, 4, 32, 32, 1], [1, 5, 32, 32, 1]`. 

1. Is ragged batching of higher dimensional tensors like this supported? 
2. How will it then batch the examples? Will it concatenate the examples in the first (batch) dimension: `[12, 32, 32, 1]`? Or will it   concatenate and flatten all values into a big 1-dimensional tensor:  `[12*32*32*1]` and should I modify my model to reshape the ragged input tensor back to shape of `[12, 32, 32, 1]`?

**Comment by Tabrizian** [comment]
cc @GuanLuo

**Comment by GuanLuo** [comment]
The ragged batched input will be flatten to [-1]. In general, the current higher dimensional tensor using ragged batch can't be restored because there is no batch input that describes the shape of each ragged input. However, we are planning to add new batch input kind to capture the input shape so the model can use it to restore the ragged input.

However, if you know that only one of the dimension may vary for different request, you should be able to restore the shape with the existing batch input kinds, before we add the new batch input type.

**Comment by stengoes** [comment]
Thanks for your explanation @GuanLuo. 

I understand that the flattened input [-1] cannot be restored to a higher dimensional ragged tensor with any of the currently available batch_input kinds. But instead of introducing a new kind of batch_input you could also consider concatenating along the first dimension. Such that two examples `[a1, b, c, d] and [a2, b, c, d]` form a batch like `[a1+a2, b, c, d]` instead of flattening all the values into a big one dimensional tensor like `[(a1+a2)*b*c*d]`. Batch input would then only describe the partitioning of the first (ragged) dimension. So that with `BATCH_ACCUMULATED_ELEMENT_COUNT` the batch_input becomes `[a1, a1+a2]`.

Such a change would be fully backwards compatible to the current situation, with the added benefit of supporting ragged batching of higher dimensional tensors as long as the first dimension of every example is the only dimension that varies. Also it would stay very close to the actual meaning of ragged batching. Ragged batching technically means that first dimension of the batch (the batch dimension) is ragged. 

Or am I missing an important point here?

**Comment by GuanLuo** [comment]
I think your idea on using the existing batch input type will work with your specific use case, as I mentioned earlier, there is only 1 dynamic dimension in your case, so your model should be able to compute the value of that dimension even with the existing batch input type. But I would disagree that "batch_input becomes a tensor with values `[a1, a1+a2]` in case of `BATCH_ACCUMULATED_ELEMENT_COUNT`", as this changes the behavior. `BATCH_ACCUMULATED_ELEMENT_COUNT` is supposed to provide value based on the element count of the request, so it produces `[a1 * b * c * d, (a1 + a2) * b * c *d]` instead, but this doesn't invalidate your idea as you can calculate `a1` and `a2` by dividing by `b * c * d` which is known value.

**Comment by stengoes** [comment]
I understand and I solved it for my situation by changing the model like you said.

But in the second part of my post, I was suggesting a way to change the current behaviour of ragged batching to support ragged batching of higher dimensional tensors without needing to introduce a new kind of batch input.

**Comment by GuanLuo** [comment]
I agree that your suggestion can solve this particular higher dimensional tensor scenario with existing ragged batch expressiveness, but as you mentioned this is not the generic solution as it can't describe tensors with multiple variable dimensions properly. And since there is already the plan for adding the new kind of batch input, I would incline to keep the existing behavior and let the new batch input to address the multi-dimensional ragged batching.

**Comment by stengoes** [comment]
Ok thanks for sharing your insights and  plans for the future support of ragged batching of higher dimensional tensors.

I will close this issue now.
