### ISSUE TITLE
quantized model inference slow with Triton server than inference directly in python code

### ISSUE THREAD

**Issue by Jaeker0512** [triton-inference-server/server#4007]
**Description**
I have quantized my custom classification model base on `Roberta-base-12layers` and finally get the following Latency measures from different backend, the results looks good:
```
batch size = 1
seq_length = 128
device = GPU Tesla T4
```

> [Pytorch (FP32)] mean=9.66ms, sd=0.19ms, min=9.38ms, max=10.08ms, median=9.60ms, 95p=10.07ms, 99p=10.08ms
> [Pytorch (FP16)] mean=9.84ms, sd=0.25ms, min=9.77ms, max=12.27ms, median=9.80ms, 95p=9.93ms, 99p=10.01ms

> [ONNX (FP32)] mean=8.41ms, sd=0.70ms, min=7.92ms, max=10.01ms, median=8.08ms, 95p=10.00ms, 99p=10.01ms
> [ONNX (FP16)] mean=2.57ms, sd=0.07ms, min=2.40ms, max=3.10ms, median=2.57ms, 95p=2.62ms, 99p=2.63ms

> [TensorRT (FP16)] mean=2.54ms, sd=0.46ms, min=2.32ms, max=3.94ms, median=2.39ms, 95p=3.92ms, 99p=3.93ms
> [TensorRT (INT-8)] mean=1.98ms, sd=0.17ms, min=1.87ms, max=3.57ms, median=1.95ms, 95p=2.06ms, 99p=2.30ms

but after I deployed the `ONNX FP16 model` and `TesorRT model (both FP16 and INT-8 )` with Triton Server and then do stress test with `Jmeter` , the result showed that TensorRT INT-8 model is not faster than FP16 model:
```
batch size = 1
seq_length = 128
threads = 20
GPU utilization between 93%~95%
```

> Triton server with TensorRT INT-8 model, **throughput = 398.7/sec**
> Triton server with TensorRT FP16 model, **throughput = 399.1/sec**
> Triton server with ONNX FP16 model, **throughput = 363.3/sec**

I just wonder if the Triton Server has a "int8 inference" option and I didn't turn it on?

**Triton Information**
What version of Triton are you using?
`nvcr.io/nvidia/tritonserver:22.01-py3`
Are you using the Triton container or did you build it yourself?
using the Triton container

**configuration file**

```
name: "transformer_tensorrtQAT_model"
max_batch_size: 0
platform: "tensorrt_plan"
default_model_filename: "model.plan"

input [
{
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [-1, -1]
},
{
    name: "token_type_ids"
    data_type: TYPE_INT32
    dims: [-1, -1]
},
{
    name: "attention_mask"
    data_type: TYPE_INT32
    dims: [-1, -1]
}
]

output {
    name: "output"
    data_type: TYPE_FP32
    dims: [-1, 21]
}

instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]
```

**Comment by tanmayv25** [comment]
Looks like the bottleneck is not the compute infer inside the backend but within jmeter/triton http endpoint interaction.
Your latency values for the model are quite small. The total latency of response= `model compute + <some overhead>`

Using quantization can improve the model compute latency, but it will not improve the overhead, hence total response time might not see same level of improvements as the model compute. I am quite positive your jmeter might not be using the binary data extension of our http server. https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_binary_data.md. You can use this to reduce the overhead. 

However, I would strongly advice you to use [perf_analyzer](https://github.com/triton-inference-server/server/blob/main/docs/perf_analyzer.md) to benchmark these models on Triton. Perf Analyzer is already built with all these small optimizations built in. It also reports all the detailed perf components so that we can identify the bottlenecks and enable some features in Triton to obtain better perf.

> I just wonder if the Triton Server has a "int8 inference" option and I didn't turn it on?

Model quantization is internal to the TRT model engine and will be automatically utilized when such model is loaded in Triton.

**Comment by tanmayv25** [comment]
closing the issue because of the lack of activity,
