### ISSUE TITLE
Dynamically load multiple instances for the same model

### ISSUE THREAD

**Issue by DeriZSY** [triton-inference-server/server#4020]
When using explicit mode for model control, seems like the number of instances created for a model is decided at loaded. 
And we would need to unload the existing model, modify the config, and reload it if we need to adjust the number of instances loaded.

Can such operation be implemented easier, for example, we can load an instance of a model while another instance of the same model is already loaded and running? It's quite necessary for application with dynamic scaling.

**Comment by GuanLuo** [comment]
Currently this kind of scaling needs to be done in the way you mentioned, however, you don't need to explicitly unload the model first, instead, you just modify the model config and the load operation will reload the model appropriately. In this way, there will not be downtime of the model as the previous created instances will only be replaced when the new instances are fully loaded.

And with the new model API extension (https://github.com/triton-inference-server/server/pull/3946, [updated doc](https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md#load)), the config modification can be done within the load API call (Triton uses this config instead of the one in the model directory), which simplify the action to be in one step.

**Comment by DeriZSY** [comment]
Thanks for the reply, my problem is solved! @GuanLuo
