### ISSUE TITLE
Permission denied message

### ISSUE THREAD

**Issue by letmerecall** [triton-inference-server/server#4030]
**Description**
If we build an image using `nvcr.io/nvidia/tritonserver:22.02-py3` as the base image, we get a 'permission denied' message when trying to run anything with a non-privileged user.

<img width="903" alt="Screenshot 2022-03-09 at 11 56 24 PM" src="https://user-images.githubusercontent.com/19938474/157514270-63323a5d-4bee-4b7c-bb0a-a8d19c50e78d.png">

After digging a bit, the root cause of this behaviour seems to be in `/opt/tritonserver/nvidia_entrypoint.sh` inside the container. 
There's a `find` command in a `if` statement  in line 46 (`if [[ "$(find -L /usr -name libcuda.so.1 | grep -v "compat") " == " " || "$(ls /dev/nvidiactl 2>/dev/null) " == " " ]]; then`), which if ran by a non-privileged user, gives a permission denied message.

The reason being that `find` command searches all the files in `/usr` directory, & symlink `/usr/lib/ssl/private -> /etc/ssl/private` got a restricted access.

**Triton Information**
Using an image which was built using `nvcr.io/nvidia/tritonserver:22.02-py3` as base image.

**To Reproduce**

1. Create a `dockerfile`
```dockerfile
FROM nvcr.io/nvidia/tritonserver:22.02-py3

# Create a non-privileged user
RUN useradd worker
USER worker

CMD ["python3"]
```
2. Build an image

```
docker build -f dockerfile -t ttsp:v1 .
```

3. Spin up a docker container.

```
docker run --rm -it ttsp:v1 
```

<img width="903" alt="Screenshot 2022-03-09 at 11 56 24 PM" src="https://user-images.githubusercontent.com/19938474/157507368-bb0ca609-c8d1-4fbf-a16d-6eace5ac3973.png">

**Expected behavior**

There should be no messages like `find: '/usr/lib/ssl/private': Permission denied`, or a way to manually control the level of information user wants to see. These messages might be misleading and user may think something is wrong with their setup.

**Comment by rmccorm4** [comment]
Hi @letmerecall, we have recently updated the entrypoint scripts used in the Triton containers: https://github.com/triton-inference-server/server/pull/3983

I believe the next release 22.03 will contain these changes and may solve this issue you're seeing, as checking for `libcuda.so` looks to be done via `ldconfig` and `LD_LIBRARY_PATH` now in the new entrypoint scripts. I don't believe this requires the escalated privileges.

If you need a short term workaround, you can try overriding the `--entrypoint` of the container with a modified version of the entrypoint script. Otherwise, please wait until the next release to see if the issue persists.

**Comment by rmccorm4** [comment]
Closing this for now. Please reopen or reference if still an issue in 22.03
