### ISSUE TITLE
Onnx batchsize greater than 1

### ISSUE THREAD

**Issue by phanxuanphucnd** [triton-inference-server/server#4048]
Hello there, converted a ir50 model .pt to onnx with dummy_input=(1, 3, 112, 112) model was generated successfully. 
```
# Export the model
    torch.onnx.export(
        network,
        dummpy_input,
        out_path,
    )
```
When config.pbtxt with max_batch_size = 0 -> OK

```
name: "ir50_onnx"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
max_batch_size: 0
input [
    {
        name: "input.1"
        data_type: TYPE_FP32
        dims: [3, 112, 112]
        reshape: { shape: [1, 3, 112, 112 ] }
    }
]
output [
    {
        name: "559"
        data_type: TYPE_FP32
        dims: [512]
        reshape: { shape: [1, 512 ] }
    }
]
instance_group [
    {
      count: 4
      kind: KIND_GPU
      gpus: [ 0 ]
    }
 ]


```

When max_batch_size=8: ->  Poll failed for model directory 'ir50_onnx': model input has different size for dims and reshape for ir50_onnx

```
name: "ir50_onnx"
platform: "onnxruntime_onnx"
backend: "onnxruntime"
max_batch_size: 8
input [
    {
        name: "input.1"
        data_type: TYPE_FP32
        dims: [3, 112, 112]
        reshape: { shape: [-1, 3, 112, 112 ] }
    }
]
output [
    {
        name: "559"
        data_type: TYPE_FP32
        dims: [512]
        reshape: { shape: [-1, 512 ] }
    }
]
instance_group [
    {
      count: 4
      kind: KIND_GPU
      gpus: [ 0 ]
    }
 ]


```

how to setup to max_batch_size=8 ? please helpme. thanks all

**Comment by dyastremsky** [comment]
Take a look at the documentation for Reshape here: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#reshape

You'll notice that the batch size acts as an extra dimension when max_batch_size > 0. So your input dimensions are [batch_size, 3, 112, 112]. I don't believe you need the Reshape, since that's what your model is expecting. Reshape would try to turn each individual input from [3, 112, 112] to [-1, 3, 112, 112]. I believe you might be able to fix the above issue by switching it to [1, 3, 112, 112], but then your model would receive an input of [batch_size, 1, 3, 112, 112], which I don't think is what you want.

Let me know if the above fixes your issue. You'll need to do the same with your output.
