### ISSUE TITLE
Post Processing with Triton Ensemble

### ISSUE THREAD

**Issue by dominusLabs** [triton-inference-server/server#4104]
Hi

We noticed that our YoloV4/TensorRT engine when being used with Triton returns ~1.4MB of data in the response. We're noticing very high latency in the overall inference process (another issue, raised [here](https://github.com/triton-inference-server/server/issues/4079)) , and are looking to cut down the response being sent back. 

We only need the labels and the confidence scores being returned, and have implemented getting that information  in our client script. However, we're hoping to move that post processing from the client to the server, in hopes of lowering the response body size, and thus lowering latency. We already have pre-processing implemented via an ensemble model (similar to that in the example, modified to our use case) and are hoping to do something similar with post-processing. Is there any example of documentation that would help in doing this?

Thanks

**Comment by deadeyegoodwin** [comment]
We don't have an explicit post-processing example, but it operates the same as pre-processing. You need to create a post-processing model that takes the Yolo output and produces the output you want, and then add that model to the ensemble. You can also consider using BLS instead of ensemble: https://github.com/triton-inference-server/python_backend#business-logic-scripting
