### ISSUE TITLE
inference failed: PyTorch execute failure: Global alloc not supported yet

### ISSUE THREAD

**Issue by Michelvl92** [triton-inference-server/server#4112]
**Description**
Running inference of a TorchScript model build with:  torch.jit.script() also in the 22.02 docker

**Triton Information**
22.02

Using the Triton container

**Comment by dyastremsky** [comment]
Can you please fill out the bug report template? We need to be able to reproduce your bug to see what is happening. See template below. If there are any pieces you cannot provide, like your model, we need a sample model that reproduces the bug.

--

**Description**
A clear and concise description of what the bug is.

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
A clear and concise description of what you expected to happen.

**Comment by deadeyegoodwin** [comment]
Closing, reopen with required template information.
