### ISSUE TITLE
Not able to use S3 bucket as a model storage 

### ISSUE THREAD

**Issue by sanjay-k598** [triton-inference-server/server#4165]
I'm get an error while running triton server to use AWS S3 bucket to load my models from.

**Triton Information**

using triton server version 2.6.0 

I'm using the triton container provided by Nvidia 

**To Reproduce**
Steps to reproduce the behavior.
1. CREATE S3 bucket with the model.onnx file inside.
2. Create a folder named .aws under home directory of container and add below files to store the AWS access keys and region details.

~/.aws/config
[default]
region=us-west-2
output=json

~/.aws/credentials
[default]
aws_access_key_id=AKIAIOSFPDNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAPPLEQQ

3. RUN TRITON WITH COMMAND:

docker run --rm -p 8004:8004 -p 8005:8005 -p 8006:8006 -v/home/sanjay/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.12-py3 tritonserver --model-repository=s3://triton-models-poc

ERROR MESSAGE: 

I0405 20:00:10.997255 1 server.cc:212] No server context available. Exiting immediately.
error: creating server: Internal - Could not get MetaData for bucket with name triton-models-poc
E0405 20:00:11.055936 1 cuda_memory_manager.cc:66] Failed to finalize CUDA memory manager: [3] CNMEM_STATUS_NOT_INITIALIZED

What other steps be followed to configure triton server to establish connection with S3 bucket and load models ?

Is there any way to test if the triton server is really able to connect and read S3 bucket ?

Many Thanks....
Sanjay

**Comment by tanmayv25** [comment]
We have a test in our CI that tests triton with S3 storage model repository: https://github.com/triton-inference-server/server/blob/main/qa/L0_storage_S3/test.sh

That being said there are a couple of issues with your invocation:
1. You should add `--gpus all` to your docker invocation so that triton can access the GPUs. Looks like your mode is configured to run on GPU.
2.  `-p 8004:8004 -p 8005:8005 -p 8006:8006` ->  `-p 8000:8000 -p 8001:8001 -p 8002:8002`. Triton by default uses these ports for its service. Read here for more information: https://github.com/triton-inference-server/server/blob/main/docs/quickstart.md#run-on-system-with-gpus

As far as original issue that you have pointed, I think there is some problem in your bucket configuration that is not allowing triton to connect with it. I guess you already have taken a look [here](https://github.com/triton-inference-server/server/blob/main/docs/model_repository.md#s3) and  are setting proper credentials properly.
@CoderHam can you take a look on what he might be missing?

**Comment by SanjayDT4o** [comment]
@tanmayv25 Thanks! for your suggestions.


- I'm  not using any GPU based machine so I didn't add "--gpus all".
- Now I have executed the below command..

docker run --rm -p 8000:8000 -p 8001:8001 -p 8002:8002 -v/home/sanjay/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:20.12-py3 tritonserver --model-repository=s3://triton-models-poc [ S3bucket where my model file is located ]

- I get below **ERROR LOGS**:

E0406 04:31:18.792248 1 model_repository_manager.cc:145] Failed to determine modification time for 's3://triton-models-poc/cbam_onnx/1/model.onnx': Internal: Failed to get modification time for object at s3://triton-models-poc/cbam_onnx/1/model.onnx
E0406 04:31:18.945892 1 model_repository_manager.cc:145] Failed to determine modification time for 's3://triton-models-poc/cbam_onnx/cbam_labels.txt': Internal: Failed to get modification time for object at s3://triton-models-poc/cbam_onnx/cbam_labels.txt
E0406 04:31:19.101263 1 model_repository_manager.cc:145] Failed to determine modification time for 's3://triton-models-poc/cbam_onnx/config.pbtxt': Internal: Failed to get modification time for object at s3://triton-models-poc/cbam_onnx/config.pbtxt
E0406 04:31:19.292726 1 model_repository_manager.cc:1682] File does not exist at s3://triton-models-poc/cbam_onnx/config.pbtxt
I0406 04:31:19.293215 1 server.cc:490] 

**ERROR MESSAGES:** 

I0406 04:31:19.294038 1 server.cc:215] Waiting for in-flight requests to complete.
I0406 04:31:19.294129 1 server.cc:230] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
E0406 04:31:19.355211 1 cuda_memory_manager.cc:66] Failed to finalize CUDA memory manager: [3] CNMEM_STATUS_NOT_INITIALIZED


From the above logs I could understand that the triton is able to read all the files under the S3 bucket  but fails to load the model file into triton server. Could this be the issue with specific S3 bucket path I'm mentioning in the docker command ?

Thanks!!

**Comment by CoderHam** [comment]
@sanjay-k598 can you try the same with a newer version of Triton (22.01 onwards)? There were some fixes made to S3 support including https://github.com/triton-inference-server/server/commit/806da77081a424fd00513ede4ed3603016785418

**Comment by Revist** [comment]
I have the same problem:

`docker run --gpus 1 --rm -p8000:8000 -p8001:8001 -p8002:8002 nvcr.io/nvidia/tritonserver:22.03-py3 tritonserver --model-repository=s3://s3.eu-de.cloud-object-storage.appdomain.cloud/triton-models-directory`

the bucket s3.eu-de.cloud-object-storage.appdomain.cloud/triton-models-directory is publicly available and i still get error

`I0414 11:45:42.267265 1 server.cc:249] No server context available. Exiting immediately.
error: creating server: Internal - Could not get MetaData for bucket with name s3.eu-de.cloud-object-storage.appdomain.cloud due to exception: , error message: No response body.`

**Comment by tanmayv25** [comment]
@Revist Are you using Triton version 22.01 or up?

**Comment by CoderHam** [comment]
@Revist please refer to the docs for [model repository](https://github.com/triton-inference-server/server/blob/main/docs/model_repository.md#s3). When using private / local S3 you need to use both host and port

Example 
````
$ tritonserver --model-repository=s3://https://host:port/bucket/path/to/model/repository ...
````

**Comment by Revist** [comment]
```
docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 nvcr.io/nvidia/tritonserver:22.03-py3 tritonserver --model-repository=s3://https://s3.eu-de.cloud-object-storage.appdomain.cloud:443/triton-models-directory```

```
docker run --rm -p8000:8000 -p8001:8001 -p8002:8002 -e AWS_ACCESS_KEY_ID=xxxxx -e AWS_SECRET_ACCESS_KEY=yyyyy nvcr.io/nvidia/tritonserver:22.03-py3 tritonserver --model-repository=s3://https://s3.eu-de.cloud-object-storage.appdomain.cloud:443/triton-models-directory```
