### ISSUE TITLE
Tritonserver Log: model-level grading

### ISSUE THREAD

**Issue by zhaotyer** [triton-inference-server/server#4213]
**Is your feature request related to a problem? Please describe.**
Currently, The logs of all models are printed together and it is difficult to distinguish，If there are many models, it will be difficult to locate the problem of a certain model.

**Describe the solution you'd like**
The log of each model is separated or the model information (like the model name) is automatically output in the log

**Describe alternatives you've considered**
The information of the model in the inference can be brought into the log

**Comment by CoderHam** [comment]
@zhaotyer can you elaborate what parts of the logging you would like to include the model name in?

Do you care for the model instance or just the model name itself?

**Comment by zhaotyer** [comment]
@CoderHam Thank you for your reply
I start up a object detection model and a classification model, then inference with these two models, I got the following log information，The output log information is not clear which inference of the two models is.

![sendpix0](https://user-images.githubusercontent.com/89376832/163535375-463f2fcb-fb00-4978-a269-c3379a94512a.jpg)

Hope to have the following functions：
1.Different model inference information can be clearly distinguished
or
2.Provides an api to obtain log information related to a model， like:/v2/models/([^/]+)(?:/versions/([0-9]+))?(?:/(infer|ready|config|stats|trace/setting)

**Comment by dyastremsky** [comment]
Thank you for submitting this feature request, @zhaotyer. We merged this ticket to add request ID logging here: https://github.com/triton-inference-server/server/pull/4484

That should be more precise than model logging, as you know the exact request the log is associated with. Since you know the request, you also know all the request-specific data, such as the model you sent that request to. This will be included in our next release.

I'm going to close this ticket. Please reopen it if you have any questions or this didn't resolve your needs.

**Comment by dyastremsky** [comment]
No, there is not. You would need to open an issue covering that as a feature request. I'd recommend being specific with your use case or where you want them logged though. The logs come from many places in the code, as it would likely not make sense to output them everywhere (e.g. in the lines listing models loaded).
