### ISSUE TITLE
how multiple instances on the same device can be concurrent

### ISSUE THREAD

**Issue by FreshZZ** [triton-inference-server/server#4319]
After reading the code, I was confused about how multiple instances on the same device can be concurrent

Multiple instances on the same device share a TritonBackendThread object,
in src/backends/backend/triton_model_instance.cc
<img width="658" alt="图片" src="https://user-images.githubusercontent.com/17643609/166084995-4f1b09d7-1b48-457c-8b52-84c2e96940b9.png">

model_instances_ save all instances on this device
<img width="561" alt="图片" src="https://user-images.githubusercontent.com/17643609/166085006-29bb74e5-1e54-45df-ab01-f669815d461c.png">

In the function,  TritonModelInstance::TritonBackendThread::BackendThread,
<img width="648" alt="图片" src="https://user-images.githubusercontent.com/17643609/166085014-feb2493c-3fbb-47d9-b42d-e5c0d7a8b952.png">

**My question is**, if there are two instances of model x,  A and B   on device 0
`model_->Server()->GetRateLimiter()->DequeuePayload(model_instances_, &payload);  `Obtain the payload and assume   instance A is assigned to the payload,  then, 'payload->Execute()', start to forward(),

 **instance B cannot be assigned payload and execution until the instance A is completed?**

**Comment by rmccorm4** [comment]
CC @tanmayv25

**Comment by tanmayv25** [comment]
@FreshZZ  Thanks for asking this question. The backend thread sharing is only implemented in case of using GPU instance and with device_blocking execution policy enabled by the backend. See this line: https://github.com/triton-inference-server/core/blob/main/src/backend_model_instance.cc#L314-321
If device_blocking is set false then each TritonModelInstance will create its own `triton_backend_thread_`. Hence achieve full concurrency. 

See here how Triton core detects that backend has device_blocking execution policy set: https://github.com/triton-inference-server/core/blob/main/src/backend_model.cc#L175-L185

Read more about Device blocking execution policy here: https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonbackend.h#L781-L794

The behavior of a backend requesting device blocking execution policy is as per what you observed. At present only[ TensorRT backend](https://github.com/triton-inference-server/tensorrt_backend) uses the Device Blocking execution policy. This is because the execution itself is asynchronous. The implementation of backend is such that even if using only a single backend thread, the backend is able to run mulitple inference requests concurrently.

**Comment by rmccorm4** [comment]
Closing per Tanmay's response, please feel free to re-open if this didn't answer your question.

**Comment by FreshZZ** [comment]
@tanmayv25 Thank you so much

**Comment by lileilai** [comment]
@tanmayv25 Does this mean only TensorRT backend supporting concurrent request to exected in multiple instances on the same device ?

**Comment by tanmayv25** [comment]
No. The other backends have per instance threads issuing inference requests for their own instances. Hence, the concurrency is gained there by the way of threading. 
TensorRT backend provides better performance when using a single thread as it minimized the thread contention.

In summary,
Other backends: multiple threads, single synchronous call
TensorRT Backend: Single thread, multiple asynchronous calls

**Comment by lileilai** [comment]
> No. The other backends have per instance threads issuing inference requests for their own instances. Hence, the concurrency is gained there by the way of threading. TensorRT backend provides better performance when using a single thread as it minimized the thread contention.
> 
> In summary, Other backends: multiple threads, single synchronous call TensorRT Backend: Single thread, multiple asynchronous calls

Thanks for your reply

**Comment by Yashupadhyay13** [comment]
@tanmayv25 i am trying to have multiple onnx instances on same gpu, but it seems the inference is not happening concurrently.

name: "model"
backend: "onnxruntime"
dynamic_batching {
}
parameters: {
key: "INFERENCE_MODE"
value: {string_value: "true"}
}
parameters: {
key: "ENABLE_NVFUSER"
value: {string_value: "true"}
}

instance_group [
{
count: 16
kind: KIND_GPU
}
]

input [
{
name: "input1"
data_type: TYPE_INT64
dims:[-1]
}
]
output [
{
name: "out1"
data_type: TYPE_FP32
dims: [ -1]
}
]
output [
{
name: "out2"
data_type: TYPE_INT64
dims: [ -1 ]
}
]

this is the config.pbtxt that i am using

**Comment by tanmayv25** [comment]
> but it seems the inference is not happening concurrently.
 
 How are you observing the concurrency? Are you sending sufficiently concurrent requests to the server to saturate all 16 model instances?
