### ISSUE TITLE
A few questions on C++ API

### ISSUE THREAD

**Issue by InfiniteLife** [triton-inference-server/server#4353]
I have a couple of questions, hope someone will help:

1. After making a call to
```
Error AsyncInfer(
      OnCompleteFn callback, const InferOptions& options,
      const std::vector<InferInput*>& inputs,
      const std::vector<const InferRequestedOutput*>& outputs =
          std::vector<const InferRequestedOutput*>(),
      const Headers& headers = Headers(),
      grpc_compression_algorithm compression_algorithm = GRPC_COMPRESS_NONE);
```
I can call `input_ptr->reset()` immediately, not waiting for function callback?

2. Doing multiple calls to  `AsyncInfer` or` Infer` in multiple threads I can pass the same instance of  `const std::vector<const InferRequestedOutput*>& outputs` as its only used to describe outputs and does not affect memory allocation for returned `result`? Or should it be different instances?
3. Is it costly to  call `tc::Error err = tc::InferInput::Create(&input, input_names[0], input_shapes[0], input_datatype[0]);` during each inference request? I want to make flexible amount of batched inference request in different threads, I can pre-allocate inputs but it will be complex solution, so Im wondering if I can call `::create` function before each batched inference request. But I dont know how heavy this call for system is.

**Comment by tanmayv25** [comment]
1. Yes if you are using gRPC client library. No if you are using HTTP client. The restriction on HTTP is documented [here](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/http_client.h#L485-L488).
In case of gRPC, all the information from the InferInput is already extracted into a gRPC request protobuf message when returning from AsyncInfer.

2. Typically you can use the same InferRequestedOutput object. But if you are [SetSharedMemory](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/common.h#L391-L400) on the object, then you must use separate objects, otherwise all the infer calls will write data on the same memory region.

3.  It should not be too costly to call InferInput::Create() as it just creates a structure to hold the name, datatype and shape. However, creating and destroying any objects on **time-critical path** would incur a performance cost. If it does then, I would advice to pre-allocate few of these objects in a pool. Then use Reset, AppendRaw, SetSharedMemory or AppendFromString. You can also use SetShape if you want to override the shapes with each request.

**Comment by InfiniteLife** [comment]
Thank you! That answers it.
