### ISSUE TITLE
Response cache is not working well

### ISSUE THREAD

**Issue by danielwonght** [triton-inference-server/server#4379]
**Description**
I turned on the response cache by setting the config as _response_cache {enable: True}_. When the request input is repeatedly the same, everything goes alright and the Inference/second can reach 25000++ while the concurrency is set to 3 (by using **Performance Analyze**).[1] But, when the input is randomly generated for each input, the performance of the Triton server is getting worse along the time from 600 inference/second down to 100 inference/second.[2] It's like the server spends increasingly more time on dealing with LRU cache stuff.
[offical instruction](https://github.com/triton-inference-server/server/blob/main/docs/response_cache.md) shows that _"Only input tensors located in CPU memory will be hashable for accessing the cache"_. My model is deployed using GPU. According to [1], I think, the cache is working, but not in the right way, proven by [2].

**Triton Information**
What version of Triton are you using?
v2.17.0 (with container version 21.12)

Are you using the Triton container or did you build it yourself?
Triton container.

**To Reproduce**
Steps to reproduce the behavior.
1. Download a whatever BERT pre-trained model.
2. Convert the model into onnx format by using _torch.onnx.export_.
3. Deploy by the Triton server.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

> name: "bert"
> platform: "onnxruntime_onnx"
> max_batch_size : 8
> input [
>   {
>     name: "input_ids"
>     data_type: TYPE_INT64
>     dims: [ -1 ]
>   },
>   {
>     name: "token_type_ids"
>     data_type: TYPE_INT64
>     dims: [ -1 ]
>   },
>   {
>     name: "attention_mask"
>     data_type: TYPE_INT64
>     dims: [ -1 ]
>   }
> ]
> output [
>   {
>     name: "pooler"
>     data_type: TYPE_FP32
>     dims: [-1]
>   }
> ]
> dynamic_batching {}
> instance_group [
>     {
>         count: 1
>         kind: KIND_GPU
>         gpus: [ 0 ]
>     }
> ]
> response_cache {
>   enable: True
> }

**Expected behavior**
Ideally, the **Response Cache** may affect the model performance subtly, when the input is varying all the time.

**Comment by rmccorm4** [comment]
Hi @danielwonght ,

Thanks for reporting this. I haven't had a chance to fix this yet, but I am aware of an issue where we are [attempting to insert](https://github.com/triton-inference-server/core/blob/db2ae826116aac376467eb86f352dcdf95c08622/src/dynamic_batch_scheduler.cc#L613-L624) (and failing + logging) into the cache even if we know we couldn't hash the inputs (i.e. GPU tensors). I will follow up on this issue once this is fixed and ask to see if you notice improved performance for the scenario you described. 

However, as you described, the cache does not support GPU tensors at the moment, so you would not see benefits from the cache for this model. Similarly, it is intended for use cases with lots of duplicate requests as you described, so if you know your use case will see consistently different/random inputs, then you would also not want to incur the cache management overhead.

**Comment by rmccorm4** [comment]
Hi @danielwonght,

The issue I mentioned where we attempt to insert into the cache even if we couldn't hash the request (request too large, input data in GPU memory, etc.) should be fixed by the PR above. 

However, after reading your issue again I'm not so sure if it will actually resolve your performance degradation. The issue I described related to GPU tensors would be if the input data is coming from GPU memory, but even if a model is deployed on GPU and may use the GPU for internal operations, the first input to the model can still be coming from CPU memory and can therefore be cached. This is evident from your comment below showing the cache was actualy being used :
> When the request input is repeatedly the same, everything goes alright and the Inference/second can reach 25000++

Out of curiosity, what was the `--response-cache-byte-size` you allocated for your test? If you have a small cache size and send lots of random/unique requests with high throughput, the cache will constantly be getting evicted and updated in order to insert new requests. I'm not sure there is necessarily an actionable issue here, it could just be that the cache is not right for your use case or that you are not allocating enough size for it to store a meaningful number of requests without constantly requiring eviction. You may want to try evaluating the performance at various cache sizes (even for random requests) and see if there are noticeable differences at certain thresholds.

**Comment by danielwonght** [comment]
Hi @rmccorm4 ,

The issue I raised above might not be solved by this PR. I think the caching function is working in this case, as I mentioned

> the Inference/second can reach 25000+ when the request is not changing. 

The input must be cached in some way. I think your saying is correct:

> In fact, when using the HTTP or GRPC endpoints, the requests/responses will be in CPU memory by default.

 However, when the input was constantly changing, the performance was degraded in comparison with the performance where I turned off the _Reponse Cache_. 

By the way, I set --response-cache-byte-size to 2G bytes. The purpose of my sending random requests is to find to what extent the performance will be affected by using the _Reponse Cache_ (There is additional actions like looking up and inserting the input to memory).

**Comment by Tabrizian** [comment]
@rmccorm4 any updates on this issue? Has this been fixed as a result of PR above?

**Comment by rmccorm4** [comment]
Hi @danielwonght ,

We don't have any current plans to investigate this perf degradation at this time as the cache is intended to be use-case specific for scenarios expecting some degree of cache hits.

However, if you could share some of your investigation results, and how you are recording the performance over time, etc. - that would be helpful for looking into this in the future.
