### ISSUE TITLE
triton image classification example client http memory leak

### ISSUE THREAD

**Issue by IdoGabay111** [triton-inference-server/server#4509]
**Description**
answer:
I'm using a modified version of the triton client image classification example (the one published on may 4th).
I run the .py file in a docker container with http request to triton which is in another container.
the memory leak happend about once every 30 seconds and it's about 300Mb of memory that is added all in a span of 5 seconds and than maintain the new size for about 20 seconds and repeat.
i know the memory leak doesn't is not related to other proccesses because when i use grpc i don't get memory leak.

**Triton Information**
What version of Triton are you using?
21.08

Are you using the Triton container or did you build it yourself?
I'm using the Triton container.

**To Reproduce**
Steps to reproduce the behavior.
changes i did : insert all the main in the example to a function so i can call it from another .py function. i also send PIL image through this function call instead odf getting the image from url in the example.
another change is that i return the results instead of returning "PASS".

i think the main difference is that i dont open new python process every request with the triton client so i can work in real time.
in this method ican get up to 30 fps vs 4 fps if i use the method in the example that I need to reopen python process every request.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

framework : pytorch
model : resnet50
input : a PIL image in size 640x480 (i'm sending one image in a batch)
output : dictionary of the results.

**Expected behavior**

triton cluent works with out open new process every request without memory leak.

[cups_labels.txt](https://github.com/triton-inference-server/server/files/8871162/cups_labels.txt)

**Comment by dyastremsky** [comment]
Can you try running your code in a more recent container, such as 22.05, and see if the error is present in the current version of Triton? The Triton client version shouldn't make a big difference, but using the client version that corresponds to your server will help remove the possibility of any version incompatibility.

If you are still seeing a memory leak in 22.05, please let us know with reproduction instructions. Specifically, the commands and code to reproduce the leak step-by-step so that we can investigate it on our end.

**Comment by Tabrizian** [comment]
Closing due in-activity.
