### ISSUE TITLE
Triton's resource consumption

### ISSUE THREAD

**Issue by Alxgreenlight** [triton-inference-server/server#4531]
Hello, we are using Triton inference server in cpu-only mode with python-backend model. Server is deployed with Kubernetes on kluster. We noticed that depending on the CPU limits set by Kubernetes, the response time of the model changes noticeably. But actual cpu utilization is much less than the limits. By detail: actual utilization ~3-4 cpu, but response time higher when limit is set to 12 cpu compare with situation when limit is 40 cpu.
Could you please explain, how triton server consume cpu and why can limits settings affect performance while actual utilization is low?

**Comment by nv-kmcgill53** [comment]
Hi @Alxgreenlight are you able to provide some bench mark statistics from your observations? Could you also provide units of the cpu limits, are these 12m and 40m respectively? To answer with the available context, [you are specifying the amount of runtime the process is allowed](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes) using resource limits while the amount of computation needed (read instructions) to run the inference is relatively fixed. So what you are seeing is probably Triton getting a larger amount of time to execute on the CPU with the larger limits rather than the smaller limits.

There is the following answer [here](https://serverfault.com/questions/1065763/can-i-have-multiple-threads-running-in-parallel-in-a-pod-with-a-cpu-limit-set-to) which states k8s is using the [Quota subsystem](https://www.kernel.org/doc/html/latest/filesystems/quota.html) to slice computation time. 

>By detail: actual utilization ~3-4 cpu, but response time higher when limit is set to 12 cpu compare with situation when limit is 40 cpu.

Do you happen to know how often this metric is updated/ what the resolution of this metric is? Inferences look like computational spikes and if there is any averaging on the metric then the utilization might appear lower than what is happening.

**Comment by Alxgreenlight** [comment]
Hi
About resources: limits are 12000 mCPU and 40000 mCPU respectively
Metrics gathered with prometheus and shows actual cpu utilization. Currently model runs with almost constantly load about 30 RPS, and as it seen by graphs utilization is not more than 4000 mCPU
But as i understand from your answer, lower limit can constraint the number of threads running in parallel and thereafter it can affect the overall performance, thank you!
