### ISSUE TITLE
How can I send variable-length tensors as a batch in one request using Python APIs?

### ISSUE THREAD

**Issue by leanrdchen00918** [triton-inference-server/server#4582]
Hi!
I've set up an ensemble model (DALI for preprocessing + InceptionV3 for image classification) that takes encoded image in any size as input. It works well when I send only one image as np.ndarray(dtype=np.uint8) in the shape of (1, x) in my request. However, as my images represented in tensor vary in length, it seems I have to arrange them in a 2D tensor whose second dimension is indefinite (in my case the shape is (21, )) and assign dtype to object (now the model takes in TYPE_STRING rather than TYPE_UINT8). Then I run into this error:
`tritonclient.utils.InferenceServerException: unexpected shape for input 'INPUT' for model 'ensemble_dali_inception'. Expected [-1,-1], got [21]`
Is it because triton cannot take in irregular tensor like (n, )? Is there a way I can do this?

**Comment by Tabrizian** [comment]
The problem here is that you are missing one additional dimension when sending the input. The dimension of the input should be [1, 21] instead of [21]. If your model doesn't support batching you can set `max_batch_size` to zero and the additional dimension will no longer be required. However, if you want to leverage [dynamic batching](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#dynamic-batcher) feature you would need to add the extra dimension.
