### ISSUE TITLE
[question] performance comparison, ensemble vs. BLS

### ISSUE THREAD

**Issue by joongkyunKim** [triton-inference-server/server#4619]
**Description**
When the same logic is performed in ensemble and bls, there is a big difference in performance (tps), and bls is much slower. Looking for an existing issue, it seems to be due to the ipc overhead. right? If not, is there another reason?
In my opinion, bls, which requires less model request process, has less network overhead and was expected to be faster.
I cannot share the model file (for confidential), so please judge in a general situation.

**Triton Information**
nvcr.io/nvidia/tritonserver:22.05-py3
using triton container
tritonserver --model-repository=s3://triton-inference-poc/model_repository/ --log-verbose=1 --log-info=True --model-control-mode=poll --repository-poll-secs=10 --backend-config=python,shm-default-byte-size=536870912 --backend-config=python,shm-growth-byte-size=536870912

i set shm-default-byte-size to 512mb (quite large) 

**To Reproduce**
It is difficult to share the model and config.pbtxt
I implemented exactly the same process with ensemble and bls. The process is as below.

ensemble way)
image input ->  
preprocessing for face detection (python backend) -> 
face detection inference (onnx) -> 
postprocessing (python backend) ->
result output

bls way)
image input ->
business logic script (python backend)
 - preprocess 
 - face detection inference
 - postprocess

result output

In the ensemble method, the pre-processing, inference, post-processing part is composed of each model. 
In bls, pre-processing, inference and post-processing are carried out in one file(bls model.py), and the result of the detection model is requested/received in the bls file.

result summary
i used same locust script to calculate performance
- ensemble way
- - tps : 60 
- - gpu util : about 95%
- bls way
- - tps : 35
- - gpu util : about 50%

Is there any way to increase the performance of the bls method in this situation?

thank you in advance.

**Comment by krishung5** [comment]
Hi @joongkyunKim, for Python BLS, due to the limitation on Python interpreter, the Python model is run in separate process, and the tensors may need to be copied to the shared memory so that it is accessible to the other process. I think this overhead could be the reason why the performance of Python BLS is not as good as you expected. To get maximum performance of BLS, I would suggest you using custom C++ BLS backend, which uses in-process C-API and doesn't have the overhead mentioned above. Please refer to this example to see how to implement the custom BLS backend: https://github.com/triton-inference-server/backend/tree/main/examples/backends/bls
CC @Tabrizian

**Comment by Tabrizian** [comment]
@joongkyunKim Adding to what Kris mentioned, you may need to increase the number of instances for the BLS model to get better performance. [Model Analyzer](https://github.com/triton-inference-server/model_analyzer) now supports BLS as models so you might get closer to the performance of BLS.
