### ISSUE TITLE
question about batch mechanism

### ISSUE THREAD

**Issue by ggslayer** [triton-inference-server/server#4643]
Hi, recently, I'm using triton to do model infer, I heard that, batch can increase thoughout, about this, I have a lot of questions:

1. When I adjust the multi gpu instance more than 1( modify config.pbtxt), I can get the 100% gpu usage in the "nvidia-smi" cmd tool.
2. The "nvidia-smi" tool's gpu usage is real usage status?  if the usage is 100%, Is "batch" can increase gpu usage more?
3. If batch can increase gpu usage more, please give me some **paper** about batch mechanism, best include hardware/driver/framework's relation core mechanism, include tensor core exection sequencely? driver interface can concurrent call? and so on.

Thank you, please give me some paper about this, thank you very much.

**Comment by dyastremsky** [comment]
Yes, while nvidia-smi is a separate project, it should give you accurate usage. You can read more about nvidia-smi here: https://developer.nvidia.com/nvidia-system-management-interface

You're never going to go above 100% GPU usage. So the returns on batching may be marginal or negative in your case, since you're increasing the cost of data movement due to there being insufficient space to send over more data in a batch without moving it around. If you want to read our documentation, it's here: https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#models-and-schedulers. If you want to read research papers, those are beyond our documentation, so you'll have to search out the ones you're interested in. Batching is essentially combining your requests to allow for optimizations around data transfer and processing.

**Comment by ggslayer** [comment]
About "Batching is essentially combining your requests to allow for optimizations around data transfer and processing.", can you give me some detail info about this?  thank you very much!

**Comment by dyastremsky** [comment]
That's a very open-ended question. The documentation around the dynamic batcher may be helpful: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#dynamic-batcher

Also, all the code is open-source, so feel free to review the parts that are relevant to any questions for you. For example, the dynamic batch scheduler is here: https://github.com/triton-inference-server/core/blob/main/src/dynamic_batch_scheduler.cc
