### ISSUE TITLE
How to load plugin dynamically

### ISSUE THREAD

**Issue by leanrdchen00918** [triton-inference-server/server#4700]
My model(not ONNX) uses a plugin that is compiled as a .so file. According to [this](https://github.com/triton-inference-server/server/blob/70588801f5bf8b16b1117a26000c1b015d0059fb/docs/custom_operations.md), it's clear that I should set LD_LIBRARY_PATH when starting up triton server to make my model work.

However, the limitation here is that I have to specify the exact library to link to BEFORE start up. How can I load my model that uses a plugin AFTER I have invoked the server(without shutting it down and restarting it)?

**Comment by krishung5** [comment]
Hi @leanrdchen00918, unfortunately right now we cannot load those custom plugin/shared libraries at runtime. We can only specify LD_LIBRARY_PATH and LD_PRELOAD variables before starting up Triton. I have filed an enhancement ticket for this.
CC @GuanLuo

**Comment by GuanLuo** [comment]
Yes, `LD_PRELOAD` is the current way to load custom plugins / ops for most frameworks. To load plugin dynamically, it largely depends on whether the framework libraries expose features (like for ONNX), we will look into it as possible enhancement for the backends.

**Comment by dyastremsky** [comment]
We have added custom plugins for other backends like TensorRT. You can see how this was done [here](https://github.com/triton-inference-server/tensorrt_backend/pull/25).

I'm going to close out this ticket because it's quite general. The implementation would be different for each backend. If you need custom plugins implemented for a specific backend, please let us know.
