### ISSUE TITLE
Python backend shared codebase and code import

### ISSUE THREAD

**Issue by Vozf** [triton-inference-server/server#4728]
I would like for 2 python models to use the same function. How can this be achieved? Can I import the function from some kind of utils.py file or import functions from one model to another?

**Comment by tanmayv25** [comment]
You can write your own python module with the common functionality and store it in a common location.
Then make sure the path to your common python module is added to [PYTHONPATH](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) so that python interpreter can find this module.
You should be able to launch tritonserver with multiple models importing your common module.

cc @Tabrizian

**Comment by Vozf** [comment]
Thanks
