### ISSUE TITLE
Limit maximum nubmer of concurrent requests for triton server

### ISSUE THREAD

**Issue by Vozf** [triton-inference-server/server#4753]
Is there an option to limit maximum number of concurrent requests for a server? I've seen the rate limiter, but it seems it has different purpose

**Comment by dyastremsky** [comment]
Could you clarify the question a bit more? If you're asking about limiting the number of requests processed concurrently, that's already [controlled by the number of model instances you have](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#concurrent-model-execution) (in the base case; for the sequence batcher, there are also batch slots).

Any requests beyond that get put in the queue. Anything beyond that would have to be on the client side, such as the [timeout settings](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/examples/simple_grpc_infer_client.cc#L147) most of Triton's clients have. To my knowledge, Triton does not have a setting to set a maximum number of queued requests then return an error if another one tries to be scheduled.

**Comment by Vozf** [comment]
I'm talking about not placing the requests in the queue and just returning some kind of error from a server. So the queue wouldn't accumulate to some large sizes. For instance if we already have a queue of 10, do not accept any new requests for a queue

**Comment by dyastremsky** [comment]
Actually just checked, and it looks like you can set a maximum queue size: https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#queue-policy.

Let me see if I can find an example.

**Comment by dyastremsky** [comment]
That should work. The dynamic batcher just provides extra functionality over the default scheduler (which simply distributes request).

**Comment by Vozf** [comment]
Thank you, I will try it out

**Comment by dyastremsky** [comment]
Fantastic. I'll close this ticket. If you have further questions or issues, we can reopen it.

**Comment by Vozf** [comment]
Tried to do it with my ensemble and got. 
```
triton_1  | [libprotobuf ERROR /tmp/tritonbuild/tritonserver/build/_deps/repo-third-party-build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format i
nference.ModelConfig: 35:21: Field "ensemble_scheduling" is specified along with field "dynamic_batching", another member of oneof "scheduling_choice".                                                    
```
Can this be done with an ensemble? If not where should i place it? On the first model of ensemble?
Can't reopen the issue

**Comment by dyastremsky** [comment]
While ensemble models use the [ensemble scheduler](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#ensemble-scheduler), the individual models [can have dynamic batching enabled](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#ensemble-models). The documentation linked goes through it in more detail, but the ensemble scheduler essentially routes requests through models but the models themselves are individual models.

It's up to you whether you place this in your first model's config or all of them. You could only run it in your first model, but then there's nothing stopping a client from running additional requests to the other models standalone. On the flip side, placing it in all of them could also cause unwanted behavior. For example, if you have models A -> B in your ensemble, if someone runs 10 requests to B while you're running a request through the ensemble, then you'll receive an error after your request was already run through A due to the maximum queue count being reached for B.

**Comment by Vozf** [comment]
Thanks again
