### ISSUE TITLE
How long support of current backend API you are guarantee.

### ISSUE THREAD

**Issue by alxmamaev** [triton-inference-server/server#4782]
Im interesting in, how long you are guaranteed backend API backward compatibility. I mean, If I wrote a custom backend, how long I may be sure, that after the core/server/backend_api update, everything will still work (methods or some other APIs will be not removed)?

**Comment by dyastremsky** [comment]
It will work until the API major version is updated. It's currently still version 1, if that's an indication of how often we make non-backward-compatible changes. You can see the major version [here](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonbackend.h#L93). Similarly, you can find the major version of server [here](https://github.com/triton-inference-server/core/blob/main/include/triton/core/tritonserver.h#L93), which is also still on version 1.

I don't know whether we'll eventually need to upgrade to a major version of 2, but it's something we'd weigh very heavily due to user impact.

**Comment by dyastremsky** [comment]
Closing the ticket. If you have any more questions about this, let me know and I can reopen the ticket.
