### ISSUE TITLE
Check torchlib torch version

### ISSUE THREAD

**Issue by alxmamaev** [triton-inference-server/server#4806]
Im running `nvcr.io/nvidia/tritonserver:22.07-pyt-python-py3` on aarch64 and on x86, so i have a completely different output from PyTorch model. 

I guess that it is not a triton bug actually, probably different `torchlib` versions are used (at least one of them built for arm), so how i can check the version of torchlib, to compate them on x86 and arm biuld? And probably reproduce this bug separately from triton.

I see shared library in `backends/pytorch/libtorch.so`, but actually that has no version in the file like `backends/pytorch/libopencv_imgcodecs.so.3.4`.

**Comment by rmccorm4** [comment]
Per DLFW release notes, looks like it's the same for both x86 and ARM SBSA: https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html (see 22.07 column and PyTorch row in this case)

@mc-nv @nv-kmcgill53 any other thoughts on verifying underlying torch versions in x86 and ARM builds? 

I might expect different intermediate values across platforms for models using platform specific features, but I would expect the final outputs to generally be close. 

But otherwise, as you said, this is likely not specific to Triton and can probably be reproduced outside of Triton.

**Comment by alxmamaev** [comment]
Update:
I see, that you [copying torchlib from current pytorch install in conda](https://github.com/triton-inference-server/pytorch_backend/blob/bfbf7af9aa59788cdcafd28ebe5e6aab030b2e6b/CMakeLists.txt#L209).


PyTorch version is determined by building container in CMake parameter `-DTRITON_PYTORCH_DOCKER_IMAGE="nvcr.io/nvidia/pytorch:21.02-py3"` .


So now I can simplify my question: which docker version used to build arm64 and x86 container for the tritonserver:22.07-pyt-python-py3?

**Comment by alxmamaev** [comment]
@rmccorm4 Thanks! I see that version is `1.13.0a0+08820cb`.

Why you are not using stable release PyTorch versions? 
It's harder to reproduce, because you cannot just install it from the pip. You should build it your own or use nvidia-pytorch-container (which is not perfect solution sometimes)

**Comment by rmccorm4** [comment]
> It's harder to reproduce, because you cannot just install it from the pip. You should build it your own or use nvidia-pytorch-container (which is not perfect solution sometimes)

@alxmamaev Triton just takes the PyTorch version built for the corresponding `nvcr.io/nvidia/pytorch:YY.MM-py3` release so we are in alignment with the other DL framework containers.

ex: `nvcr.io/nvidia/pytorch:22.07-py3` should generally have the same pytorch version as `nvcr.io/nvidia/tritonserver:22.07-py3`

**Comment by alxmamaev** [comment]
@rmccorm4 ok, thank you. It's it is what I wanted. Will try to reproduce bug separately.
