### ISSUE TITLE
[QUESTION] What are Benefits of Using Backends?

### ISSUE THREAD

**Issue by alercelik** [triton-inference-server/server#4892]
Hello,

Are backends implemented for performance issues or just for compatibility? I have read quite a bit of documentation but could not find satisfying answers for those questions. 

In case of using a single PyTorch model in a single GPU, does Triton Inference Server have any advantages? I am excluding features like model repository & versioning. In other words, is there a benefit of using a dedicated PyTorch backend with Triton instead of serving the model using bare PyTorch without Triton?

**Comment by dyastremsky** [comment]
I believe this is two different questions. Triton server needs to have a backend for your model, with each backend providing different logic and functionality. For example, the ONNXRuntime backend is usually the preferred backend for ONNX models, Python backend has a lot of flexibility with features like Business Logic Scripting, FasterTransformer runs large models that require multiple nodes and GPUs to run, etc.

As far as your question about whether to use Triton for a single model on a single GPU, that depends on what you need. The PyTorch backend will use PyTorch for execution. However, Triton makes a lot of things easy and accessible for users, such as optimized execution, inference mode, weight sharing (for multiple model instances), shared memory, dynamic batching, and more. There are also other Triton tools like Model Analyzer that can help you find the best configuration for your model. So while you could run on bare PyTorch, Triton provides additional features and options that could be beneficial when running your models.

**Comment by alercelik** [comment]
Hello dyastremsky,

Thanks a lot for the detailed explanation, it was very helpful. 

I also would like to add that I was not able to find a documentation telling weight sharing feature in docs but found in pull requests. Is this feature only for PyTorch? Does TF, ONNX or TRT use this feature as well?

**Comment by dyastremsky** [comment]
Any time! The documentation can be spread out due to all the features. For PyTorch, it's available in the README for the PyTorch repo: https://github.com/triton-inference-server/pytorch_backend

Weight sharing is dependent on whether the framework supports it. It's listed in the PyTorch documentation because it should only be used with models that are not stateful, so the user can choose to enable/disable it. However, it is one of the optimizations that we do under-the-hood where possible. Specifically, the TensorRT backend supports it as well. I don't believe the others do.

**Comment by alercelik** [comment]
Thanks for the explanations.
