### ISSUE TITLE
Grpc_serve unable to handle Java client UINT32 requests

### ISSUE THREAD

**Issue by zhyajie** [triton-inference-server/server#4917]
**Description**
When I set the input data type of the model to INT32, the request can be accessed normally using the python client. Using the Java client will result in a Server parsing model input error.
**Bug**
I checked the Triton server code and thought there [grpc_server.cc:3402](https://github.com/triton-inference-server/server/blob/main/src/grpc_server.cc) might be a bug, I hope to confirm.
why input type equal  TRITONSERVER_TYPE_UINT32,the code is io.contents().int_contents().data() instead of 
 io.contents().uint_contents().data()

**Comment by jbkyang-nvi** [comment]
The issue you have seem to be a client error instead of a server error. Some questions
1. You mean you are seeing the issue when you set datatype to *UINT32* instead of *INT32* right?
2. What is the error you are seeing when using the Java client?
3. Can you provide the Python code and the Java client code?
