### ISSUE TITLE
Missing doc for `platform`

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [triton-inference-server/server#4937]
Hi guys,

There is no doc about the correct value for `platform`, only this [matrix](https://github.com/triton-inference-server/backend/blob/main/docs/backend_platform_support_matrix.md) this is quite boring since I have no idea about what I am allow to put in `platform`. In your example you have `tensorrt_plan`, why? What is `plan`?

Thanks

**Comment by dyastremsky** [comment]
Hi Francesco! Thanks for letting us know. Under that example, there should have been a link here: https://github.com/triton-inference-server/backend/blob/main/README.md#backends

`A Triton backend is the implementation that executes a model. A backend can be a wrapper around a deep-learning framework, like PyTorch, TensorFlow, TensorRT, ONNX Runtime or OpenVINO. A backend can also implement any functionality you want as long as it adheres to the [backend API](https://github.com/triton-inference-server/backend/blob/main/README.md#triton-backend-api). Triton uses this API to send requests to the backend for execution and the backend uses the API to communicate with Triton.

Every model must be associated with a backend. A model's backend is specified in the model's configuration using the 'backend' setting. For using TensorRT backend, the value of this setting should be tensorrt. Similarly, for using PyTorch, ONNX and TensorFlow Backends, the backend field should be set to pytorch, onnxruntime or tensorflow respectively. For all other backends, 'backend' must be set to the name of the backend.`

We previously had a field called platform, which we support as a deprecated option instead of backend. It looks like during a [recent documentation update](https://github.com/triton-inference-server/backend/pull/66/), the references to that field were removed to avoid confusion but the examples were not updated to use backend. I've created a ticket to do so. Thanks again!

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @dyastremsky , thanks for the detailed message. Still, which field should I use and which values are supported?

**Comment by dyastremsky** [comment]
That's correct, `backend`. That [first link](https://github.com/triton-inference-server/backend/blob/main/README.md#backends) should always list the available values. Quote below.

> Every model must be associated with a backend. A model's backend is specified in the model's configuration using the 'backend' setting. For using TensorRT backend, the value of this setting should be tensorrt. Similarly, for using PyTorch, ONNX and TensorFlow Backends, the backend field should be set to pytorch, onnxruntime or tensorflow respectively. For all other backends, 'backend' must be set to the name of the backend.

The `all other backends` includes custom backends, by the way. If you build your own, Triton is going to be looking for the backend named whatever is in that field. Also, as you play around with the config to learn the fields, you can try using the [auto-generated model configuration](https://github.com/triton-inference-server/server/blob/3589c2c72d249392809fe9ae3de8057fe0437135/docs/user_guide/model_configuration.md#auto-generated-model-configuration) on many models (putting the model in without a config) in --verbose-log mode to see what config gets auto-generated by Triton for a certain model.
