### ISSUE TITLE
Get request_id_ from failed request

### ISSUE THREAD

**Issue by avickars** [triton-inference-server/server#4941]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

In my current implementation I assign each request sent to Triton a request id, that is used when the response is returned to determine how to process the result.

However I noticed when a request fails (ex: request duration exceeds client timeout) that the request_id is not available.  So I am wondering if there is at all possible a way to access it, or if there is another unique identifier that I can use to match a request sent to a failed request?

**Comment by dyastremsky** [comment]
Can you provide more specifics into what you're trying to do? Ideally, steps to reproduce as well.

The [request ID is made available to the response](https://github.com/triton-inference-server/core/blob/main/src/infer_request.h#L466-L477) when the callback is being set. So you can get the request ID from the response. Do you need to get it a specific way (e.g. via the C API)? Or are you trying to save the original request ID... in which case, since it'll get deleted, it'd be best to do that on the client side.

**Comment by dyastremsky** [comment]
Clossing issue due to inactivity. If you would like to follow up on this, let us know and we will reopen the ticket.
