### ISSUE TITLE
how to get triton_python.dll?

### ISSUE THREAD

**Issue by iPengXPro** [triton-inference-server/server#4954]
i download [tritonserver2.25.0-win.zip](https://github.com/triton-inference-server/server/releases/download/v2.25.0/tritonserver2.25.0-win.zip)
and run tritonserver.exe on win10,the comand is 
tritonserver --model-repository=D:\xxx\bls_yolov7_trt2206 --backend-directory=..\backends --backend-config=tensorflow,version=2 --strict-model-config=false --log-verbose=1
and i get 
 UNAVAILABLE: Invalid argument: unable to find 'triton_python.dll' for model 'bls'

how to get triton_pyhton.dll? thx

**Comment by krishung5** [comment]
Hi @iPengXPro, unfortunately, Triton does not support python backend and that's why there is no `triton_python.dll` in tritonserver2.25.0-win.zip. For all the features and backends available on windows, you can refer to this [section](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/build.md#build-triton-server) or [build.py](https://github.com/triton-inference-server/server/blob/main/build.py#L1654-L1657).

**Comment by iPengXPro** [comment]
您的邮件已收到，谢谢！

**Comment by iPengXPro** [comment]
OK！
Thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "triton-inference-server/server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 凌晨1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [triton-inference-server/server] how to get triton_python.dll? (Issue #4954)





 
Hi @iPengXPro, unfortunately, Triton does not support python backend and that's why there is no triton_python.dll in tritonserver2.25.0-win.zip. For all the features and backends available on windows, you can refer to this section or build.py.

**Comment by krishung5** [comment]
Closing this issue as the question has been addressed.
