### ISSUE TITLE
Possibility to recreate new connection to the triton server

### ISSUE THREAD

**Issue by JindrichD** [triton-inference-server/server#5009]
**Description**
Hi, this probably does not fall into the bug category and i was not sure whether it may rather fit into feature request, Anyway here it is: we are using grpc streaming client `tc::InferenceServerGrpcClient` (created with `InferenceServerGrpcClient::Create()` function), the stream is started with `StartStream(...)` and we are calling `AsyncStreamInfer(..,)` to do the infer request.  when client gets the results, the pointer is freed and everthing repeats. 

i thought that when the client is deleted all the network connections are shutdown as well. however it is not the case.
I found out increasing number of TCP connections that goes to triton server, i don't fully understand when they are created, as it is not after each call to `Create()` function and after some time I saw error messages of type `too many opened files` on the server. I was able to partially workaround that with reusing the stream, but it is not optimal because i needed to increase the stream timeout. so this rather seem as a bug to me. 
however we would like to control when new tcp connections are created anyway, as our clients are behind a load balancer and we would like to create new connection when servers are going to be scaled down.

so my question is whether it is possible to somehow control when new tcp connections are created? i did not find any client api, so maybe with some grpc env variables? 

**Triton Information**
r22.02

Are you using the Triton container or did you build it yourself?
triton container

**To Reproduce**
see above

**Expected behavior**
client user should be able to control creation of tcp connections

**Comment by GuanLuo** [comment]
@jbkyang-nvi @tanmayv25 can you take a look?

I don't think GRPC exposes such a finer control over connections,.

**Comment by GuanLuo** [comment]
We have some data structure [to keep channel open and shared](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.cc#L45-L53) for performance result, perhaps that is why the connection is not closed and the data structure should have been pruned when destructing the client.

**Comment by JindrichD** [comment]
yea, i've found that map too. Problem is that the channels are never removed from the map. Normally when the channel is destroyed/not used any more, grpc frees the network resources and shuts down the tcp connection as well. However this never happen because channels are only added to grpc_channel_stub_map_ and there is no way how to remove them manually.

**Comment by jbkyang-nvi** [comment]
@JindrichD the best practices for GRPC for high load applications listed [here](https://grpc.io/docs/guides/performance/) includes reusing the TCP connections. I might be missing something here in my understanding but some questions:
1. Why do you need to create a new connection every time? The client actually (defaults to reusing connections)[https://github.com/triton-inference-server/client/blob/64bc158e026d1f6674b1bc1d098f5e19fbba2034/src/c%2B%2B/library/grpc_client.h#L116-L118] since closing old connections take more time. 
 a. If you want a new connection every time you create a client, you can call `force_new_connection` to be true and the new connections will replace the old connection. However if you are reusing connections, you shouldn't be getting the `too many open files` message...
b.  Are you saying you are creating a new url every time you swap out clients? If you do, then it makes sense that there is a `too many opened files` message. However, if you are only doing load balancing, does the downscaled connection need new urls?

2. To your point on the shared `std::map` that manages all the connections: we can create a flag to close the connection when each client is destructed... this is a feature the grpc client does not currently have.

**Comment by JindrichD** [comment]
Hi, we are using r22.02 and lookin at latest code, there are some improvements, so the situation with `too many open files` might not be actual to the latest code. And actually it might also help even with our second problem. Let me explain it a bit more:
Our clients are connected to a loadbalancer, which internally maintains pool of triton servers that can be used. when it decides that one of the servers will be removed, there is some grace period during which we want to all active inference calls to be finished (so they are not interrupted by simple shutting down the server) but no new inferences are not to be started on that server. To achieve that, LB would not forward new connections to that server that is going down, but to the others from the pool instead. So for that we want to be able to say something like: hey client, next time you are going to do inference call, shut down existing connection and do the new one. (which can translate into client recreation, or something like that).

To your question 1c)
I said reusing the stream. And it was not optimal, because stream has a timeout in which it is supposed finish the inference request. but if we reuse a stream for more inferences, we also have to increase the timeout, which is not something that we want because if something breaks we would not know for long time.

**Comment by JindrichD** [comment]
with `force_new_connection` you mean the `use_cached_channel ` parameter https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/library/grpc_client.h#L125?
if so..yea, setting it false may work. so we might want to upgrade the client.

however it looks to me that it works somehow strangely if set to yes anyway - because it is only inserted in the map (i.e. when client finishes the shared count is not decreased), and if sharedcount reaches TRITON_CLIENT_GRPC_CHANNEL_MAX_SHARE_COUNT then map item is rewritten, so it means that till we reach that count the connections cant be closed.

**Comment by dyastremsky** [comment]
Closing issue due to lack of activitity. If you need further support, please let us know and we can reopen the issue.
