### ISSUE TITLE
Question about deploying multiple docker models on a single GPU

### ISSUE THREAD

**Issue by ethanfa** [triton-inference-server/server#5031]
Hi,

This is actually a question and not an issue. I am a novice to Triton and GPU, and the following questions may be wrong.
If so, I will appreciate your guidance in understanding things better.
I have a TensorFlow model that needs to be deployed in Triton.
Considering that the model is large (~1.5 GB), I will appreciate it if someone could help me to understand the following:
1. Can Triton manage GPU RAM and GPU cores for running multiple instances of the same model on a GPU such as A100 or a cluster of GPUs automatically?
2. If I use a Python backend, does it mean that every time the model wants to make an inference, it has to load the 1.5GB model from the HD? 
3. I have thought of encapsulating the model in a Docker with FastAPI. This helps to load the model once and then keep everything in the GPU RAM while calling the model for each inference with an async approach.
4. If (3) is possible, how should I solve the issue of the ports? assuming that A100 can load and run 8 models (8x1.5GB=12GBB), how should I handle the matter of multiple ports for each instance of the Docker for the model?

Thank you very much for your help.

**Comment by tanmayv25** [comment]
1. Triton does not manage cores and ram for GPU. It relies on the framework running behind tritonbackend to allocate and consume resources for its own.
2. No. you can load model once in model's `initialize` function and then repeatedly use it in the `execute` function.
3. Triton is a full-fledged inference serving solution with industry standardized serving protocol like TensorFlow Serving. FastAPI is just a framework for generic python services. There are lots of features for deriving better performance within Triton and you can use 
4. Why do you need to run multiple docker containers? I am not understanding your use case. You can load all the 8 models in a single tritonserver process. In a way it will be better because tensorflow has its own allocators and can utilize it across the different models.

**Comment by ethanfa** [comment]
Thank you, @tanmayv25. It was very helpful!

**Comment by tanmayv25** [comment]
Closing the issue.
