### ISSUE TITLE
Triton server container taking long time to launch. How to reduce the time when scaling to new instances

### ISSUE THREAD

**Issue by simhadri-eltropy** [triton-inference-server/server#5045]
## Environment

**TensorRT Version**: 22.04
**NVIDIA GPU**:  running on CPU machine
**NVIDIA Driver Version**: 
**CUDA Version**: 
**CUDNN Version**: 
**Operating System**: Ubuntu 22.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by simhadri-eltropy** [comment]
I am launching triton server on aws ec2 instances. using both python and onnxruntime backends.
However when I launch it the first time, it is taking about 10 mins to load and run the models and about 2 mins when I rerun the container again. 
If I have to scale in production to multiple servers. 10 mins is very long launch time. Why is it so?
the python environment I am using in python3.8 and the zipfile size is about 2 gb

**Comment by simhadri-eltropy** [comment]
@Tabrizian. your thoughts on this

**Comment by Tabrizian** [comment]
@simhadri-eltropy Sorry about the delayed response. I think the reason could be because of the large environment size or your Python model imports. If the Python imports take a long time or the environment is too big, using execution environments may take a long time because it has to decompress the execution environment. Alternatively, you could install the dependencies in your docker image so that you can remove the time required to untar the tar file.

**Comment by simhadri-eltropy** [comment]
Thanks @Tabrizian. it was bcoz of large environment issue. looking into optimising it.
