### ISSUE TITLE
Assigning GPU fraction to a model

### ISSUE THREAD

**Issue by saeid93** [triton-inference-server/server#5175]
In the containerized multi-model serving feature of Triton is it possible to assign a specific portion of the container hardware to each model?
E.g. consider that we have assigned a GPU to the Triton server container and there are three models inside it and I want to assigne 50% of GPU computational unit to model one and 25% to the other two models, or e.g. in a none-GPU case that 16 cores are assigned to the model server I want to assign 8 cores to one model and 4 cores to the other two models. Is this possible in Triton Server?

**Comment by rmccorm4** [comment]
Hi @saeid93 ,

On [MIG-capable devices](https://www.nvidia.com/en-us/technologies/multi-instance-gpu/), you should be able to partition your GPUs at the system level, and then assign the partitioned GPUs to separate tritonserver containers/processes to achieve such isolation. Currently it is not possible to assign multiple MIG slices/partitions to a single process due to a CUDA limitation, so you would need separate tritonserver processes/containers for each partitioned device (MIG slice).

I think the most relevant feature Triton has today to support what you are looking for is to assign fractions of GPU memory to model loading through the [--model-load-gpu-limit](https://github.com/triton-inference-server/server/blob/dfc6f196c1cbc191f4d3e6b0ae7d0e55e9de3fab/src/main.cc#L652-L658) flag. However, this is not really the same as assigning fractions of compute power as you described. MIG + separate tritonserver processes as described above is probably the best route for supporting your use case today. The MIG process limitation is described in more detail here: https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html#cuda-visible-devices
