### ISSUE TITLE
Has anyone implemented a backend for Goldwasser GPU inference?

### ISSUE THREAD

**Issue by yanxiuzi** [triton-inference-server/server#5200]
Goldwasser L256 `https://denglinai.com/?products_13/83.html`

**Comment by dyastremsky** [comment]
Not a publicly supported one. Also, this looks like hardware rather than a framework. Triton doesn't carry official support for this GPU, so while you can try running inference on Triton using a Goldwasser L256 GPU (e.g. I see the GPU supports a bunch of frameworks, so you could run an ONNX model via the ONNXRuntime backend), it's quite possible it won't work.
