### ISSUE TITLE
Custom metrics for Python backend?

### ISSUE THREAD

**Issue by cakeislife100** [triton-inference-server/server#5227]
We want to be able to define custom metrics from within Python models - is this possible right now? I see from the [docs](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#custom-metrics) that this is somewhat supported in C but I don't see any way to do it from Python.

Ideally we'd be able to define arbitrary metrics using the [Python Prometheus client](https://github.com/prometheus/client_python#counter) and have that automatically available to (and therefore scraped alongside) the Triton metrics endpoint.

We could use the Prometheus PushGateway for this but it doesn't seem like it was meant for this use case nor will it scale well. https://prometheus.io/docs/practices/pushing/#when-to-use-the-pushgateway.

Any advice for what to do here would be very helpful! Also happy to contribute back if we can get some pointers on how to do so.

**Comment by kthui** [comment]
@Tabrizian Do we support reporting metrics from within Python models (in Python backend)?

**Comment by krishung5** [comment]
The custom metrics support for Python backend is in our roadmap. For Python backend, the stub process which runs the python code needs to communicate with the parent process to call Triton APIs. To do so, both processes have their own message queue where they can read the message pushed from the other process and perform some actions. Each message is passed as a handle to the shared memory so that it can be loaded in each process. For the implementation, we need to have a background thread to monitor the messages in the parent queue so that if there is an ask from the python code to use the Metrics APIs we can handle it. We can make use of the current Logging thread/queue and modify it to be a thread/queue for both Logging and Metrics.

**Comment by cakeislife100** [comment]
That's awesome news! @krishung5 @Tabrizian is there a timeline for this feature?

**Comment by dyastremsky** [comment]
We cannot provide an exact timeline, but this feature is a priority for us.
