### ISSUE TITLE
Incorrect output for a movinet model on a tensorflow backend - Triton 22.04

### ISSUE THREAD

**Issue by dpostolovski** [triton-inference-server/server#5278]
**Description**
The output from a movinet model on a tensorflow backend is incorrect. No error message or warning is present.
Latest version (Triton 22.12) works as expected. Looking at the compatibility matrix, triton 22.04 is not compatible with tensorflow 2.10, but as a good practice, if not compatible with the specific model, some error message should be expected.

What is the best way to prevent bugs like these creeping in?

**Triton Information**
22.04

Are you using the Triton container or did you build it yourself?
Yes, using 22.04-py3 official image container.

**To Reproduce**
Steps to reproduce the behavior.
Train a movinet model on tensorflow 2.10 and export it as a savedmodel. Load it in Triton 22.04, inference it and the result
will be different than when inferencing on native python with the latest version of tensorflow.

**Expected behavior**
Model outputs from tensorflow and triton are the same, or an error message about compatibility is present.

@rsandler00

**Comment by jbkyang-nvi** [comment]
Thanks for the report @dpostolovski . I have created a ticket to look into this. cc: @tanmayv25

**Comment by tanmayv25** [comment]
@dpostolovski 
> Load it in Triton 22.04, inference it and the result will be different than when inferencing on native python with the latest version of tensorflow.

Can you try comparing the outputs of triton 22.04 with the output of native python with the tensorflow version 2.8.0 - which is the tensorflow version shipped with Triton 22.04?
This looks like an issue with tensorflow library. If a particular savedmodel is not supported in the specific TF version then an error needs to be thrown.

**Comment by tanmayv25** [comment]
Closing the issue because of the lack of activity. Please respond to the questions so we can investigate the issue further.

Some degree of difference is expected. Outputs from different versions of TensorFlow library(TF 2.8.0 in Triton and TF 2.10 in python) can be different. The correct comparison would be output from TF 2.8.0 in python to output from TF 2.8.0 in Triton.
We are also curious to learn how different are the results? Different version means different kernels might be invoked for the tensor ops.
