### ISSUE TITLE
Dynamic model loading/unloading depending on requests?

### ISSUE THREAD

**Issue by MichalPitr** [triton-inference-server/server#5345]
I am trying to serve a Switch Transformer. My setup is such that every expert is an individual Feed-Forward Neural Net and there are a couple hundred of these experts in a Switch Transformer. All of these models are in a static model repository.

I am not expecting to make concurrent inferences to all models, hence I don't need all of them loaded in the GPU memory at all times. If not all of my models fit in GPU memory, does TRTIS (or the Torch backend since I'm using PyTorch models) dynamically load/unload models depending on demand (observe request, potentially evict a model, load demanded model, run inference, repeat)?

I noticed there's the [model_management_api](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_management.md), which suggests to me that TRTIS doesn't do any dynamic loading/unloading and it simply tries to load all models to memory and either they fit or not. 

To verify this, is there a way to check which models are loaded on the GPU memory at any given time?

Many thanks!

**Comment by rmccorm4** [comment]
Hi @MichalPitr, thanks for raising this question.

> dynamically load/unload models depending on demand

I believe this is one of the goals of TMS: https://developer.nvidia.com/tms-early-access. CC @whoisj

Otherwise, it is generally on the user to make use of the available APIs to load/unload as needed. If running Triton in [explicit model control mode](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_management.md#model-control-mode-explicit), you can send load/unload requests to the server for specific models. Here are the exposed load/unload routes for the HTTP/GRPC endpoints: https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_model_repository.md

> To verify this, is there a way to check which models are loaded on the GPU memory at any given time?

You can check which models are loaded at any given time, and probably correlate this with their model configs (also queryable through APIs) to see which ones would be on GPU or not. Here's an example of starting a server with no models loaded, checking which are loaded, loading one, checking again, etc.

Start server:
```
# Start server in separate shell with explicit model control mode
root@rmccormick-dt:/opt/tritonserver# tritonserver --model-repository /mnt/triton/models/ --model-control-mode=explicit
```
Try model control APIs:
```
# No models loaded yet, none are READY
rmccormick@rmccormick-dt:~/triton$ curl -X POST localhost:8000/v2/repository/index
[{"name":"double"},{"name":"ensemble_double"}] 

# Load "double" model
rmccormick@rmccormick-dt:~/triton$ curl -X POST localhost:8000/v2/repository/models/double/load

# Now "double" is reported as READY
rmccormick@rmccormick-dt:~/triton$ curl -X POST localhost:8000/v2/repository/index
[{"name":"double","version":"1","state":"READY"},{"name":"ensemble_double"}]
```
Check config of a loaded model:
```
# Get whole model config
rmccormick@rmccormick-dt:~/triton$ curl -s localhost:8000/v2/models/double/config
...

# Get specific field from model config, such as instance group to check if on GPU
rmccormick@rmccormick-dt:~/triton$ curl -s localhost:8000/v2/models/double/config | jq .instance_group
[
  {
    "name": "double_0",
    "kind": "KIND_CPU",
    "count": 1,
    "gpus": [],
    "secondary_devices": [],
    "profile": [],
    "passive": false,
    "host_policy": ""
  }
]
```

**Comment by MichalPitr** [comment]
Awesome, thanks for the help!
