### ISSUE TITLE
The difference between triton bls and python banckend

### ISSUE THREAD

**Issue by ZR19971001** [triton-inference-server/server#5477]
Hello,

I would like to know the difference between triton BLS architecture and python backend, or what problem does BLS solve in python backend?If it is a cascade structure, what is the difference between simply using python backend and BLS?

Thank you for your help !

**Comment by GuanLuo** [comment]
BLS is the concept that user may describe a complex pipeline that calls back to Triton for model execution, which implies that the pipeline can utilize the model serving functionalities provided by Triton. Although it is true that you can also create such a pipeline purely within your Python backend model, you will have to re-create the boilerplate that Triton already provides. For example, if your pipeline contains execution of a TensorRT model, you will have to implement the logic to load and prepare the TRT I/O following the TRT interface, whereas with BLS, you can ask Triton to load the model, prepare and send the inference request back to Triton. The benefit of BLS is more obvious if your pipeline contains models in various frameworks, as the interaction with Triton is framework agnostic.

Note that BLS has its own limitation that the encapsulation may prevent further optimization of your pipeline, because it needs to ensure that each model execution is self-contained. To be clear that it doesn't mean that there is no parallelization in model executions, but it prevents you from performing more advanced optimization, for example, that you may know one of the model in the pipeline only needs a subset of outputs from the previous model, and the subset of the outputs will be ready in the middle of the execution. Then **without** BLS, you can start execution of the model as soon as the required outputs are ready rather than wait for the whole execution of the previous model.
