### ISSUE TITLE
How to get headers of request?

### ISSUE THREAD

**Issue by N-Kingsley** [triton-inference-server/server#5512]
**Description**
I want to get the headers of request, but when i use 'request.parameters()' in the models.py, it errors!

**Triton Information**
docker.io/nvidia/tritonserver:22.03-py3 

I both use the Triton container and build it yourself.

**To Reproduce**
![image](https://user-images.githubusercontent.com/38311217/225503761-8c4a1531-e769-4ea0-b4a2-5e40209068a0.png)
![image](https://user-images.githubusercontent.com/38311217/225503949-99593e9a-22bd-4584-8655-478b9ec970a3.png)

**Expected behavior**
I want to get the headers or parameters of request

**Comment by Tabrizian** [comment]
The headers are not supported yet and it is on our roadmap. The `parameters` will be included in the 23.03 release. You can build Python backend from source if you're interested in trying this feature. Since we already have a request for adding headers I'm going to close this one: https://github.com/triton-inference-server/server/issues/5391
