### ISSUE TITLE
docker can‘t run --gpus in orin

### ISSUE THREAD

**Issue by Egozjuer** [triton-inference-server/server#5641]
docker run --gpus="device=0" --rm  -p8000:8000 -p8001:8001 -p8002:8002 -v/home/orin/workspace/triton-inference-server/server/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:23.03-py3 tritonserver --model-repository=/models
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'csv'
invoking the NVIDIA Container Runtime Hook directly (e.g. specifying the docker --gpus flag) is not supported. Please use the NVIDIA Container Runtime instead.: unknown.

Hello,when I run images tritonserver:23.03-py3 ,once  I add --gpus, the container can't  run correctly,please tell me how to solve the problem

**Comment by nv-kmcgill53** [comment]
Hi @Egozjuer, currently we have not released a docker container which is compatible with Orin, however this is in development. You can find our latest Jetpack release [here](https://github.com/triton-inference-server/server/releases) (choose `*-jetpack5.1.tgz`)  which can be run on the host OS granted Jetpack 5.1 is installed. 

As for why the `--gpus` flag doesn't work on Orin devices, Orin platforms have an integrated GPU (colloquially referenced as iGPU) rather than a dedicated card/chip (a discrete GPU or dGPU). Thus some features of CUDA may not be compatible with Orin as they are with our other offerings. Please check the [CUDA documentation](https://docs.nvidia.com/cuda/) for these differences.

**Comment by tanmayv25** [comment]
Closing because of the lack of activity.

**Comment by mattdibi** [comment]
Hi @nv-kmcgill53, I've encountered the same error on `23.07-py3` on Orin AGX Developer Kit.

> currently we have not released a docker container which is compatible with Orin, however this is in development. 

Is this still true?
