### ISSUE TITLE
Question: scheduling on multiple GPUs when using cuda shared memory

### ISSUE THREAD

**Issue by philipp-schmidt** [triton-inference-server/server#5687]
I have a question when using cuda shared memory:

In case of multiple GPUs, if an inferencing request is made using a cuda shared memory location, will triton try to schedule inferencing on the same GPU the buffer is on? If not, will a memory copy between GPUs occur?

For example: if all clients make request and place their buffers on GPU 0, what will Triton do in that case if it has 4 GPUs available?

Additional information: we use Deepstreams nvinferserver plugin, but it is unclear from the documentation how to optimize it when Triton has multiple GPUs available. In many cases we can pick the GPU ID, but it is not clear if Triton will respect the placement of the memory buffers on GPU and use them accordingly or whether it will involve a memcopy between GPUs.

**Comment by oandreeva-nv** [comment]
@Tabrizian and @GuanLuo could you please help with these questions?

**Comment by Tabrizian** [comment]
> If not, will a memory copy between GPUs occur?

The inference can happen on any GPU. The memory copy between devices may happen depending on which instance gets picked up for the inference.

This request is on our roadmap. https://github.com/triton-inference-server/server/issues/5564

**Comment by philipp-schmidt** [comment]
Thanks for the quick reply. This makes using cuda shared memory potentially very inefficient on a multi-gpu system.
Is there a way to make the scheduler aware of the location of the cuda buffer and prioritize the same GPU?

For a 4 GPU system we want to make use of all available NVENC decoders (and VRAM), which place the memory of the decoded frames on their respective GPU. Using cuda shared memory now will randomly copy that buffer across GPUs, even though there is a model instance running on the very same GPU.

I was expecting this to be trivially supported, as in: the scheduler understands that the buffer lives on GPU ID 3, so he will use the model instance on GPU ID 3 to avoid a memcopy.

**Comment by Tabrizian** [comment]
> Is there a way to make the scheduler aware of the location of the cuda buffer and prioritize the same GPU?

Unfortunately, it is not possible right now. The only way to workaround this issue right now would be to create multiple models where each one is located on a single GPU and send request to the correct model.

I agree that this is something that we need to add. Hopefully we can address this issue soon.

**Comment by philipp-schmidt** [comment]
Thanks @Tabrizian for the comments and for addressing this.

We are fine with the current implementation for now. I suppose this technically this puts cuda shared memory at the same performance than regular system shared memory for multi-gpu servers. But tritonserver handles the copy from device to host instead of the application. And bonus performance whenever the request hits the correct GPU by chance.

Happy to try out any new feature coming up regarding this.

**Comment by Tabrizian** [comment]
Exactly, that would be the case until the issue is addressed.

**Comment by ivanfarevalo** [comment]
Wanted to follow up on this conversation. Currently using triton server 24.06.
My setup:
* I have my python application and triton servers running on same machine. Triton server only serves requests for this application.
* 2 triton servers each designated to 1 GPU. (This is because multigpu support with onnx tensorrt optimization model doesn't work with single server.)
* My application has visibility into both GPUS and has 2 processes which send requests to their designated server.
* Using an onnx model with tensorrt optimizations.
* Using cuda shared memory

My Issue:
When using cuda shared memory, I have to set and register cuda shared memory to gpu 0 regardless of which server I am requesting to. I have verified that setting this works correctly for my setup. When trying to set cuda shared memory on gpu 1 i get the following error:
```
File "/app/.pyenv/versions/3.10.14/lib/python3.10/site-packages/tritonclient/grpc/_client.py", line 1565, in infer
    raise_error_grpc(rpc_error)
  File "/app/.pyenv/versions/3.10.14/lib/python3.10/site-packages/tritonclient/grpc/_utils.py", line 77, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] input: failed to perform CUDA copy: invalid device ordinal
```

Since I assigned each process a corresponding server which is an corresponding gpu, there is no load balancing between GPUs. This also means there is no reason for me to only set shared memory to gpu 0 and then have triton do a mem copy between gpus everytime i request to gpu 1.

I have tried setting cuda context explicitly to a device before requesting inference but did not make any difference.
```
import pycuda.driver as cuda
cuda.init()
context = cuda.Device(gpu_id).make_context()
# Get the device associated with the current context
current_device = cuda.Context.get_device()
print(f"Device obj: {current_device}, Current device: {current_device.pci_bus_id()}, Name: {current_device.name()}, Ordinal: {current_device.__hash__()}")
``

Is there a known fix for this issue for more recent triton servers?
