### ISSUE TITLE
How to upgrade the model configuration file to poll mode for tritonserver

### ISSUE THREAD

**Issue by JasonChao-yue** [triton-inference-server/server#5711]
How to achieve loading and unloading of new and partial models without restarting the tritonserver service？Can you provide some tutorial materials?

**Comment by dyastremsky** [comment]
You would just make changes to the model repository. POLL mode is not recommended for running in production because there is no synchronization between when you make changes to the model repository and when Triton polls and updates the model repo, as mentioned in the documentation [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_management.md#model-control-mode-poll). However, if you want to load or unload models in POLL mode, you'd do it by modifying the model repository.
