### ISSUE TITLE
Can Triton achieve a return in typewriter form?

### ISSUE THREAD

**Issue by SeibertronSS** [triton-inference-server/server#5788]
**Is your feature request related to a problem? Please describe.**
I use FasterTransformer + Triton to deploy my language model. I found that Triton always waits for the model to complete the entire inferencing process before returning all the results. I hope that Triton can return immediately when the model generates the first token, and continue to output all subsequent results to achieve a typewriter effect.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dyastremsky** [comment]
Thank you for submitting this feature request. The FasterTransformer backend is a research tool, not an officially supported product. It is also undergoing restructuring at the moment, please see its repository for more details.

While this is not currently supported, these sort of features are being developed by the folks working on it. I am going to close this issue for now as this will be specific to that backend rather than supported by Triton across different backends. Keep an eye out for updates on the FasterTransformer backend.
