### ISSUE TITLE
Can I use triton with deepspeed inference?

### ISSUE THREAD

**Issue by sooftware** [triton-inference-server/server#5823]
Thanks for your great works. 
I'm using the triton inference server, and I want to use the deepspeed inference module together. Can I use it together?

**Comment by ppppppppig** [comment]
@dyastremsky Can I implement a DeepSpeed backend to run a large language model?

**Comment by dyastremsky** [comment]
Of course. Please see here for documentation to help create your own backend: https://github.com/triton-inference-server/backend#how-can-i-develop-my-own-triton-backend

**Comment by sooftware** [comment]
Deepspeed runs in the format as "ds *.py", and Triton runs in the format as "triton $FOLDER", do you know how to execute both?

**Comment by kunal14053** [comment]
Hi, I have optimised the model latency with DeepSpeed inference and now want to use triton server with that in order to server multiple request or increase my throughput. Is this possible to do? 
As of now I have been using Gunicorn workers to load the model for each worker to serve the concurrent requests.
