### ISSUE TITLE
How to serve Python models on GPU

### ISSUE THREAD

**Issue by benhgm** [triton-inference-server/server#5889]
**Description**
Hi everyone, I have created an ensemble model consisting of a python preprocessing and a python post processing model, plus a CNN model.

I would like to ask how do I know if my Python models are served using GPU or CPU?

I am asking because if i set the 'instance_group' parameter in the python models config files to KIND_GPU, and i run nvidia-smi, I see that the ensemble takes up the same memory as if i set KIND_CPU for the python models.

**Comment by dyastremsky** [comment]
The Python backend is a little unique in this regard. The model execution is completely dependent on the model, so the only change KIND_GPU and KIND_CPU does is if the model uses those values to change its execution.

**Comment by benhgm** [comment]
hi @dyastremsky could you share a sample script on how to do that?

**Comment by dyastremsky** [comment]
I believe this model in our QA repository is a good example: https://github.com/triton-inference-server/server/blob/main/qa/python_models/torchvision/resnet50/model.py#L38

**Comment by dyastremsky** [comment]
CC: @Tabrizian who may have a more detailed answer.

Generally, the Python backend gives you a lot of freedom in how you implement your models. Since it's running whatever Python code you write, you'd need to dive into the documentation of the code you're using to validate the code puts it on the GPU and whether there are APIs for checking where it is running. The one Triton-specific thing you can do is validate (e.g. with print statements) that your if the kind is being picked up correctly and therefore your if statement is running correctly.

**Comment by Tabrizian** [comment]
Closing, due to in-activity.
