### ISSUE TITLE
Ensemble model versioning

### ISSUE THREAD

**Issue by MADHUMITHA-V2-IBM** [triton-inference-server/server#5890]
Hello,

I was working on deploying ensemble models in Triton version `2.33.0` `r23.04`. I was able to deploy and infer simple custom models. 
One problem I faced was with respect to model version. I'm not able to use version `1` for all ensemble models on x86 systems. It's instead asking me to use version `0`. I am getting the following error when I change the model version to 1:
`E0601 02:56:21.546245 8507 model_repository_manager.cc:501] Invalid argument: ensemble 'ensemble' depends on 'custom_model' whose required version 0 is not loaded.`
I tried a couple of combinations but triton expects to use version `0` for all ensemble models. But the examples in the server repo uses model version `1` instead. I faced this even with lower versions of Triton [r23.01, r23.02].

Is this some sort of an error or am I missing something?
Please do let me know how to enable custom model versioning as well.
Thank you

**Comment by phamkhactu** [comment]
In custom_model, you should use to specific your version:
```
version_policy: { specific: { versions: [3]}}
```
For example, I specific version is 3.

**Comment by MADHUMITHA-V2-IBM** [comment]
Thank you @phamkhactu.
I want to confirm if 1 is the default version for ensemble models or is it 0? Because I see examples where this `version_policy` is not mentioned and still they were able to use version 1, whereas I'm not able to use version 1 but 0.

**Comment by rmccorm4** [comment]
Hi @MADHUMITHA-V2-IBM,

Typically users default to version 1 in the model repository, or specifying -1 (meaning "latest") in the `ensemble_scheduling` step. I don't believe a model version of "0" typically comes up. 

If I were to guess, are you perhaps writing an ensemble model config and **not** specifying the `model_version` in the ensemble step? You must specify the model_version, otherwise I believe it will default to 0 based on general [protobuf behavior](https://protobuf.dev/programming-guides/proto3/#default).

> For numeric types, the default value is zero.

```
ensemble_scheduling {
  step [
    {
      model_name: "my_model"
      model_version: 1      # <--- This version must be specified, otherwise it will default to 0 in protobuf
      ...
    }
...
  ]
}
```

If that's not the issue, please share all the relevant model configs so we can have more info to debug.
