### ISSUE TITLE
Yielding Tokens During LM Inference

### ISSUE THREAD

**Issue by DayOfThePenguin** [triton-inference-server/server#5913]
Hi All,

How do you recommend replicating the "streaming token" experience of chat-based language models where you iteratively yield the result of a prompt and render it for a user vs returning the entire response at once?  My Python-only code looks like: https://huggingface.co/spaces/mosaicml/mpt-7b-chat/blob/main/app.py

I've tried to replicate this behavior using the Triton Python backend, but the core problem is that there doesn't appear to be a way to get Triton to iteratively yield tokens and instead I have to wait to get a complete inference response.

Essentially, how do you get a generator of `InferenceResponses` from a single execution of `InferenceRequest.exec()` vs a single `InferenceResponse`

**Comment by nv-kmcgill53** [comment]
CC: @GuanLuo @Tabrizian @nnshah1 @Christina-Young-NVIDIA

**Comment by Tabrizian** [comment]
Hi @DayOfThePenguin, using the decoupled mode in Python backend you can return many responses for a single request instead of only a single response: https://github.com/triton-inference-server/python_backend#decoupled-mode

This way you can stream responses to the client as they are being received from the model. We also recently added support for decoupled BLS models in Python backend so you can execute BLS requests on them as a part of your Python model exeuction.

**Comment by nicobasile** [comment]
Hi @DayOfThePenguin were you able to get token streaming to work with MPT? I'm working on this now and it would be great if you had any helpful info

**Comment by Tabrizian** [comment]
Closing, since it is already supported in Python backend APIs.

**Comment by DayOfThePenguin** [comment]
@Tabrizian, yes this was exactly what I needed, thanks!

**Comment by merlinarer** [comment]
> @Tabrizian, yes this was exactly what I needed, thanks!

I am trying to impl. the same for LLMs, and I would be grateful if you could proviode any help ~
