### ISSUE TITLE
Metrics: number of requests in queue 

### ISSUE THREAD

**Issue by cceyda** [triton-inference-server/server#5927]
**Is your feature request related to a problem? Please describe.**
I would like to see number of requests currently waiting in queue so I can better schedule things.
I can see the duration `nv_inference_queue_duration_us` but not how many requests are waiting. 
I saw `nv_inference_queue_summary_us_count` but I think this is just counting how requests were used to calculate the stats so doesn't signify how many are waiting in queue according to the docs:

> The count and sum for the summary above show that stats have been recorded for 161 requests, and took a combined total of 11110 microseconds. The _count and _sum of a summary should generally match the counter metric equivalents when applicable, such as:

Also want to add an average `throughput per second` metric to grafana would
`rate(nv_inference_count{}[$__rate_interval])` be the way to do it?... The number seems lower than what I see with perf_analyzer

**Comment by nv-kmcgill53** [comment]
CC: @rmccorm4 @oandreeva-nv

**Comment by rmccorm4** [comment]
Hi @cceyda,

Thanks for posting this issue.

> I saw nv_inference_queue_summary_us_count but I think this is just counting how requests were used to calculate the stats so doesn't signify how many are waiting in queue according to the docs:

Correct, as of today all `nv_inference_*` per-model metrics are generally updated at the same time **after** the response is completed. So this queue count is basically the same as number of requests that have completed successfully, and should generally match the `nv_inference_request_success` count or the other `nv_inference_*_summary*` counts if talking about summaries.

The number of requests currently in-queue is not reported today, nor are there any current plans to add this feature. However, if there is enough interest/use cases around it, we may consider it - so I'll add the enhancement tag for now. 

However, in terms of using queue metrics to estimate load and schedule (load balance) accordingly, today the existing `queue_duration` metric can be used to calculate a moving average of the **time** requests are spending in queue for each model as described in the blog: https://developer.nvidia.com/blog/deploying-nvidia-triton-at-scale-with-mig-and-kubernetes/. 

---

I'll share some of my general thoughts on adding a `num_requests_in_queue` metric below:

For a relatively fast model, just looking at the number of requests in queue may not be sufficient to express a bottleneck. For example, if an inference can be computed in 10ms and there are 100 requests in queue, these requests could all be done and finished in the next second. For a prometheus client querying the queue metric, the time spent querying may already be outdated in some cases like this.

For a larger/slower model, I can see a `num_requests_in_queue` metric being more intuitive than the duration metric, and still useful since each request may actually sit in the queue and have more impact on the load given each compute/inference being longer.

I'm curious on your thoughts/feedback, your use case needs, and if the existing queue duration metric could be used to meet your needs as described in the blog above.

**Comment by rmccorm4** [comment]
> Also want to add an average throughput per second metric to grafana would
rate(nv_inference_count{}[$__rate_interval]) be the way to do it?... The number seems lower than what I see with perf_analyzer

This seems like a reasonable computation to me at a glance. Can you share some of the numbers you're seeing for reference?
1. full perf_analyzer command and the reported throughput
2. snapshots of a few nv_inference_counts and the number being reported from the interval, etc.

**Comment by Jack47** [comment]
the queue length is a good way to know when the request will be served. so I believe this is useful in some cases

**Comment by cceyda** [comment]
Another related request to this one: #6044

**Comment by FrankTheTank9** [comment]
I’d like to +1 this request. We are serving LLM with slow response and a queue length metrics would be better than queue duration to evaluate load to capacity with dynamic batching until we have in-flight batching.

Any ETA for this feature?

**Comment by olehpidhi** [comment]
+1 for this request. Queue size is an important metric for models with slow response times.

**Comment by arnabmanna619** [comment]
+1 for this request too. In my use case, we are using a combination of local machines and serverless GPU for cost optimization. So it there are already n requests in queue then serve with serverless GPU else use the local machine.

**Comment by rmccorm4** [comment]
Hi everyone, thanks for expressing your interest. I am looking into the feature now, no firm ETA yet.

**Comment by rmccorm4** [comment]
Hi everyone, we've [implemented](https://github.com/triton-inference-server/core/pull/246) this metric and it will tentatively be included in the 23.09 release, assuming no unexpected issues. See [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#pending-request-count-queue-size-per-model) for a preview description of the feature.

**Comment by paras-oai** [comment]
Hi @rmccorm4 , thanks for this feature. It's very helpful. Is it possible to know how much memory all of the requests in the queue are occupying at a particular point of time?
