### ISSUE TITLE
Am I the only one who can't pull nvidia image from `nvcr.io/nvidia` ?

### ISSUE THREAD

**Issue by hunhoon21** [triton-inference-server/server#5958]
**Description**
I can't pull tritonserver image now.

**Triton Information**
* `tritonserver:21.12-py3`

**To Reproduce**

command: `docker pull nvcr.io/nvidia/tritonserver:21.12-py3`

**Expected behavior**
pulled well. But I got 
```
Error response from daemon: received unexpected HTTP status: 502 Bad Gateway
```

**Comment by muqishan** [comment]
No, you are not. Today, while I was doing some debugging, I realized that I couldn't fetch image either. However, just as I was replying to your message, it was able to retrieve the image. I believe this might be due to an upgrade or maintenance of the Nvidia server.

`sudo docker pull nvcr.io/nvidia/tritonserver:23.04-py3`
`Error response from daemon: received unexpected HTTP status: 502 Bad Gateway`

**Comment by kthui** [comment]
I just tried pulling from `nvcr.io/nvidia/tritonserver:21.12-py3` and `nvcr.io/nvidia/tritonserver:23.04-py3` links, and they are both working. Can you try it again?

**Comment by hunhoon21** [comment]
It works now. Thank you!
