### ISSUE TITLE
Allow A Graceful Period Before Triton Service Stops

### ISSUE THREAD

**Issue by tonyguo2022** [triton-inference-server/server#6230]
**Is your feature request related to a problem? Please describe.**

First of all, many thanks to the triton inference server project. It works great.

When we run triton server in a k8s container, the cluster may still send requests to triton server even after the container has received stop signals. Then the triton server would respond with "unknown model" because the triton server has started to unload models to stop. This could happen continuously for several seconds.

**Describe the solution you'd like**

We are wondering if it is possible for the triton server to wait for a few seconds right before the triton server really starts to exit. It is even better if this period is configurable, such as GracefulPeriodBeforeStopping or exit-graceful-secs. During this period, the triton should still be fully functional.

If this feature is available, our QoS will be significantly improved. Thanks in advance.

**Describe alternatives you've considered**
~~A clear and concise description of any alternative solutions or features you've considered.~~

**Additional context**
Example of the errors we hit:
grpc_server.cc:3920] [request id: <id_unknown>] Infer failed: Request for unknown model: 'model-name' is not found.

We have noticed there is an [option](https://github.com/triton-inference-server/server/blob/64975185d58ddf8a9d1fe83b5d2104286c8ab45f/src/command_line_parser.cc#L342C3-L346C33) of timeout in seconds when exiting to wait for inflight inferences to finish. But that's for different purpose. Here we expect the service can still accept new requests for a short period when exiting.

**Comment by dyastremsky** [comment]
Thank you for your kind words about the Triton Inference Server project. We appreciate your feedback and your use of the platform.

In terms of the feature being requested, this sounds like it is outside the scope of Triton. Once Triton starts shutting down, no new requests will be accepted. If you want Triton to shut down later, rather than adding configurable sleep logic to Triton, it would make sense to have whatever is calling for the shutdown (e.g. code to shut it down) wait/sleep the length of time before calling for the server to be shutdown.

For Kubernetes specifically, you can consider implementing a graceful shutdown mechanism at the Kubernetes level. Kubernetes provides lifecycle hooks that allow you to perform certain actions before a pod is terminated. You can set up a preStop hook that will be executed when the pod receives a termination signal. This hook can wait for a configurable period of time before allowing the pod to terminate completely. During this waiting period, Triton should still be able to handle incoming requests. Alternatively, you might want to look at resend logic when a request fails. There is also the Triton health check that might be helpful here.

The [Triton Management Service](https://www.nvidia.com/en-us/ai-data-science/products/triton-management-service/) team also mentioned that if horizontal pod autoscaling is enabled and you have a smart cluster, the issue should be self-healing due to Kubernetes handling the traffic routing.

**Comment by tonyguo2022** [comment]
Thanks @dyastremsky  for the reply and the suggestion to use Kubernetes preStop hook. We will try it first.

As I described, we actually observed that the triton server could still accept new requests but respond with unknown model. Seems the triton server would unload models first then shutdown the GRPC endpoints (socket listeners).
> Once Triton starts shutting down, no new requests will be accepted.

**Comment by dyastremsky** [comment]
Interesting. You raise a good point about disabling socket listening, even if the socket itself needs to stay open to send responses for in-flight requests.

CC: @GuanLuo @Tabrizian, can you think of any ways that disabling Triton's endpoints' ability to listen before starting to unload models would be problematic e.g. for sequence models or streaming requests? If not, I can open a ticket to track this feature request.

**Comment by kgu3** [comment]
hi @tonyguo2022, may I ask how you found out that "When we run triton server in a k8s container, the cluster may still send requests to triton server even after the container has received stop signals."??
Is that some logging by tritonserver or cluster?

**Comment by tonyguo2022** [comment]
@dyastremsky We tried the preStop hook and it works. Thanks a lot for the suggestion.
> Thanks @dyastremsky for the reply and the suggestion to use Kubernetes preStop hook. We will try it first.

@kgu3 We checked both cluster and triton server logs to conclude that the errors were during termination stage.
And the source file name "grpc_server.cc" in the log indicated it's from triton server.
> (grpc_server.cc:3920] [request id: <id_unknown>] Infer failed: Request for unknown model: 'model-name' is not found.

**Comment by dyastremsky** [comment]
Thank you for trying the suggestion and updating us, Tony. Happy to hear it worked for you!
