### ISSUE TITLE
coder bug in r23.04

### ISSUE THREAD

**Issue by LuLu2kANG** [triton-inference-server/server#6240]
**Description**
r23.04

build triton without docker 
when build with tensorrt backends
error at the code

`/server/build_dir/tensorrt/src/tensorrt_utils.cc::411`

the code is :
`int64_t dim;`

dim should be init
so i change it 
`int64_t dim = 1;`

and it is ok now

**Comment by dyastremsky** [comment]
Thank you for letting us know. This builds fine in our build pipeline. Perhaps you are using different CMake with different options (e.g. --warn-uninitialized with CMAKE_COMPILE_WARNING_AS_ERROR) or have a different build environment.

It generally does not make sense for us to change this on our end because there are other places in the code with similar logic, i.e. not initializing the variable because it is set in the next line (like in [tensorrt_utils on the mentioned line](https://github.com/triton-inference-server/tensorrt_backend/blob/7c6751bbbe38e8f037de08ff3f40bc23f7531858/src/tensorrt_utils.cc#L176). If you think this it is important to initialize these variables on the same line for your compiler, you can submit a pull request making these changes following [the contributing guidelines](https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md) and we can review it.
