### ISSUE TITLE
Potential concurrency safety issues in streaming inference

### ISSUE THREAD

**Issue by dyastremsky** [triton-inference-server/server#6245]
### Discussed in https://github.com/triton-inference-server/server/discussions/6214

<div type='discussions-op-text'>

<sup>Originally posted by **liuyang-my** August 20, 2023</sup>
Is there a thread safety issue in `ModelStreamInferHandler` of Triton Server grpc in streaming mode? After the `Process` function handles the `WRITEREADY` state, the state transitions to `WRITTEN`. If `HasReadyResponse` is evaluated as false during the handling of `WRITTEN`, the state is set to `ISSUED`. If `StreamInferResponseComplete` is called before the state is modified to `ISSUED`, and `StreamInferResponseComplete` checks that `is_decoupled_` is true and `step_` is `WRITTEN`, it does nothing. In this case, when the thread context switches back to `Process`, the state is set to `ISSUED`. If this response happens to be the last response and there are no tasks in the CQ, will `Finish` never be executed?

![image](https://github.com/triton-inference-server/server/assets/84125729/7953a879-77ac-4645-a6fb-c9f042033924)
</div>

**Comment by dyastremsky** [comment]
Thank you for reviewing the code and asking about this, @liuyang-my. We have filed a ticket (DLIS-5344) to investigate this and update you.

**Comment by rmccorm4** [comment]
Hi @liuyang-my, took a quick look at this.

Isnt' this lock protecting the critical section you're describing?
```cpp
        std::lock_guard<std::mutex> lock(state->step_mtx_);
```

If the Process() thread gets [here](https://github.com/triton-inference-server/server/blob/41c689e674cb3f9a3afa08e3fb7781288dc2b971/src/grpc/stream_infer_handler.cc#L442C1-L454) first, it will lock, check for ready response, or mark as ISSUED if no ready response. 

If the StreamInferResponseComplete thread gets [here](https://github.com/triton-inference-server/server/blob/41c689e674cb3f9a3afa08e3fb7781288dc2b971/src/grpc/stream_infer_handler.cc#L623-L630) first, it will mark a response as ready for the Process() thread to see, or move to WRITEREADY and put task back on queue for writing if the Process() thread had already marked as ISSUED.

But neither section should get interweaved because of the lock on `state->step_mtx_` as far as I can tell.

Let me know if this summary doesn't line up.

**Comment by liuyang-my** [comment]
This lock guarantees the order of steps, which I previously overlooked. Thank you for your guidance.
