### ISSUE TITLE
getting gRPC connection error after updating triton from 22.03 to 23.07

### ISSUE THREAD

**Issue by RazHoshia** [triton-inference-server/server#6327]
**Description**
We maintain a number of triton servers, all getting requests from a single service using gRPC.
each server is loaded with several different ensembles.
After upgrading Triton from 22.03 to 23.07 we are getting this error during some of the requests to the servers.
```
gRPC Connection Error: Status { code: Unavailable, message: "upstream request timeout", metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-envoy-upstream-service-time": "14999", "server": "envoy"} }
```
We use HashiCorp Consul envoy sidecar with the Triton servers.

Can you please point me to changes that happen between the versions that may cause this issue / ways to debug what is happening better?

**Triton Information**
Using the official triton container - version 23.07

**Comment by oavner** [comment]
getting the same error using nginx ingress controller as a reverse proxy for triton server instances. after upgrading from 22.03 to 23.07 our nginx reverse proxy logs the following connection timeout error:
```
upstream timed out (110: Operation timed out) while reading response header from upstream, client: <client>, server: <triton-server>, request: "POST /inference.GRPCInferenceService/ModelInfer HTTP/2.0", upstream: "grpc://<triton-server>:8001", host: "<triton-server>:80"
[19/Sep/2023:11:16:43 +0000] "POST /inference.GRPCInferenceService/ModelInfer HTTP/2.0" 504 160 "-" "tonic/0.7.2" 1597762 60.006 [triton-backend] [] <triton-server>:8001 0 60.006 504 f72a4feb3f83765f43f00522ae647519
````

**Comment by oandreeva-nv** [comment]
CC @jbkyang-nvi , is this something related to the timeout ticket you were working with recently?

**Comment by jbkyang-nvi** [comment]
@oandreeva-nv that one has not been merged yet. Would adding `timeout:0s` solve the problem in `envoy.yaml`? 
ref: https://github.com/envoyproxy/envoy/issues/17697 and https://stackoverflow.com/questions/68759061/envoy-proxy-with-grpc-server-streaming-throwing-unavailable-upstream-request-ti

**Comment by oavner** [comment]
Although were not using envoy proxies i tried implementing some parallel NGINX configurations to the solution that @jbkyang-nvi suggested: 
1. setting `proxy_connect_timeout` to 0s did not solve the problem since this isnt a connect timeout but reading client response header.
2. setting `client_header_timeout` to 0s did not solve the problem since we timed out immediately for every request.
3. setting `proxy_read_timeout` to 0s did not solve the problem since we timed out immediately for every request, again.
4. setting `keepalive_timeout` to 0s did not solve the problem since we timed out immediately for every request, the third time.

Ill be honest and say that this solution seemed a tiny bit odd since were getting the timeout error when its taking more then 60 seconds to read the triton server's response header, so i though we should try increasing the timeout setting instead of decreasing it to zero. So i tried to remove the timeout limit from every possible timeout NGINX config by setting it to 0 (not 0s) and were still getting this notorious 60s response header timeout error.

another way i tried solving this is by increasing the amount of `keepalive_connections` since i though this might be a mismatch between `http2_max_connections` and the `keepalived_connections`, but again nothing really changed.

can i get some more info about the timeout ticket u guys r talking about? if u got some extra data about whats happening with the triton server in these cases, i might be able to find a valid solution until  @jbkyang-nvi 's PR is merged :)

**Comment by jbkyang-nvi** [comment]
@oavner I mostly searched for `upstream request timeout` for the suggested solution. The thing we have a ticket for is to set client timeout for each of the APIs [code comparison link here](https://github.com/triton-inference-server/client/compare/main...kyang-timeout-to-client-apis).  I do not think it will solve your problem since your problem seems like that there is an increase in time to read the server's response header.
I also looked through the commits from [23.02-23.07](https://github.com/triton-inference-server/client/compare/r23.02...r23.07) there does not seem like there has been any significant changes in how we send requests. 
To be clear, you're using both the 23.07 server and 23.07-sdk, correct? How frequently is this happening?

@GuanLuo anything on the server side which could have made the request times be longer?

**Comment by dyastremsky** [comment]
Closing ticket due to inactivity. If you would like to reopen it, let us know.
