### ISSUE TITLE
Metrics Incompatibility in Triton Inference Server

### ISSUE THREAD

**Issue by levipereira** [triton-inference-server/server#6362]
**Description**
Hello,

I hope this message finds you well. I'm encountering an issue related to metric inconsistencies in NVIDIA Triton Inference Server, and I would appreciate some guidance on how to resolve it.

I'm currently processing a single video at a frame rate of 30 FPS using Triton Server, and I'm monitoring the following metrics:
- `rate(nv_inference_count[1m])`: This metric indicates the number of inferences processed per minute and correctly shows 30 FPS, which is expected.

However, the issue arises with the following metric:
- `rate(nv_inference_request_duration_us[1m])`: This metric represents the time spent on processing inferences in microseconds and consistently reports a value around 170ms. This value is significantly higher than expected and incompatible with the 30 FPS frame rate I'm processing. In fact, the correct value should ideally be a maximum of 33ms to accommodate a 30 FPS workload.

It's worth noting that these metrics are collected for Prometheus and visualized using Grafana as a dashboard.

I would greatly appreciate any insights or suggestions on how to address this metric inconsistency and ensure that `nv_inference_request_duration_us` aligns more accurately with the expected processing time for a 30 FPS workload.

`nv_inference_count` refers Inference/second
`nv_inference_request_duration_us`  refers Request Inference Time 
`nv_inference_compute_infer_duration_us` refers Inference Time Graph

Thank you for your assistance.

![image](https://github.com/triton-inference-server/server/assets/22964932/5f7b3136-4709-484d-bed9-10941f386421)
![image](https://github.com/triton-inference-server/server/assets/22964932/d91ccd09-a106-4f1f-9951-ca38284d2e7b)

**Triton Information**
What version of Triton are you using?
 Nvidia Triton Server (v)2.26.0 - CUDA : 11.8 - TensorRT: 8.5.0.12

Are you using the Triton container or did you build it yourself?
nvcr.io/nvidia/tritonserver:22.09-py3

**Comment by dyastremsky** [comment]
Can you share your model configuration? If you have dynamic batching enabled or multiple model instances, that could be the reason. You would be processing requests in parallel.

Also, would you be able to try with a more recent version of Triton (e.g. 23.08) to see how it compares? We are improving Triton on an ongoing basis, so it's possible that there was a patch in the time since that would have fixed any incompatibility.

**Comment by levipereira** [comment]
Yes i have dynamic batching and instance group.
How I can use this metric since I can't understand it.  If I change  instance group to 3 or 4 this value will change.

```
instance_group [
    {
      count: 2
      kind: KIND_GPU
      gpus: [ 0 ]
    }
]
version_policy: { latest: { num_versions: 1}}
dynamic_batching {
}
```
I'm using Deepstream 6.2, I can use Triton Server  23.08 as supported version?

https://github.com/NVIDIA-AI-IOT/deepstream_triton_migration
The current version used by DS 6.2 official release is 22.09: nvcr.io/nvidia/tritonserver:22.09-py3

**Comment by dyastremsky** [comment]
It looks like you can change the Triton version [here](https://github.com/NVIDIA-AI-IOT/deepstream_triton_migration#11-deepstream-x86-docker-image-update). If you need more details than that, the Deepstream team would be the better resource.

You can see the metric definitions [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#counters). For `nv_inference_request_duration_us`, the definition is `Cumulative end-to-end inference request handling time (includes cached requests)`. If you are using 2-4 instances with the default maximum batch size of 4, you would in most cases have a much higher number of inferences per second processed than if you have 1 instance without batching (i.e. with one request sent at a time).

It sounds like the confusion is stemming from the fact that the requests are being processed in parallel. Tour latency in regards to the end-to-end inference request handling time is still 170ms. Your throughput is higher because you have multiple requests being processed at the same time.

If you want to explore the throughput vs latency tradeoffs for different model configuration, [Model Analyzer](https://github.com/triton-inference-server/model_analyzer) is a good place to play with this. You could also try [perf analyzer](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/perf_analyzer.md).

**Comment by levipereira** [comment]
The video is being processed at the same frame rate at which it was generated, so there is a processing limit of 30 fps.
Per as my understand, since I processing a single video at 30fps (deepstream) batch size will be 1 and this time
I'll disable dynamic batching and use one instance group to check and limit  processing at 30fps  with batch size 1

**Comment by dyastremsky** [comment]
Yes, disabling dynamic batching and using one instance can help gain clarity.

The best thing you can do here is probably to try enabling [tracing](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/trace.html) to get more information. That will give you the timestamps so that you can see exactly what is happening. For example, it's possible that any individual request will take > 33ms to process, but increasing the throughput ceiling via dynamic batching and increased instance counts helps keep the throughput 30 fps as expected. It's also possible that increasing the instance count results in smaller requests (smaller batches) sent to each instance, speeding up the latency of each request. The traces are going to give you the best information there.

**Comment by levipereira** [comment]
I've identified the root cause of the problem:
To calculate the time taken per inference, I have to divide nv_inference_request_duration_us by nv_inference_count as follows:
```
rate(nv_inference_request_duration_us[1m]) / rate(nv_inference_count[1m])
```

Just to provide some context, it took a total of 170 milliseconds to process 30 frames per second (FPS)
In this case, I have mentioned that it took a total of 170 milliseconds to process 30 frames  .  
 170 ms  / 30 frames = 5,67 ms/inference

So, the rate of processing in this scenario is approximately  5,67 ms per frame

Apologies for any previous misunderstandings.
