### ISSUE TITLE
[question] maxine denoiser model in triton server

### ISSUE THREAD

**Issue by jsoto-gladia** [triton-inference-server/server#6375]
Hello,

I am currently using the maxine sdk because we see great denoising performances out of it.

My goal is to be able to set up the denoiser model directly in the triton server and not to have to use the effect_demo executable that loads and runs the model at each inference.

Do you know how I can achieve this? Could I get access to the tensortrt.plan or something similar
Any other ideas ?

Thanks for the help

**Comment by jsoto-gladia** [comment]
@jqueguiner

**Comment by tanmayv25** [comment]
@jsoto-gladia This question seems to be outside the scope of Triton Inference Server. I will route the query to Nvidia Maxine team for the response.

**Comment by dyastremsky** [comment]
I'm going to close this issue. NVIDIA Maxine has different GitHub repositories based on which SDK you are using (e.g. their AR SDK repository [here](https://github.com/NVIDIA/MAXINE-AR-SDK)). If Tanmay is able to get a response from Maxine here, I can reopen this issue. Otherwise, the Maxine repository corresponding to your SDK would be the best place to ask this question.
