### ISSUE TITLE
Problems with core development build

### ISSUE THREAD

**Issue by rhamilt** [triton-inference-server/server#6434]
I am having trouble using a development build of the core repository as specified [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/customization_guide/build.html?highlight=buildbase#development-build-of-triton-core). I believe I have followed all the directions properly. I have modified the commands in the `cmake_build` file to build in the core directory that I mapped in to the `tritonserver_buildbase` image and specified the `cmake` command to use `/server` instead of `/workspace`, but didn't have any luck getting my changes to show up. I tried running the executable output by the build as `/tmp/tritonbuild/install/bin/tritonserver`, but it did not have any of the changes.

Am I missing an obvious way to actually run the server with my core changes? Is there a way I can specify a local repository to use as source for the build? Thanks!

**Comment by jbkyang-nvi** [comment]
Can you just mount the core directory onto the original core repository when you run docker?

**Comment by rhamilt** [comment]
What I did was mapped the source for the core into the `buildbase` container and then made the `cmake_build` script use that directory as the source for the `cmake` and `make`. What do you mean by 

> mount the core directory onto the original core repository when you run docker

I had trouble finding where the original core repo was coming from in the python build script, so I'm not sure what the best way to mount over that is.

**Comment by jbkyang-nvi** [comment]
Where are you making the changes? In the core repo? 
The core repo build is included everywhere in the Triton build so you you will need to change every backend build and change the core repo it includes to the backend build.

To only change it in the core part of the build:
Your core build command is something like this I assume:
```
mkdir -p /tmp/tritonbuild/tritonserver/build
cd /tmp/tritonbuild/tritonserver/build
cmake "-DTRT_VERSION=${TRT_VERSION}" "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}" "-DVCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET}" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX:PATH=/tmp/tritonbuild/tritonserver/install" "-DTRITON_VERSION:STRING=2.40.0dev" "-DTRITON_COMMON_REPO_TAG:STRING=main" "-DTRITON_CORE_REPO_TAG:STRING=main" "-DTRITON_BACKEND_REPO_TAG:STRING=main" "-DTRITON_THIRD_PARTY_REPO_TAG:STRING=main" "-DTRITON_ENABLE_LOGGING:BOOL=ON" "-DTRITON_ENABLE_STATS:BOOL=ON" "-DTRITON_ENABLE_METRICS:BOOL=ON" "-DTRITON_ENABLE_METRICS_GPU:BOOL=ON" "-DTRITON_ENABLE_METRICS_CPU:BOOL=ON" "-DTRITON_ENABLE_TRACING:BOOL=ON" "-DTRITON_ENABLE_NVTX:BOOL=OFF" "-DTRITON_ENABLE_GPU:BOOL=ON" "-DTRITON_MIN_COMPUTE_CAPABILITY=6.0" "-DTRITON_ENABLE_MALI_GPU:BOOL=OFF" "-DTRITON_ENABLE_GRPC:BOOL=ON" "-DTRITON_ENABLE_HTTP:BOOL=ON" "-DTRITON_ENABLE_SAGEMAKER:BOOL=ON" "-DTRITON_ENABLE_VERTEX_AI:BOOL=ON" "-DTRITON_ENABLE_GCS:BOOL=ON" "-DTRITON_ENABLE_S3:BOOL=ON" "-DTRITON_ENABLE_AZURE_STORAGE:BOOL=ON" "-DTRITON_ENABLE_ENSEMBLE:BOOL=ON" "-DTRITON_ENABLE_TENSORRT:BOOL=ON" /workspace
make -j256 VERBOSE=1 install
... other copying things ...
```
I don't think copying over the core repo to workspace will solve the problem since the repo is trying to pull from `main`  as seen from `"-DTRITON_CORE_REPO_TAG:STRING=main"` in the cmake command. 
I would suggest trying:
1. After the running cmake command copy your changes to /workspace/_deps/repo-core-src 
2. Push your Modifying CMakeList to a branch and change 
`GIT_REPOSITORY https://github.com/triton-inference-server/core.git` to your cloned repo.

**Comment by rhamilt** [comment]
Changing the git repository in the CMakeList fixed the issue!
