### ISSUE TITLE
Failed to pull the Triton Server Docker image.

### ISSUE THREAD

**Issue by 4BD0U** [triton-inference-server/server#6479]
Hello
When I try to pull the Triton Server image using the following command:

**sudo docker pull nvcr.io/nvidia/tritonserver:23.09-py3**

I encountered an issue. Despite trying different versions, none worked for me. The error message I received is:

**failed to register layer: archive/tar: invalid tar header**

Below is the information regarding my Docker version:

***
Version:           24.0.4
API version:       1.43
Go version:        go1.20.5
Git commit:        3713ee1
Built:             Fri Jul 7 14:50:57 2023
OS/Arch:           linux/amd64
Context:           default

Server: Docker Engine - Community
Engine:
 Version:          24.0.4
 API version:      1.43 (minimum version 1.12)
 Go version:       go1.20.5
 Git commit:       4ffc614
 Built:            Fri Jul 7 14:50:57 2023
 OS/Arch:          linux/amd64
 Experimental:     false
containerd:
 Version:          1.6.24
 GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
runc:
 Version:          1.1.9
 GitCommit:        v1.1.9-0-gccaecfc
docker-init:
 Version:          0.19.0
 GitCommit:        de40ad0
***

Thank you for assisting me in resolving this issue.

**Comment by dyastremsky** [comment]
This does not look like a Triton issue, so we are unfortunately unable to help. I am seeing different questions like [this one on Satck Overflow](https://stackoverflow.com/questions/75710177/docker-pull-error-failed-to-register-layer-error-processing-tar-fileexit-sta) about this online. Since this is a Docker issue, I recommend posting a question on the [Docker GitHub](https://github.com/docker).
