### ISSUE TITLE
What limits the throughput of model instances?

### ISSUE THREAD

**Issue by lzcchl** [triton-inference-server/server#6825]
I conducted some experiments on multi card with one model instance and single card with multi model instances, and used the perf analyzer tool to obtain throughput, but the results I obtained left me puzzled.

For example, when I use a single card with one model instance, I get a throughput of 100 times per second. Then, when I use two cards to enable a single model instance separately, the throughput is about 200, which is logical. However, when I use one card to enable two model instances, the throughput is about 160, and when I use one card to enable four model instances, the throughput is about 170.

Why does throughput not increase linearly in this situation? What constrains the performance of multiple model instances during triton runtime, leading to overall performance bottlenecks.

**Comment by lzcchl** [comment]
emmm, I will do more expEmmm, I am currently only conducting experiments on low-end graphics cards, and my high-end card is still being purchased, which will take a few weeks or even longer. After the card arrives, I will conduct more experiments to verify this issue, and then I will post my test data.

**Comment by tgerdesnv** [comment]
Many things can limit the throughput of model instances. Eventually you will either be compute bound (the gpu utilization is at or near 100%) or memory bound. It sounds like your low end card can handle about 160-170 requests per second. Adding more models on that GPU probably won't help since they will all be waiting for their turn to compute on the GPU.

You can also look at [Model Analyzer](https://github.com/triton-inference-server/model_analyzer) to try to find a better configuration to try to maximize your throughput.
