### ISSUE TITLE
Running asr streaming inference with triton server

### ISSUE THREAD

**Issue by Jank14** [triton-inference-server/server#6875]
Hi, I am trying to run wav2vec2 model with language model decoding on triton server. It works fine for single request. Now I want to try is running online streaming inference using triton. I want to run continuous microphone stream, and once enough chunk size is achieved get output for that chunk back and continue this the stream stops. How can I achieve this? Should I use websockets to stream the audio and how can i get sequential output for the chunks without compromising on performance. I am very new to this field so any help is appreciated. Thanks

**Comment by Jank14** [comment]
I have checked kaldi online inference notebook but that is outdated api and also I have the triton server hosted on an ubuntu server so would be able to send direct microphone recording from my local to the triton server

**Comment by Jank14** [comment]
> Hi @Jank14,
> 
> > I want to run continuous microphone stream, and once enough chunk size is achieved get output for that chunk back and continue this the stream stops. How can I achieve this?
> 
> The [dynamic batcher](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#dynamic-batcher) allows the combining of one or more inference requests into a single batch. If the model is stateful, the [sequence batcher](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#sequence-batcher) should be used instead.
> 
> > Should I use websockets to stream the audio and how can i get sequential output for the chunks without compromising on performance
> 
> Here is an example to stream inference requests using [gRPC protocol](https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/inference_protocols.md#grpc-options): https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_aio_sequence_stream_infer_client.py

Hi @kthui I would be using this with michrophone stream where till the time stream is up, audio chunks would be sent to the model for inference. For this the first input would be a buffer + audio_chunk(of some size) and then the next input would be some part of previous input and the new audio chunk from the stream. This is kindoff shown in kaldi asr online notebook. Which batcher would be best for this usecase. We would prefer low latency as well. Should I be using async like in the above mentioned [simple_grpc_aio_sequence_stream_infer_client.py](https://github.com/triton-inference-server/client/blob/main/src/python/examples/simple_grpc_aio_sequence_stream_infer_client.py)

**Comment by kthui** [comment]
> Which batcher would be best for this usecase.

You mentioned two inputs
1. the first input would be a buffer + audio_chunk(of some size)
2. the next input would be some part of previous input and the new audio chunk

To determine which batcher to use: Can the second input be executed before the first input? If yes, then the [dynamic batcher](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#dynamic-batcher) is the one to use, because there is no dependencies between the first and second input. If no, then the [sequence batcher](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#sequence-batcher) should be used, which adds more constraints on the order and which model instance the requests are to be executed on.

> Should I be using async like in the above mentioned

The Python client supports both threaded and AsyncIO interface. It is mainly a personal preference on which interface you would like to code on. Although people on the internet commented AsyncIO being faster than threading on Python, every setup is different and you would have to experiment on which one is faster on your environment.

**Comment by Jank14** [comment]
@kthui Thanks a lot this was helpful
