### ISSUE TITLE
CPU-only build hangs for python backend

### ISSUE THREAD

**Issue by michael-ryan-warner** [triton-inference-server/server#6915]
**Description**
I want to build a CPU-only image with a python backend. After building, the server hangs when I attempt to start it (see screenshot).

Using a prebuilt image or building a GPU image with `compose.py` does not have this problem.

I generally don't have this problem across many other models and repositories, only when attempting to build a CPU-only image.

I also tried adding `--backend pytorch` to the build command and had the same result.

**Triton Information**
Version: v2.42.0

Built image myself using `python3 build.py --backend python`

**To Reproduce**
1. Build image: `python3 build.py --backend python`
2. Download [add_sub](https://github.com/triton-inference-server/python_backend/tree/main/examples/add_sub) model, place in `models/add_sub`. Place `model.py` in `models/add_sub/1`.
3. Run image: `docker run --shm-size=1g --ulimit memlock=-1 -p 8000:8000 -p 8001:8001 -p 8002:8002 --ulimit stack=67108864 -v $PWD/models:/models tritonserver:latest tritonserver --model-repository=/models`
4. Saw same problem with simpler command `docker run -v $PWD/models:/models tritonserver:latest tritonserver --model-repository=/models`

**Expected behavior**
The server should start and allow requests to be sent.

<img width="787" alt="Screenshot 2024-02-24 at 9 05 25 AM" src="https://github.com/triton-inference-server/server/assets/107935066/6fafc1a4-6eaf-4d0c-b021-5cac0fea719a">

**Comment by fpetrini15** [comment]
Hi @michael-ryan-warner,

The server is not hanging, it's actually running! It's just not producing output because the `--enable-logging` flag was not set in your build command.

Ultimately, if you rebuild with logging enabled, you will still encounter an issue--your server will have no endpoints for you to communicate with.

I would suggest this minimal build command (you can replace http with grpc if you prefer or enable both):
`python3 build.py --enable-logging --endpoint http --backend python`

To see a full list of build options, please invoke the help option:
`python3 build.py --help`

**Comment by michael-ryan-warner** [comment]
@fpetrini15 thank you for your help! Yes I was just confused, thanks!
