### ISSUE TITLE
decouple model abnormal dynamic batching result

### ISSUE THREAD

**Issue by hrfng** [triton-inference-server/server#6922]
**Description**
I find a very strange behavior when using decouple mode + dynamic batching.

I used the vllm backend like official manner, small modified to support the decouple model

when I ran a performance testing, client set the 1000 thread parallel call.

case 1. set the model non-decoupled + set the dynamic batching with max_batch_size 64
case 2. set the model decoupled + set the dynamic batching with max_batch_size 64

### The Result:

case 1, non-decoupled vllm backend model get the stable batched requests, size is mostly 64, gpu utility  get 70% avg
 ```
    data: alpaca_data, model: Qwen-1_8B-Chat, vllm: 0.3.0， gpu memory 20g
    perf_n = 5000
    n_parallel = 1000
    non-stream Speed: 1720.6560135611235 tokens/s, avg req time: 51.12825612154007s, req_speed: 17.654344940686816 req/s, 
   tokens: 487318
```

case 2, decoupled vllm backend model, firstly get the batched requests size equals to 64, then quickly decrease to 3-10, gpu utility get 30%
```
  data: alpaca_data, model: Qwen-1_8B-Chat, vllm: 0.3.0， gpu memory 20g
  perf_n = 5000
  n_parallel = 1000
  Speed: 993.6950416055031 tokens/s, req_latency: 26.75894072556496, first_token_latency: 0.00014983115196228028, req_speed: 9.287129934535576, tokens: 534985
```

**Triton Information**

I build Triton with my own logic, server commit f2cd99:  others components are r23.10

**To Reproduce**

**Expected behavior**

I expect the decoupled model + dynamic batching with 1000 thread parallel call, will get the stable batch size (the max_batch_size)

which reason may cause this result?
I increase the http_thread_cnt to 64, the result is not chaning.

**Comment by hrfng** [comment]
config likie
```
 {
    name: "dataelem.pymodel.vllm_model"
    backend: "python"
    max_batch_size: 64

   model_transaction_policy {
     decoupled: True
   }

   dynamic_batching {
      max_queue_delay_microseconds: 500000
    }
    parameters { key: "pymodel_type" value: { string_value: "" } }

    input [
      { name: "INPUT", data_type: TYPE_STRING, dims: [ 1 ] }
    ]

    output [
      { name: "OUTPUT", data_type: TYPE_STRING, dims: [ 1 ] }
    ]

    instance_group [ { count: 1, kind: KIND_CPU } ]
  }
```

**Comment by fpetrini15** [comment]
Hi @hrfng,

I believe this makes sense. You are observing much higher throughput performance when using decoupled mode vs non-decoupled mode because in decoupled mode Triton can receive responses out of order, reducing latency. I believe you can get your batch more consistently close to 64 by specifying a [preferred batch size](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/model_configuration.html#preferred-batch-sizes) of 64 and potentially modifying the `max_queue_delay_microseconds`. Ultimately, I believe these numbers indicate the decoupled server can handle a higher workload. That said, there are many variables in benchmarks like these and I am not sure which profiler you used or how those numbers are collected. Might I suggest using Triton's [performance analyzer](https://github.com/triton-inference-server/client/blob/main/src/c++/perf_analyzer/README.md) to collect your performance data so we have a tool in common?

Also a few notes:
1. It seems like you are using the python backend to server a vllm model, not the [vllm backend](https://github.com/triton-inference-server/vllm_backend).
2. If you are interested in maximum GPU usage, consider deploying the server as an instance of `KIND_GPU`

CC: @oandreeva-nv for accuracy

**Comment by hrfng** [comment]
@fpetrini15 thx for you reply. 
1. yes, I use the python backend. the inner logic is almost same with vllm backend implementation.
2. yes, I want to get a high gpu usage. I will change the instance property to KIND_GPU.

My result show that, decoupled model has low throughput performance: 
non-decouple model get 17.6 req/second compared to 9.2 req/second in decoupled model. 

The reason I guess is that, when in the decoupled model, the dynamic batch size batched less reqs compared to the non decoupled model, which will decrease the in-flight batching size in the vllm ray workers

**Comment by hrfng** [comment]
the perf scripts
```python
def perf():
  alpaca_file = '../../benchmarks/data/alpaca_data_zh_51k.json'
  alpaca = json.load(open(alpaca_file))
  prompts = []
  for sample in alpaca:
    input_text = sample.get('input', '')
    instruction = sample.get('instruction', '')
    prompts.append('{} {}'.format(instruction, input_text))

  print('--- number of total prompts', len(prompts))
  stream = False
  print(test_qwen_chat(prompts[0], stream))
  # test_qwen_batch(prompts[:10])
  # return

  warm_n = 100
  start_n = 20000
  perf_n = 500
  n_parallel = 50

  perf_prompts = prompts[start_n + warm_n: start_n + perf_n + warm_n]
  n_prompts = len(perf_prompts)
  batch = int(math.ceil(n_prompts / n_parallel))

  t0 = time.time()
  futures_data = []
  rets = []
  with tqdm.tqdm(total=n_prompts) as pbar:
    with concurrent.futures.ThreadPoolExecutor(max_workers=n_parallel) as executor:
        futures_data = [executor.submit(test_qwen_chat, prompt, stream) for prompt in perf_prompts]
        for future in concurrent.futures.as_completed(futures_data):
            rets.append(future.result())
            pbar.update(1)

  elapse = time.time() - t0
  token_n = sum([ret['usage']['completion_tokens'] for ret in rets])
  token_speed = token_n / elapse
  mean_1token_latency = sum([ret['usage']['first_token_latency'] for ret in rets]) / n_prompts
  mean_req_latency = sum([ret['usage']['req_latency'] for ret in rets]) / n_prompts
  req_speed = n_prompts / elapse

  print('Speed: {} tokens/s, req_latency: {}, first_token_latency: {}, req_speed: {}, tokens: {}'.format(
    token_speed, mean_req_latency, mean_1token_latency, req_speed, token_n))

```

**Comment by thanhtung901** [comment]
hi @hrfng 
i am configuring tritonserver with vllm backend and using dynamic batching, but i have error relate to file config.txt, you can share file config.txt for me? tks
