### ISSUE TITLE
python backend's environment

### ISSUE THREAD

**Issue by leafjungle** [triton-inference-server/server#7097]
(1) if my python code is developed by python2.7, is it possible to be deployed in triton as a python backend?

(2) what is the environment requirments for python backend ?
     Can my python backend run in one container, and triton server run in another one?  One Kubernetes Pod with Two Containers !
     thus their environments will not be conflict.

**Comment by Tabrizian** [comment]
Python backend is not supported on Python 2.7 since Python 2 is considered EOL. 

> Can my python backend run in one container, and triton server run in another one? One Kubernetes Pod with Two Containers !

No, currently Python backend uses shared memory to connect with the parent process and it is not possible to run in different containers.

Could you share more regarding your use-case and what you're trying to accomplish?

**Comment by leafjungle** [comment]
@Tabrizian , thank you for your kindly reply.    

yes, python2.7 is old.  but python with version < 3.8 also can not  be deployed in triton as a python backend.

Many old programs is developed by python2.7 or python<3.8,  it is really hard to migrate them to triton.

**Comment by Tabrizian** [comment]
Unfortunately, Python <3.8 are all considered EOL. My suggestion is to try to create a custom fork and make all the modifications needed to support older Python versions.
