### ISSUE TITLE
How does Triton implement one instance to handle multiple requests simultaneously?

### ISSUE THREAD

**Issue by SeibertronSS** [triton-inference-server/server#7295]
I am trying to implement a custom triton backend in C++ that will use the decoupled mode to return multiple times for each request. I implemented a queue in the triton backend so that I can customize the scheduling of all requests. According to the repeat_backend example, I need to return TRITONBACKEND_ModelInstanceExecute immediately after the request is enqueued so that the backend can immediately enqueue the next request. However, ending the TRITONBACKEND_ModelInstanceExecute function causes all pointers declared before enqueuing to become dangling pointers, including the TRITONBACKEND_ResponseFactory* required for decoupled returns. How should I handle this situation?

**Comment by kthui** [comment]
Hi @SeibertronSS, if I understand your question correctly, there are two cases that can happen:
```c++
...
TRITONBACKEND_ModelInstanceExecute(...)
{
  ...
  // case 1
  int my_int = 123;
  my_int_pointer_queue_.push(&my_int);

  // case 2
  TRITONBACKEND_ResponseFactory* factory_pointer;
  TRITONBACKEND_ResponseFactoryNew(&factory_pointer, ...);
  factory_pointer_queue_.push(factory_pointer);

  ...
  return nullptr;
}
```

For case 1, you are correct that the `&my_int` is a dangling pointer, because it is declared in the scope of `TRITONBACKEND_ModelInstanceExecute()` function and it will be erased once the function returns. My recommendation is to use a [shared pointer](https://en.cppreference.com/w/cpp/memory/shared_ptr) or [unique pointer](https://en.cppreference.com/w/cpp/memory/unique_ptr) in this case for managing the lifecycle of the object.

For case 2, The `TRITONBACKEND_ResponseFactory` object is managed by Triton core, so its pointer will not be dangling after `TRITONBACKEND_ModelInstanceExecute()` function returns. Make sure to call [TRITONBACKEND_ResponseFactoryDelete](https://github.com/triton-inference-server/core/blob/main/src/backend_model.cc#L1478) with the pointer after you are done sending all the response(s) and final flag for the request, to delete the response factory object.

**Comment by statiraju** [comment]
@SeibertronSS Did the instructions help you

**Comment by SeibertronSS** [comment]
Yes, I have stored all the required variables in a custom request structure to ensure that their life cycle is consistent with the inference cycle.
