### ISSUE TITLE
The trt llm container does not have the other backends

### ISSUE THREAD

**Issue by MatthieuToulemont** [triton-inference-server/server#7346]
I want to run a version of triton that has both the TensorRT LLM backend and the other backends (TensorRT, ONNX, TorchScript) is it possible ? 

Container version: 24.05

**Comment by MatthieuToulemont** [comment]
Ok, is the python backend from the trt-llm different from the one of 24.05-py3 ?

**Comment by krishung5** [comment]
No, the Python Backend should be the same.

**Comment by tricky61** [comment]
> No, the Python Backend should be the same.

Does the 24.05-py3 contain backends of ONNX、TensorRT and TorchScript?

**Comment by krishung5** [comment]
@tricky61 The `nvcr.io/nvidia/tritonserver:24.05-py3` container contains ONNX, TRT and PyTorch backends. The `nvcr.io/nvidia/tritonserver:24.05-trtllm-python-py3` only has TRTLLM and Python backends.

**Comment by tricky61** [comment]
> @tricky61 The `nvcr.io/nvidia/tritonserver:24.05-py3` container contains ONNX, TRT and PyTorch backends. The `nvcr.io/nvidia/tritonserver:24.05-trtllm-python-py3` only has TRTLLM and Python backends.

ok. I am using nvcr.io/nvidia/tritonserver:24.05-vllm-python-py3
I also use tritonserver:23.11 and add vllm backend manually. 
I will try to add vllm backends to nvcr.io/nvidia/tritonserver:24.05-py3 manually. 
Does this method make difference？because the nvcr.io/nvidia/tritonserver:24.05-vllm-python-py3 is 11.2 GB and nvcr.io/nvidia/tritonserver:24.05-py3 costs 7.55GB

**Comment by krishung5** [comment]
@tricky61 It shouldn't make any difference. Note that you'd have to `pip install vllm` and make sure `model.py` exists under `/opt/tritonserver/backends/vllm_backend`.

**Comment by Tabrizian** [comment]
Closing due to in-activity.
