### ISSUE TITLE
Decoupled mode, dimensionality explosion

### ISSUE THREAD

**Issue by SeibertronSS** [triton-inference-server/server#7378]
I implemented a continuous batching backend in C++, which supports streaming back the results of LLM. However, sometimes when the results of LLM are returned to the postprocessing for decoding, the dimension of the token will be multiplied by 2 after each step, and finally I will get an output_id with tens of millions of dimensions. I don't know if it's because Triton caches the answer or my buffer is not cleared in time. The answer output to postprocessing is like [8908, 8908, 234, 8908, 8908, 234, 114, 8908, 8908, 234, 8908, 8908, 234, 114, 103081, 8908, 8908, 234, 8908, 8908, 234, 114, 8908, 8908, 234, 8908, 8908, 234, 114, 103081, 99662, 8908, 8908, 234, 8908, 8908, 234, 114, 8908, 8908, 234, 8908, 8908, 234, 114, 103081, 8908, 8908, 234, 8908, 8908, 234, 114, 8908, 8908, 234, 8908, 8908, 234, 114, 103081, 99662, 99808, 8908, 8908, 234, 8908, 8908, 234, 114, 8908, 8908, 234, 8908, 8908, 234, 114, 103081, 8908, 8908, 234, 8908, 8908, 234, 114, 8908, 8908, 234, 8908, 8908, 234, 114, 103081, 99662, 8908, 8908, 234, 8908, 8908, 234, 114, 8908, 8908, 234, 8908, 8908, 234, 114, 103081, 8908, 8908, 234, 8908, 8908, 234, 114, 8908, 8908, 234, 8908, 8908, 234, 114, 103081, 99662, 99808, 99219, 9909]

**Comment by statiraju** [comment]
kindly provide the following information:

**Description**
A clear and concise description of what the bug is.

**Triton Information**
What version of Triton are you using?

Are you using the Triton container or did you build it yourself?

**To Reproduce**
Steps to reproduce the behavior.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
A clear and concise description of what you expected to happen.

**Comment by SeibertronSS** [comment]
I found out that the reason was a bug in my custom backend
