### ISSUE TITLE
Understanding and customize the vLLM backend 

### ISSUE THREAD

**Issue by CoolFish88** [triton-inference-server/server#7429]
Hello @oandreeva-nv and @dyastremsky,
 
As a new user of the vLLM backend, I found the [guideline](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md#deploying-a-vllm-model-in-triton) slightly unclear (which may very well be due to my lack of experience with Triton). I have a few questions whose answer I hope I can find here. Specifically, I noticed that the guideline references different model files (model.json and [model.py](https://github.com/triton-inference-server/vllm_backend/blob/main/src/model.py)), where model.json is is used to provide further settings to the vLLM engine. 

- What is the connection between the two files?
  - Do they have to co-exist in the sense that both need to be present or specified?
  - If I use model.json to specify vLLM parameters, are these sent to the [model.py](https://github.com/triton-inference-server/vllm_backend/blob/main/src/model.py) backend?
- The [model.py](https://github.com/triton-inference-server/vllm_backend/blob/main/src/model.py) vLLM backend defines a [custom auto_complete_config method](https://github.com/triton-inference-server/vllm_backend/blob/main/src/model.py#L48). 
  - Will this overwrite the contents of a user supplied config.pbtxt in the model registry? 
  - If affirmative, do I need to change auto_complete_config method with my custom code?
  - If negative, will [vLLM specific settings in auto_complete_config](https://github.com/triton-inference-server/vllm_backend/blob/main/src/model.py#L94-L97) still be executed?
  - What would be the best approach in the vLLM backend context to operate in with user supplied config files? 
- I already have a model.py which I would like to operate with the vLLM backend.
  - Do I need to merge my version of model.py with the vLLM variant in order to accomplish this goal?
  - If affirmative, to I put the refactored model.py in the model repository without a model.json (by incorporating vLLM engine parameters in the model.py code)?
  - If negative, how can I use my custom code with the vLLM backend?
 
Please feel free to defer these questions to other contributors. I understand some of these questions may sound stupid, but they need to be asked to move towards knowledge. 

Thank you for your support!

**Comment by dyastremsky** [comment]
The model.py is what's used by Triton as the vLLM backend (technically an implementation of the [Python backend](https://github.com/triton-inference-server/python_backend). It'll exist in a vLLM directory under the backends directory. If you want to understand that directory structure better, you can read about how Triton backends and custom backends work in the [backend repo](https://github.com/triton-inference-server/backend?tab=readme-ov-file#can-i-add-or-remove-a-backend-to-an-existing-triton-installation).

If you're trying to modify model.py to work with the vLLM engine differently, that's the place to do it. You're essentially creating your own Python backend though, so that may require going through documentation a bit, including the links above. Otherwise, you'd want to leave this file as is and that tutorial should set you in the right direction.

As far as autocomplete, it should only run if the config.pbtxt is not provided or certain fields are not provided.

**Comment by CoolFish88** [comment]
Hello @oandreeva-nv and @dyastremsky,

Thank you for addressing my questions in plenty of detail. 

I had previously consulted the documentation of the python backend when drafting the custom model.py file according to the TritonPythonModel interface. This file would reside under the model repository path, as showcased [here](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_repository.md#python-models), and the config.pbtxt file would reference the python backend. And the world was a happy place to be in. 

Then I decided to leverage the advantages of the vLLM framework and things started to get really foggy really fast. At that point in time, I came across the [Python-based backends](https://github.com/triton-inference-server/backend/blob/main/docs/python_based_backends.md) that you referenced in the answers, and this is when things started to get unclear, as my model repository wouldn't contain the artefacts: libtriton_python.so, triton_python_backend_stub, and triton_python_backend_utils.py.

Correct me if my understanding is wrong:

- When using the Python backend, Triton Inference Server would look into my model repository and fetch my custom model.py implementation as a backend to use (if it doesn't exist, will it fetch the backend implementation by looking into /opt/tritonserver/backends/. ??), and use the three file artefacts (libtriton_python.so, triton_python_backend_stub, and triton_python_backend_utils.py) from the backend repository (since they are not present in the model repository). 

- When using a Python-based backend (e.g. vLLM), Triton Inference Server would ignore the model.py file located in the model repository and use the model.py file residing (together with the three file artefacts) in its own repository under /opt/tritonserver/backends/ 

Now, as my existing model.py implementation of the TritonPythonModel interface is devoid of any vLLM sugar and contains custom code in the `execute` and `initialize` methods, it seems that I have to merge the vLLM model.py with my own and resort to one of the two strategies that you @oandreeva-nv mentioned under bulletpoint 5. If I go for the first strategy, I may use model.json to pass parameters to the refactored version of vLLM backend containing bits of the custom code I needed.

Could you please validate my understanding?

**Comment by oandreeva-nv** [comment]
> When using the Python backend, Triton Inference Server would look into my model repository and fetch my custom model.py implementation as a backend to use

Not really. When you explicitly use python backend, it looks for `libtriton_python.so` (in your model's repo and under `backends/python/`) as a backend and your `model.py` is considered a model, which contains implimentation of `execute` function, which defines how to run your model. 

`libtriton_python.so` is the library, that implements [backend APIs](https://github.com/triton-inference-server/backend?tab=readme-ov-file#triton-backend-api), so that Triton Server knows how to run `model.py`. And `model.py` is basically your custom component. 

> When using a Python-based backend (e.g. vLLM), Triton Inference Server would ignore the model.py file located in the model repository and use the model.py file residing (together with the three file artefacts) in its own repository under /opt/tritonserver/backends/

It will try to find `.so` library first, when in case nothing is found, it will look for `libtriton_python.so` and use `model.py` as a common model definition for all custom models, that use this python-based backend.

> as my existing model.py implementation of the TritonPythonModel interface is devoid of any vLLM sugar and contains custom code in the execute and initialize methods, it seems that I have to merge the vLLM model.py

If you don't need anything from vLLM's `model.py` we provide, there is no need to use it. You can put your `model.py` under `backends/vllm_custom` and then specify `backend: vllm_custom` in your model's `config.pbtxt` files, make sure `backends/python` is also present and contains 3 files. If you need something we provide in vllm python backend, then yes, feel free to merge your 2 files.

**Comment by oandreeva-nv** [comment]
I'm closing this issue. Feel free to reach out with any other questions and I'll re-open if needed
