### ISSUE TITLE
Why there aren't generate and generate_stream api in http client?

### ISSUE THREAD

**Issue by MasterYi1024** [triton-inference-server/server#7602]
**Is your feature request related to a problem? Please describe.**

I'm wondering why there aren't generate and generate_stream api in http client?  
If I want to use the generate api in C++, should I add it to http client class?

How can I chat with LLM using http client?

Is there a demo?

**Describe the solution you'd like**

I want genetate and generate_stream api in C language.

**Describe alternatives you've considered**

Any alternatives will do. I just want to use triton(self built, triton client communicates with tritonserver) to chat with LLM.

**Additional context**

Nothing.

Thanks in advance:)

**Comment by KrishnanPrash** [comment]
Hello @MasterYi1024,

The `/generate` and `/generate_stream` endpoints were added to provide simpler text-in/text-out payloads without having to use `tritonclient` and bypassing dealing with input/output tensors. Due to this reason, I don't believe it is currently in the plan to support these endpoints within the `httpclient` class.

Currently, I would recommend following this [example](https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/examples/simple_http_infer_client.cc) for chatting with LLMs with the `httpclient`.
