### ISSUE TITLE
Can TIS run both vllm and torch backend together?

### ISSUE THREAD

**Issue by k0286** [triton-inference-server/server#7637]
**Is your feature request related to a problem? Please describe.**
I have some torch models on TIS, now I want to add a LLM model.

And I notice that TIS supports the vllm. But there are no Triton images on NGC can support both vllm and torch backend.

**Describe the solution you'd like**
Provide the Triton image support both vllm and torch backend.

**Describe alternatives you've considered**
Describe the reason why can not support vllm and torch backend at same time.

**Comment by tanmayv25** [comment]
@k0286  Ideally you should be able to build container image with [vLLM ](https://github.com/triton-inference-server/vllm_backend) and[ Torch](https://github.com/triton-inference-server/pytorch_backend) backend. 

Triton supports numerous backends which can lead to a large number of combinations - container images. Additionally, vLLM dependency is large in size so in order to avoid further increasing the image size vLLM container image does not carry any other backends.

However, for your use case, you can start with Triton container image with pytorch backend and install vLLM backend in it. See the instructions [here](https://github.com/triton-inference-server/vllm_backend?tab=readme-ov-file#option-3-add-the-vllm-backend-to-the-default-triton-container) on how to build this image.

**Comment by k0286** [comment]
Ty, I'll give it a try!
