### ISSUE TITLE
Could I get request access log instead of starting server with --verbose-log=1?

### ISSUE THREAD

**Issue by rithd** [triton-inference-server/server#776]
I want to get the statistics of the models calling, but I found that if I ran the docker of server with default parameters, the docker stdin logs didn't roll with the access log. However, if I run it with --verbose-log=1, the request logs can be writen like 
'I1021 15:24:02.193979 1 http_server.cc:399] HTTP request: 2 /api/infer/simple'
Though it prints successfully, there are many of others verbose log, which can occupy extra space.
Besides, the access log is so easy for statistics, we also need others information such as userip, request using time, headers , etc. Does TRTIS provide other method to achieve this requirement?

Thanks a lot.

**Comment by deadeyegoodwin** [comment]
TRTIS doesn't currently have this kind of per-request logging (log-verbose is primarily meant for debugging). We can consider adding it. Please provide a full list of your requirements. Note that such logging will likely have significant overhead in cases where the inference server is handling 1000's of requests per sec.

**Comment by rithd** [comment]
Get it. I want to log the userip, model name, inference time and input/output (maybe so long, it is only a suggestion :) ). I know it may influence the server's performence, so maybe it can be added in a special mode. But I think it is really useful for user especially who directly connect the server. Really expect it.


thanks

**Comment by deadeyegoodwin** [comment]
Marking as enhancement request. It is not clear how much of the requested data we can capture in an access log. Also, capturing inputs/outputs would in general be very expensive since those can be 10-100MBs in size (or larger) for some models especially at large batch size.

I should have mentioned earlier to make sure you are aware that there are all ready per-model aggregate statistics available by both the status API and the metrics API.

**Comment by rithd** [comment]
thanks~

**Comment by joneepenk** [comment]
+1, just want nginx like access log format.

**Comment by rithd** [comment]
@joneepenk Finally, I deployed a nginx server and passed the request to TRTIS so that I could collect the log. May help you~

**Comment by joneepenk** [comment]
@rithd thanks, currently i am trying to use a similar solution, Envoy as a reverse-proxy, if it's forward cost is bearable.

**Comment by dyastremsky** [comment]
As jackiexiao mentioned, trace settings should now be able to provide this log-level tracing. We've also updated logging quite a bit since this enhancement request was submitted.

Given these changes and the age of this enhancement request, I'm going to close this issue. If you would like it reopened for follow-up, please let us know.
